<? require_once("global/config.php"); 
/*
$res_acc = $db->Execute("select PK_ACCOUNT from Z_ACCOUNT WHERE PK_ACCOUNT != 1 ");
while (!$res_acc->EOF) {
	
	$res_m = $db->Execute("select * from M_PLACEMENT_COMPANY_EVENT_TYPE_MASTER WHERE ACTIVE = '1'");
	while (!$res_m->EOF) {
		$PLACEMENT_COMPANY_EVENT_TYPE['PK_PLACEMENT_COMPANY_EVENT_TYPE_MASTER'] = $res_m->fields['PK_PLACEMENT_COMPANY_EVENT_TYPE_MASTER'];
		$PLACEMENT_COMPANY_EVENT_TYPE['PLACEMENT_COMPANY_EVENT_TYPE'] 			= $res_m->fields['PLACEMENT_COMPANY_EVENT_TYPE'];
		$PLACEMENT_COMPANY_EVENT_TYPE['ACTIVE'] 							= 1;
		$PLACEMENT_COMPANY_EVENT_TYPE['PK_ACCOUNT'] 						= $res_acc->fields['PK_ACCOUNT'];;
		$PLACEMENT_COMPANY_EVENT_TYPE['CREATED_ON'] 						= date("Y-m-d H:i:s");
		$PLACEMENT_COMPANY_EVENT_TYPE['CREATED_BY'] 						= $_SESSION['ADMIN_PK_USER'];
		db_perform('M_PLACEMENT_COMPANY_EVENT_TYPE', $PLACEMENT_COMPANY_EVENT_TYPE, 'insert');

		$res_m->MoveNext();
	}
	
	$res_acc->MoveNext();
}
*/

/*
$res_acc = $db->Execute("SELECT * FROM `S_STUDENT_COURSE` ");
while (!$res_acc->EOF) {
	
	$PK_ACCOUNT = $res_acc->fields['PK_ACCOUNT'];
	$res_grade = $db->Execute("SELECT PK_GRADE  FROM `S_GRADE` WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND IS_DEFAULT =1 ");
	$STUDENT_FINAL_GRADE['PK_STUDENT_MASTER'] 		= $res_acc->fields['PK_STUDENT_MASTER'];
	$STUDENT_FINAL_GRADE['PK_STUDENT_ENROLLMENT'] 	= $res_acc->fields['PK_STUDENT_ENROLLMENT'];
	$STUDENT_FINAL_GRADE['PK_COURSE_OFFERING'] 		= $res_acc->fields['PK_COURSE_OFFERING'];
	$STUDENT_FINAL_GRADE['GRADE'] 					= $res_grade->fields['PK_GRADE'];
	
	$STUDENT_FINAL_GRADE['PK_ACCOUNT'] 				= $PK_ACCOUNT;
	$STUDENT_FINAL_GRADE['CREATED_ON'] 				= date("Y-m-d H:i:s");
	$STUDENT_FINAL_GRADE['CREATED_BY'] 				= $_SESSION['ADMIN_PK_USER'];
	db_perform('S_STUDENT_FINAL_GRADE', $STUDENT_FINAL_GRADE, 'insert');

	
	$res_acc->MoveNext();
}*/

/*
$res_acc = $db->Execute("select PK_ACCOUNT from Z_ACCOUNT WHERE PK_ACCOUNT != 1 ");
while (!$res_acc->EOF) {
	
	$res_m = $db->Execute("select * from M_SESSION_MASTER WHERE ACTIVE = '1' ");
	while (!$res_m->EOF) {
		$SESSION['PK_SESSION_MASTER'] 	= $res_m->fields['PK_SESSION_MASTER'];
		$SESSION['SESSION'] 			= $res_m->fields['SESSION'];
		$SESSION['DISPLAY_ORDER'] 		= $res_m->fields['DISPLAY_ORDER'];
		$SESSION['COLOR'] 				= $res_m->fields['COLOR'];
		$SESSION['ACTIVE'] 				= 1;
		$SESSION['PK_ACCOUNT'] 			= $res_acc->fields['PK_ACCOUNT'];
		$SESSION['CREATED_ON'] 			= date("Y-m-d H:i:s");
		$SESSION['CREATED_BY'] 			= $_SESSION['ADMIN_PK_USER'];
		db_perform('M_SESSION', $SESSION, 'insert');
		
		$res_m->MoveNext();
	}
	
	$res_acc->MoveNext();
}
*/
/*
$res_acc = $db->Execute("select PK_STUDENT_ENROLLMENT, PK_ACCOUNT, PK_SESSION from S_STUDENT_ENROLLMENT ");
while (!$res_acc->EOF) {
	$PK_STUDENT_ENROLLMENT 	= $res_acc->fields['PK_STUDENT_ENROLLMENT'];
	$PK_ACCOUNT 					= $res_acc->fields['PK_ACCOUNT'];
	$PK_SESSION_MASTER 				= $res_acc->fields['PK_SESSION'];
	
	$res = $db->Execute("select PK_SESSION from M_SESSION WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND PK_SESSION_MASTER = '$PK_SESSION_MASTER' ");
	$PK_SESSION = $res->fields['PK_SESSION'];
	
	//echo "UPDATE S_STUDENT_ENROLLMENT SET PK_SESSION = '$PK_SESSION' WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' <br />";
	$db->Execute("UPDATE S_STUDENT_ENROLLMENT SET PK_SESSION = '$PK_SESSION' WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ");
	
	$res_acc->MoveNext();
}
*/
/*
$res_acc = $db->Execute("select PK_ACCOUNT from Z_ACCOUNT WHERE PK_ACCOUNT != 1 ");
while (!$res_acc->EOF) {
	$PK_ACCOUNT = $res_acc->fields['PK_ACCOUNT'];;
	
	$ACCOUNT_REPORTS['PK_ACCOUNT'] 	= $PK_ACCOUNT;
	$ACCOUNT_REPORTS['CREATED_BY']  = $_SESSION['ADMIN_PK_USER'];
	$ACCOUNT_REPORTS['CREATED_ON']  = date("Y-m-d H:i");
	db_perform('Z_ACCOUNT_REPORTS', $ACCOUNT_REPORTS, 'insert');

	
	$res_acc->MoveNext();
}*/
/*
$res_acc = $db->Execute("select PK_STUDENT_MASTER from S_STUDENT_MASTER ");
while (!$res_acc->EOF) {
	$PK_STUDENT_MASTER = $res_acc->fields['PK_STUDENT_MASTER'];;
	
	$res_acc1 = $db->Execute("select PK_STUDENT_ENROLLMENT from S_STUDENT_ENROLLMENT WHERE  PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' ");
	if($res_acc1->RecordCount() == 0){
		//echo $PK_STUDENT_MASTER.'<br />';
		echo "DELETE FROM S_STUDENT_MASTER WHERE PK_STUDENT_MASTER='$PK_STUDENT_MASTER'<br />";
	}
	
	$res_acc->MoveNext();
}*/
/*
$res_acc = $db->Execute("select PK_ACCOUNT from Z_ACCOUNT WHERE PK_ACCOUNT != 1 ");
while (!$res_acc->EOF) {
	
	$res_m = $db->Execute("select * from M_ECM_LEDGER_MASTER WHERE ACTIVE = '1' ");
	while (!$res_m->EOF) {
		$ECM_LEDGER_MASTER['PK_ECM_LEDGER_MASTER'] 	= $res_m->fields['PK_ECM_LEDGER_MASTER'];
		$ECM_LEDGER_MASTER['ECM_LEDGER'] 			= $res_m->fields['ECM_LEDGER'];
		$ECM_LEDGER_MASTER['DESCRIPTION'] 			= $res_m->fields['DESCRIPTION'];
		$ECM_LEDGER_MASTER['ACTIVE'] 				= 1;
		$ECM_LEDGER_MASTER['PK_ACCOUNT'] 			= $res_acc->fields['PK_ACCOUNT'];
		$ECM_LEDGER_MASTER['CREATED_ON'] 			= date("Y-m-d H:i:s");
		$ECM_LEDGER_MASTER['CREATED_BY'] 			= $_SESSION['ADMIN_PK_USER'];
		db_perform('M_ECM_LEDGER', $ECM_LEDGER_MASTER, 'insert');
		
		$res_m->MoveNext();
	}
	
	$res_acc->MoveNext();
}
*/
/*
$res_doc = $db->Execute("select PK_STUDENT_DOCUMENTS,PK_ACCOUNT from S_STUDENT_DOCUMENTS ");
while (!$res_doc->EOF) {
	$PK_STUDENT_DOCUMENTS 	= $res_doc->fields['PK_STUDENT_DOCUMENTS'];
	$PK_ACCOUNT 			= $res_doc->fields['PK_ACCOUNT'];
	
	$res_dep = $db->Execute("select PK_STUDENT_DOCUMENTS_DEPARTMENT from S_STUDENT_DOCUMENTS_DEPARTMENT WHERE  PK_STUDENT_DOCUMENTS = '$PK_STUDENT_DOCUMENTS' ");
	if($res_dep->RecordCount() == 0){
		$res_dep1 = $db->Execute("select PK_DEPARTMENT from M_DEPARTMENT WHERE  PK_ACCOUNT = '$PK_ACCOUNT' AND PK_DEPARTMENT_MASTER = 2 ");
		$PK_DEPARTMENT = $res_dep1->fields['PK_DEPARTMENT'];
		
		$STUDENT_DOCUMENTS_DEPARTMENT['PK_DEPARTMENT']   		= $PK_DEPARTMENT;
		$STUDENT_DOCUMENTS_DEPARTMENT['PK_STUDENT_DOCUMENTS'] 	= $PK_STUDENT_DOCUMENTS;
		$STUDENT_DOCUMENTS_DEPARTMENT['PK_ACCOUNT'] 			= $PK_ACCOUNT;
		$STUDENT_DOCUMENTS_DEPARTMENT['CREATED_ON']  			= date("Y-m-d H:i");
		db_perform('S_STUDENT_DOCUMENTS_DEPARTMENT', $STUDENT_DOCUMENTS_DEPARTMENT, 'insert');
	}
	
	$res_doc->MoveNext();
}
*/
/*
$res_campus = $db->Execute("select PK_STUDENT_CAMPUS,PK_STUDENT_MASTER,PK_ACCOUNT from S_STUDENT_CAMPUS ");
while (!$res_campus->EOF) {
	$PK_STUDENT_CAMPUS 		= $res_campus->fields['PK_STUDENT_CAMPUS'];
	$PK_STUDENT_MASTER 		= $res_campus->fields['PK_STUDENT_MASTER'];
	$PK_ACCOUNT 			= $res_campus->fields['PK_ACCOUNT'];

	$res_dep = $db->Execute("select PK_STUDENT_ENROLLMENT from S_STUDENT_ENROLLMENT WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND IS_ACTIVE_ENROLLMENT = 1");
	if($res_dep->RecordCount() == 0)
		$res_dep = $db->Execute("select PK_STUDENT_ENROLLMENT from S_STUDENT_ENROLLMENT WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' ");
		
	if($res_dep->RecordCount() > 0) {
		$PK_STUDENT_ENROLLMENT = $res_dep->fields['PK_STUDENT_ENROLLMENT'];
		
		$STUDENT_CAMPUS['PK_STUDENT_ENROLLMENT'] = $PK_STUDENT_ENROLLMENT;
		db_perform('S_STUDENT_CAMPUS', $STUDENT_CAMPUS, 'update'," PK_STUDENT_CAMPUS = '$PK_STUDENT_CAMPUS' ");
		
	}
	
	$res_campus->MoveNext();
}
*/
/*
$res_campus = $db->Execute("SELECT PK_STUDENT_LEDGER,S_STUDENT_LEDGER.PK_STUDENT_DISBURSEMENT, TRANSACTION_DATE,DISBURSEMENT_DATE FROM S_STUDENT_LEDGER,S_STUDENT_DISBURSEMENT WHERE S_STUDENT_LEDGER.PK_ACCOUNT = 30 AND S_STUDENT_LEDGER.PK_PAYMENT_BATCH_DETAIL > 0 AND S_STUDENT_LEDGER.PK_STUDENT_DISBURSEMENT = S_STUDENT_DISBURSEMENT.PK_STUDENT_DISBURSEMENT AND TRANSACTION_DATE != DISBURSEMENT_DATE ");
while (!$res_campus->EOF) {
	$PK_STUDENT_LEDGER 		= $res_campus->fields['PK_STUDENT_LEDGER'];
	$DISBURSEMENT_DATE 		= $res_campus->fields['DISBURSEMENT_DATE'];
	
	echo "UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$DISBURSEMENT_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'; <br/>";
	$db->Execute("UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$DISBURSEMENT_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'");
	//exit;
	
	$res_campus->MoveNext();
}
	*/
/*	
$res_campus = $db->Execute("SELECT PK_EMAIL_ACCOUNT,PASSWORD FROM `Z_EMAIL_ACCOUNT` ");
while (!$res_campus->EOF) {
	$PK_EMAIL_ACCOUNT 	= $res_campus->fields['PK_EMAIL_ACCOUNT'];
	$PASSWORD 			= $res_campus->fields['PASSWORD'];
	$PASSWORD 			= my_encrypt('',$PASSWORD);
	
	//echo "UPDATE Z_EMAIL_ACCOUNT SET PASSWORD = '$PASSWORD' WHERE PK_EMAIL_ACCOUNT = '$PK_EMAIL_ACCOUNT'; <br/>";
	$db->Execute("UPDATE Z_EMAIL_ACCOUNT SET PASSWORD = '$PASSWORD' WHERE PK_EMAIL_ACCOUNT = '$PK_EMAIL_ACCOUNT' ");
	//exit;
	
	$res_campus->MoveNext();
}*/
/*
$res_campus = $db->Execute("SELECT PK_STUDENT_LEDGER,S_STUDENT_LEDGER.PK_MISC_BATCH_DETAIL, S_STUDENT_LEDGER.TRANSACTION_DATE AS LEDGER_TRANSACTION_DATE ,S_MISC_BATCH_DETAIL.TRANSACTION_DATE AS MISC_TRANSACTION_DATE FROM S_STUDENT_LEDGER,S_MISC_BATCH_DETAIL WHERE S_STUDENT_LEDGER.PK_MISC_BATCH_DETAIL > 0 AND S_STUDENT_LEDGER.PK_MISC_BATCH_DETAIL = S_MISC_BATCH_DETAIL.PK_MISC_BATCH_DETAIL AND S_STUDENT_LEDGER.TRANSACTION_DATE != S_MISC_BATCH_DETAIL.TRANSACTION_DATE ");
while (!$res_campus->EOF) {
	$PK_STUDENT_LEDGER 			= $res_campus->fields['PK_STUDENT_LEDGER'];
	$LEDGER_TRANSACTION_DATE 	= $res_campus->fields['LEDGER_TRANSACTION_DATE'];
	$MISC_TRANSACTION_DATE 		= $res_campus->fields['MISC_TRANSACTION_DATE'];
	
	echo "UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$MISC_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'; <br/>";
	$db->Execute("UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$MISC_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'");
	//exit;
	
	$res_campus->MoveNext();
}
*/
/*
$res_campus = $db->Execute("SELECT PK_STUDENT_LEDGER,S_STUDENT_LEDGER.PK_TUITION_BATCH_DETAIL, S_STUDENT_LEDGER.TRANSACTION_DATE AS LEDGER_TRANSACTION_DATE ,S_TUITION_BATCH_DETAIL.TRANSACTION_DATE AS TUITION_TRANSACTION_DATE FROM S_STUDENT_LEDGER,S_TUITION_BATCH_DETAIL WHERE S_STUDENT_LEDGER.PK_TUITION_BATCH_DETAIL > 0 AND S_STUDENT_LEDGER.PK_TUITION_BATCH_DETAIL = S_TUITION_BATCH_DETAIL.PK_TUITION_BATCH_DETAIL AND S_STUDENT_LEDGER.TRANSACTION_DATE != S_TUITION_BATCH_DETAIL.TRANSACTION_DATE ");
while (!$res_campus->EOF) {
	$PK_STUDENT_LEDGER 			= $res_campus->fields['PK_STUDENT_LEDGER'];
	$LEDGER_TRANSACTION_DATE 	= $res_campus->fields['LEDGER_TRANSACTION_DATE'];
	$TUITION_TRANSACTION_DATE 	= $res_campus->fields['TUITION_TRANSACTION_DATE'];
	
	//echo "UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$TUITION_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'; <br/>";
	$db->Execute("UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$TUITION_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'");
	//exit;
	
	$res_campus->MoveNext();
}
*/
/*
$res_campus = $db->Execute("SELECT S_STUDENT_LEDGER.PK_ACCOUNT, PK_STUDENT_LEDGER,S_STUDENT_LEDGER.PK_STUDENT_FEE_BUDGET, S_STUDENT_LEDGER.TRANSACTION_DATE AS LEDGER_TRANSACTION_DATE , DATE_FORMAT(S_STUDENT_FEE_BUDGET.CREATED_ON,'%Y-%m-%d') AS TUITION_TRANSACTION_DATE FROM S_STUDENT_LEDGER,S_STUDENT_FEE_BUDGET WHERE S_STUDENT_LEDGER.PK_STUDENT_FEE_BUDGET > 0 AND S_STUDENT_LEDGER.PK_STUDENT_FEE_BUDGET = S_STUDENT_FEE_BUDGET.PK_STUDENT_FEE_BUDGET AND S_STUDENT_LEDGER.TRANSACTION_DATE != DATE_FORMAT(S_STUDENT_FEE_BUDGET.CREATED_ON,'%Y-%m-%d') ");
while (!$res_campus->EOF) {
	$PK_STUDENT_LEDGER 			= $res_campus->fields['PK_STUDENT_LEDGER'];
	$LEDGER_TRANSACTION_DATE 	= $res_campus->fields['LEDGER_TRANSACTION_DATE'];
	$TUITION_TRANSACTION_DATE 	= $res_campus->fields['TUITION_TRANSACTION_DATE'];
	
	echo "UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$TUITION_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'; <br/>";
	$db->Execute("UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$TUITION_TRANSACTION_DATE' WHERE PK_STUDENT_LEDGER = '$PK_STUDENT_LEDGER'");
	//exit;
	
	$res_campus->MoveNext();
}*/


/*	
$res_m = $db->Execute("select PK_EVENT_TEMPLATE, PK_ACCOUNT from S_EVENT_TEMPLATE WHERE PK_ACCOUNT > 0 ");
while (!$res_m->EOF) {
	$PK_EVENT_TEMPLATE 	= $res_m->fields['PK_EVENT_TEMPLATE'];
	$PK_ACCOUNT 		= $res_m->fields['PK_ACCOUNT'];
	
	$res_campus = $db->Execute("select PK_CAMPUS from S_CAMPUS WHERE PK_ACCOUNT = '$PK_ACCOUNT' ");
	while (!$res_campus->EOF) {
		$EVENT_TEMPLATE_CAMPUS['PK_ACCOUNT'] 			= $PK_ACCOUNT;
		$EVENT_TEMPLATE_CAMPUS['PK_EVENT_TEMPLATE'] 	= $PK_EVENT_TEMPLATE;
		$EVENT_TEMPLATE_CAMPUS['PK_CAMPUS'] 			= $res_campus->fields['PK_CAMPUS'];
		$EVENT_TEMPLATE_CAMPUS['CREATED_ON'] 			= date("Y-m-d H:i:s");
		db_perform('S_EVENT_TEMPLATE_CAMPUS', $EVENT_TEMPLATE_CAMPUS, 'insert');
	
		$res_campus->MoveNext();
	}

	$res_m->MoveNext();
}
*/
/*
$res_m = $db->Execute("select * from M_CAMPUS_PROGRAM ");
while (!$res_m->EOF) {
	$CAMPUS_PROGRAM_REPORT_HEADER['PK_CAMPUS_PROGRAM'] 	= $res_m->fields['PK_CAMPUS_PROGRAM'];
	$CAMPUS_PROGRAM_REPORT_HEADER['PK_ACCOUNT'] 		= $res_m->fields['PK_ACCOUNT'];
	
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_1'] 			= 'PROGRAM_CODE';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_2'] 			= 'STUDENT_STATUS';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_3'] 			= 'BEGIN_DATE';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_4'] 			= '';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_5'] 			= 'EXPECTED_GRAD_DATE';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_6'] 			= 'LDA';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_7'] 			= '';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_8'] 			= 'FULL_PART_TIME';
	$CAMPUS_PROGRAM_REPORT_HEADER['BOX_9'] 			= 'SESSION_ABBREVIATION';
	$CAMPUS_PROGRAM_REPORT_HEADER['ACTIVE'] 		= 1;
	$CAMPUS_PROGRAM_REPORT_HEADER['CREATED_ON'] 	= date("Y-m-d H:i:s");
	$CAMPUS_PROGRAM_REPORT_HEADER['CREATED_BY'] 	= $_SESSION['ADMIN_PK_USER'];
	db_perform('M_CAMPUS_PROGRAM_REPORT_HEADER', $CAMPUS_PROGRAM_REPORT_HEADER, 'insert');
	
	$res_m->MoveNext();
}*/
/*
$res_m = $db->Execute("SELECT PK_STUDENT_MASTER, PK_STUDENT_CUSTOM_FIELDS FROM `S_STUDENT_CUSTOM_FIELDS` where PK_CUSTOM_FIELDS IN (19,61,62,63,73,74,77,111,113,158,159)");
while (!$res_m->EOF) {
	$PK_STUDENT_MASTER 			= $res_m->fields['PK_STUDENT_MASTER'];
	$PK_STUDENT_CUSTOM_FIELDS 	= $res_m->fields['PK_STUDENT_CUSTOM_FIELDS'];

	$res_en = $db->Execute("select PK_STUDENT_ENROLLMENT from S_STUDENT_ENROLLMENT WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND IS_ACTIVE_ENROLLMENT = 1 ");
	$PK_STUDENT_ENROLLMENT = $res_en->fields['PK_STUDENT_ENROLLMENT'];
	
	echo "UPDATE S_STUDENT_CUSTOM_FIELDS SET PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' WHERE PK_STUDENT_CUSTOM_FIELDS = '$PK_STUDENT_CUSTOM_FIELDS'; <br />";

	$res_m->MoveNext();
}
*/
/*
$res_cal = $db->Execute("SELECT * FROM `M_ACADEMIC_CALENDAR` ");
while (!$res_cal->EOF) {
	
	$PK_ACCOUNT 			= $res_cal->fields['PK_ACCOUNT'];
	$PK_ACADEMIC_CALENDAR 	= $res_cal->fields['PK_ACADEMIC_CALENDAR'];
	
	$res_campus = $db->Execute("select PK_CAMPUS from S_CAMPUS WHERE ACTIVE = 1 AND PK_ACCOUNT = '$PK_ACCOUNT' ORDER BY OFFICIAL_CAMPUS_NAME ASC ");
	while (!$res_campus->EOF) {
		$PK_CAMPUS 	= $res_campus->fields['PK_CAMPUS'];
		
		$res = $db->Execute("SELECT PK_ACADEMIC_CALENDAR_CAMPUS FROM M_ACADEMIC_CALENDAR_CAMPUS WHERE PK_ACADEMIC_CALENDAR = '$PK_ACADEMIC_CALENDAR' AND PK_ACCOUNT = '$PK_ACCOUNT' AND PK_CAMPUS = '$PK_CAMPUS' "); 
		if($res->RecordCount() == 0) {
			$ACADEMIC_CALENDAR_CAMPUS['PK_CAMPUS'] 				= $PK_CAMPUS;
			$ACADEMIC_CALENDAR_CAMPUS['PK_ACADEMIC_CALENDAR']  	= $PK_ACADEMIC_CALENDAR;
			$ACADEMIC_CALENDAR_CAMPUS['PK_ACCOUNT']  			= $PK_ACCOUNT;
			$ACADEMIC_CALENDAR_CAMPUS['CREATED_ON']  			= date("Y-m-d H:i");
			db_perform('M_ACADEMIC_CALENDAR_CAMPUS', $ACADEMIC_CALENDAR_CAMPUS, 'insert');
			
			//echo "<pre>";print_r($ACADEMIC_CALENDAR_CAMPUS);
		}
		
		$res_campus->MoveNext();
	}
	
	$res_cal->MoveNext();
}
*/
echo "Done 200";
