<? require_once("../../global/config.php"); 

$DATA = (file_get_contents('php://input'));

$API_KEY = '';
foreach (getallheaders() as $name => $value) {
    //echo "$name: $value<br />";
	if(strtolower(trim($name)) == 'apikey')
		$API_KEY = trim($value);
}

$flag = 1;
if($API_KEY == ''){
	$data['SUCCESS'] = 0;
	$data['MESSAGE'] = 'API Key Missing';
	
	$flag = 0;
} else {
	$res = $db->Execute("SELECT PK_ACCOUNT,ACTIVE FROM Z_ACCOUNT where API_KEY = '$API_KEY'");
	if($res->RecordCount() == 0){
		$data['SUCCESS'] = 0;
		$data['MESSAGE'] = 'Invalid API Key';
		
		$flag = 0;
	} else if($res->fields['ACTIVE'] == 0){
		$data['SUCCESS'] = 0;
		$data['MESSAGE'] = 'Your Account Is Blocked.';
		
		$flag = 0;
	}
	
	$PK_ACCOUNT = $res->fields['PK_ACCOUNT'];
}

if($flag == 1){
	$data['SUCCESS'] = 1;
	$data['MESSAGE'] = '';
	
	$res_type = $db->Execute("select PK_STUDENT_STATUS from M_STUDENT_STATUS WHERE PK_ACCOUNT = '$PK_ACCOUNT' ");
	while (!$res_type->EOF) {
		if($sts != '')
			$sts .= ',';
			
		$sts .= $res_type->fields['PK_STUDENT_STATUS'];
		
		$res_type->MoveNext();
	}

	$res = $db->Execute("SELECT S_STUDENT_MASTER.PK_STUDENT_MASTER, FIRST_NAME, LAST_NAME, MIDDLE_NAME, OTHER_NAME, SSN, DATE_OF_BIRTH, GENDER as GENDER_ID, IF(GENDER = 1, 'Male', IF(GENDER = 2, 'Female', '')) AS GENDER , DRIVERS_LICENSE, PK_DRIVERS_LICENSE_STATE, Z_STATES.STATE_NAME AS DRIVERS_LICENSE_STATE , S_STUDENT_MASTER.PK_MARITAL_STATUS, MARITAL_STATUS, S_STUDENT_MASTER.PK_COUNTRY_CITIZEN, Z_COUNTRY.NAME as COUNTRY_CITIZEN, S_STUDENT_MASTER.PK_CITIZENSHIP, CITIZENSHIP, IPEDS_ETHNICITY, PLACE_OF_BIRTH,  Z_STATES_1.STATE_NAME AS STATE_OF_RESIDENCY, PK_STATE_OF_RESIDENCY, IF(SSN_VERIFIED = 1,'Yes','No') as SSN_VERIFIED, BADGE_ID, OLD_DSIS_STU_NO, OLD_DSIS_LEAD_ID, STUDENT_ID, ADM_USER_ID, S_STUDENT_ACADEMICS.PK_HIGHEST_LEVEL_OF_EDU, HIGHEST_LEVEL_OF_EDU, IF(PREVIOUS_COLLEGE = 1 ,'Yes',IF(PREVIOUS_COLLEGE = 2 ,'No','')) AS PREVIOUS_COLLEGE , IF(FERPA_BLOCK = 1 ,'Yes',IF(FERPA_BLOCK = 2 ,'No','')) AS FERPA_BLOCK, ENTRY_DATE, ENTRY_TIME, CONCAT(M_LEAD_CONTACT_SOURCE.LEAD_CONTACT_SOURCE,' - ',M_LEAD_CONTACT_SOURCE.DESCRIPTION)   AS CONTACT_SOURCE, S_STUDENT_ACADEMICS.PK_LEAD_CONTACT_SOURCE FROM 
	S_STUDENT_MASTER 
	LEFT JOIN S_STUDENT_ACADEMICS ON S_STUDENT_ACADEMICS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER 
	LEFT JOIN M_HIGHEST_LEVEL_OF_EDU ON M_HIGHEST_LEVEL_OF_EDU.PK_HIGHEST_LEVEL_OF_EDU = S_STUDENT_ACADEMICS.PK_HIGHEST_LEVEL_OF_EDU 
	LEFT JOIN M_LEAD_CONTACT_SOURCE ON M_LEAD_CONTACT_SOURCE.PK_LEAD_CONTACT_SOURCE = S_STUDENT_ACADEMICS.PK_LEAD_CONTACT_SOURCE 
	
	LEFT JOIN Z_CITIZENSHIP ON Z_CITIZENSHIP.PK_CITIZENSHIP = S_STUDENT_MASTER.PK_CITIZENSHIP 
	LEFT JOIN Z_COUNTRY ON Z_COUNTRY.PK_COUNTRY = PK_COUNTRY_CITIZEN  
	LEFT JOIN Z_STATES ON Z_STATES.PK_STATES = PK_DRIVERS_LICENSE_STATE 
	LEFT JOIN Z_STATES AS Z_STATES_1 ON Z_STATES_1.PK_STATES = PK_STATE_OF_RESIDENCY 
	LEFT JOIN Z_MARITAL_STATUS ON Z_MARITAL_STATUS.PK_MARITAL_STATUS = S_STUDENT_MASTER.PK_MARITAL_STATUS 
	, S_STUDENT_ENROLLMENT 
	WHERE S_STUDENT_MASTER.PK_ACCOUNT = '$PK_ACCOUNT' AND ARCHIVED = 0 AND S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER AND IS_ACTIVE_ENROLLMENT = 1 AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS IN ($sts) ");
	
	$i = 0;
	while (!$res->EOF) { 
		$PK_STUDENT_MASTER = $res->fields['PK_STUDENT_MASTER'];
		$ENTRY_DATE = $res->fields['ENTRY_DATE'];
		$ENTRY_TIME = $res->fields['ENTRY_TIME'];
		
		$data['LEAD'][$i]['ID'] 						= $PK_STUDENT_MASTER;
		$data['LEAD'][$i]['FIRST_NAME'] 				= $res->fields['FIRST_NAME'];
		$data['LEAD'][$i]['LAST_NAME'] 					= $res->fields['LAST_NAME'];
		$data['LEAD'][$i]['MIDDLE_NAME'] 				= $res->fields['MIDDLE_NAME'];
		$data['LEAD'][$i]['OTHER_NAME'] 				= $res->fields['OTHER_NAME'];
		$data['LEAD'][$i]['SSN'] 						= $res->fields['SSN'];
		$data['LEAD'][$i]['SSN_VERIFIED'] 				= $res->fields['SSN_VERIFIED'];
		$data['LEAD'][$i]['DATE_OF_BIRTH'] 				= $res->fields['DATE_OF_BIRTH'];
		$data['LEAD'][$i]['DRIVERS_LICENSE'] 			= $res->fields['DRIVERS_LICENSE'];
		$data['LEAD'][$i]['DRIVERS_LICENSE_STATE'] 		= $res->fields['DRIVERS_LICENSE_STATE'];
		$data['LEAD'][$i]['DRIVERS_LICENSE_STATE_ID'] 	= $res->fields['PK_DRIVERS_LICENSE_STATE'];
		$data['LEAD'][$i]['MARITAL_STATUS'] 			= $res->fields['MARITAL_STATUS'];
		$data['LEAD'][$i]['MARITAL_STATUS_ID'] 			= $res->fields['PK_MARITAL_STATUS'];
		$data['LEAD'][$i]['GENDER'] 					= $res->fields['GENDER'];
		$data['LEAD'][$i]['GENDER_ID'] 					= $res->fields['GENDER_ID'];
		$data['LEAD'][$i]['COUNTRY_CITIZEN'] 			= $res->fields['COUNTRY_CITIZEN'];
		$data['LEAD'][$i]['COUNTRY_CITIZEN_ID'] 		= $res->fields['PK_COUNTRY_CITIZEN'];
		$data['LEAD'][$i]['CITIZENSHIP'] 				= $res->fields['CITIZENSHIP'];
		$data['LEAD'][$i]['CITIZENSHIP_ID'] 			= $res->fields['PK_CITIZENSHIP'];
		$data['LEAD'][$i]['PLACE_OF_BIRTH'] 			= $res->fields['PLACE_OF_BIRTH'];
		$data['LEAD'][$i]['STATE_OF_RESIDENCY'] 		= $res->fields['STATE_OF_RESIDENCY'];
		$data['LEAD'][$i]['STATE_OF_RESIDENCY_ID'] 		= $res->fields['PK_STATE_OF_RESIDENCY'];
		$data['LEAD'][$i]['OLD_DSIS_STU_NO'] 			= $res->fields['OLD_DSIS_STU_NO'];
		$data['LEAD'][$i]['OLD_DSIS_LEAD_ID'] 			= $res->fields['OLD_DSIS_LEAD_ID'];
		$data['LEAD'][$i]['STUDENT_ID'] 				= $res->fields['STUDENT_ID'];
		$data['LEAD'][$i]['ADM_USER_ID'] 				= $res->fields['ADM_USER_ID'];
		$data['LEAD'][$i]['HIGHEST_LEVEL_OF_EDU'] 		= $res->fields['HIGHEST_LEVEL_OF_EDU']; 
		$data['LEAD'][$i]['HIGHEST_LEVEL_OF_EDU_ID'] 	= $res->fields['PK_HIGHEST_LEVEL_OF_EDU'];
		$data['LEAD'][$i]['PREVIOUS_COLLEGE'] 			= $res->fields['PREVIOUS_COLLEGE'];
		$data['LEAD'][$i]['BADGE_ID'] 					= $res->fields['BADGE_ID'];
		$data['LEAD'][$i]['FERPA_BLOCK'] 				= $res->fields['FERPA_BLOCK'];
		$data['LEAD'][$i]['IPEDS_ETHNICITY'] 			= $res->fields['IPEDS_ETHNICITY'];
		
		$j = 0;
		$res_det = $db->Execute("select RACE, Z_RACE.PK_RACE FROM Z_RACE,S_STUDENT_RACE WHERE Z_RACE.PK_RACE = S_STUDENT_RACE.PK_RACE AND PK_STUDENT_MASTER='$PK_STUDENT_MASTER'"); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['RACE'][$j]['NAME']		= $res_det->fields['RACE'];
			$data['LEAD'][$i]['RACE'][$j]['RACE_ID']	= $res_det->fields['PK_RACE'];
			
			$j++;
			$res_det->MoveNext();
		}

		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_CONTACT,HOME_PHONE, S_STUDENT_CONTACT.PK_STUDENT_CONTACT_TYPE_MASTER, STUDENT_CONTACT_TYPE, STUDENT_RELATIONSHIP, ADDRESS, ADDRESS_1, CITY, STATE_NAME, ZIP, WORK_PHONE, CELL_PHONE, EMAIL, CONTACT_NAME, STUDENT_RELATIONSHIP, S_STUDENT_CONTACT.PK_STUDENT_CONTACT_TYPE_MASTER, CONTACT_TITLE, S_STUDENT_CONTACT.PK_STUDENT_RELATIONSHIP_MASTER, COMPANY_NAME, S_STUDENT_CONTACT.PK_STATES, Z_COUNTRY.NAME as COUNTRY, S_STUDENT_CONTACT.PK_COUNTRY, IF(ADDRESS_INVALID = 1, 'Yes','No') as ADDRESS_INVALID, IF(HOME_PHONE_INVALID = 1, 'Yes','No') as HOME_PHONE_INVALID , IF(WORK_PHONE_INVALID = 1, 'Yes','No') as WORK_PHONE_INVALID, IF(CELL_PHONE_INVALID = 1, 'Yes','No') as CELL_PHONE_INVALID, OTHER_PHONE, IF(OTHER_PHONE_INVALID = 1, 'Yes','No') as OTHER_PHONE_INVALID, FAX, EMAIL,  IF(EMAIL_INVALID = 1, 'Yes','No') as  EMAIL_INVALID, EMAIL_OTHER, IF(EMAIL_OTHER_INVALID = 1, 'Yes','No') as  EMAIL_OTHER_INVALID , IF(OPT_OUT = 1, 'Yes','No') as  OPT_OUT , IF(USE_EMAIL = 1, 'Yes','No') as  USE_EMAIL, WEBSITE, IF(S_STUDENT_CONTACT.ACTIVE = 1, 'Yes','No') AS ACTIVE
		FROM 
		S_STUDENT_CONTACT 
		LEFT JOIN M_STUDENT_CONTACT_TYPE_MASTER ON M_STUDENT_CONTACT_TYPE_MASTER.PK_STUDENT_CONTACT_TYPE_MASTER = S_STUDENT_CONTACT.PK_STUDENT_CONTACT_TYPE_MASTER 
		LEFT JOIN M_STUDENT_RELATIONSHIP_MASTER ON M_STUDENT_RELATIONSHIP_MASTER.PK_STUDENT_RELATIONSHIP_MASTER = S_STUDENT_CONTACT.PK_STUDENT_RELATIONSHIP_MASTER 
		LEFT JOIN Z_STATES ON Z_STATES.PK_STATES = S_STUDENT_CONTACT.PK_STATES 
		LEFT JOIN Z_COUNTRY ON Z_COUNTRY.PK_COUNTRY = S_STUDENT_CONTACT.PK_COUNTRY 
		WHERE 
		PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['CONTACTS'][$j]['CONTACT_TYPE']			= $res_det->fields['STUDENT_CONTACT_TYPE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CONTACT_TYPE_ID']		= $res_det->fields['PK_STUDENT_CONTACT_TYPE_MASTER'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CONTACT_NAME']			= $res_det->fields['CONTACT_NAME'];
			$data['LEAD'][$i]['CONTACTS'][$j]['RELATIONSHIP']			= $res_det->fields['STUDENT_RELATIONSHIP'];
			$data['LEAD'][$i]['CONTACTS'][$j]['RELATIONSHIP_ID']		= $res_det->fields['PK_STUDENT_RELATIONSHIP_MASTER'];
			$data['LEAD'][$i]['CONTACTS'][$j]['COMPANY_NAME']			= $res_det->fields['COMPANY_NAME'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CONTACT_TITLE']			= $res_det->fields['CONTACT_TITLE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['ADDRESS']				= $res_det->fields['ADDRESS'];
			$data['LEAD'][$i]['CONTACTS'][$j]['ADDRESS_1']				= $res_det->fields['ADDRESS_1'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CITY']					= $res_det->fields['CITY'];
			$data['LEAD'][$i]['CONTACTS'][$j]['STATE']					= $res_det->fields['STATE_NAME'];
			$data['LEAD'][$i]['CONTACTS'][$j]['STATE_ID']				= $res_det->fields['PK_STATES'];
			$data['LEAD'][$i]['CONTACTS'][$j]['COUNTRY']				= $res_det->fields['COUNTRY'];
			$data['LEAD'][$i]['CONTACTS'][$j]['COUNTRY_ID']				= $res_det->fields['PK_COUNTRY'];
			$data['LEAD'][$i]['CONTACTS'][$j]['IS_ADDRESS_INVALID']		= $res_det->fields['ADDRESS_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['HOME_PHONE']				= $res_det->fields['HOME_PHONE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['HOME_PHONE_INVALID']		= $res_det->fields['HOME_PHONE_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['WORK_PHONE']				= $res_det->fields['WORK_PHONE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['WORK_PHONE_INVALID']		= $res_det->fields['WORK_PHONE_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CELL_PHONE']				= $res_det->fields['CELL_PHONE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['CELL_PHONE_INVALID']		= $res_det->fields['CELL_PHONE_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['OTHER_PHONE']			= $res_det->fields['OTHER_PHONE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['OTHER_PHONE_INVALID']	= $res_det->fields['OTHER_PHONE_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['FAX']					= $res_det->fields['FAX'];
			$data['LEAD'][$i]['CONTACTS'][$j]['EMAIL']					= $res_det->fields['EMAIL'];
			$data['LEAD'][$i]['CONTACTS'][$j]['EMAIL_INVALID']			= $res_det->fields['EMAIL_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['EMAIL_OTHER']			= $res_det->fields['EMAIL_OTHER'];
			$data['LEAD'][$i]['CONTACTS'][$j]['EMAIL_OTHER_INVALID']	= $res_det->fields['EMAIL_OTHER_INVALID'];
			$data['LEAD'][$i]['CONTACTS'][$j]['OPT_OUT']				= $res_det->fields['OPT_OUT'];
			$data['LEAD'][$i]['CONTACTS'][$j]['USE_EMAIL']				= $res_det->fields['USE_EMAIL'];
			$data['LEAD'][$i]['CONTACTS'][$j]['WEBSITE']				= $res_det->fields['WEBSITE'];
			$data['LEAD'][$i]['CONTACTS'][$j]['USE_EMAIL']				= $res_det->fields['USE_EMAIL'];
			$data['LEAD'][$i]['CONTACTS'][$j]['ACTIVE']					= $res_det->fields['ACTIVE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_ENROLLMENT, IF(IS_ACTIVE_ENROLLMENT = 1,'Yes', 'No') as IS_ACTIVE_ENROLLMENT, S_STUDENT_ENROLLMENT.PK_TERM_MASTER, IF(S_TERM_MASTER.BEGIN_DATE = '0000-00-00','',DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE, '%m/%d/%Y' )) AS  BEGIN_DATE_1, CONCAT(M_CAMPUS_PROGRAM.CODE,' - ',M_CAMPUS_PROGRAM.DESCRIPTION) AS PROGRAM, S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM, CONCAT(M_STUDENT_STATUS.STUDENT_STATUS,' - ',M_STUDENT_STATUS.DESCRIPTION) AS STATUS, S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS, STATUS_DATE, CONCAT(FIRST_NAME,' ',LAST_NAME) AS ADMISSION_REP, S_STUDENT_ENROLLMENT.PK_REPRESENTATIVE, CONCAT(M_LEAD_SOURCE.LEAD_SOURCE,' - ',M_LEAD_SOURCE.DESCRIPTION) AS LEAD_SOURCE, S_STUDENT_ENROLLMENT.PK_LEAD_SOURCE, CONTRACT_SIGNED_DATE, CONTRACT_END_DATE, EXPECTED_GRAD_DATE, CONCAT(M_ENROLLMENT_STATUS.CODE,' - ',M_ENROLLMENT_STATUS.DESCRIPTION) AS ENROLLMENT_STATUS, S_STUDENT_ENROLLMENT.PK_ENROLLMENT_STATUS, SESSION, S_STUDENT_ENROLLMENT.PK_SESSION, CONCAT(M_FUNDING.FUNDING,' - ',M_FUNDING.DESCRIPTION) AS FUNDING, M_FUNDING.PK_FUNDING, STUDENT_GROUP, S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP, IF(S_TERM_BLOCK.BEGIN_DATE = '0000-00-00','',DATE_FORMAT(S_TERM_BLOCK.BEGIN_DATE, '%m/%d/%Y' )) AS TERM_BLOCK, S_STUDENT_ENROLLMENT.ENROLLMENT_PK_TERM_BLOCK, LDA , DETERMINATION_DATE, DROP_DATE, MIDPOINT_DATE 
		FROM 
		S_STUDENT_ENROLLMENT 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
		LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_STUDENT_ENROLLMENT.PK_REPRESENTATIVE 
		LEFT JOIN M_FUNDING ON M_FUNDING.PK_FUNDING = S_STUDENT_ENROLLMENT.PK_FUNDING 
		LEFT JOIN M_STUDENT_GROUP ON M_STUDENT_GROUP.PK_STUDENT_GROUP = S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP 
		LEFT JOIN M_LEAD_SOURCE ON M_LEAD_SOURCE.PK_LEAD_SOURCE = S_STUDENT_ENROLLMENT.PK_LEAD_SOURCE 
		LEFT JOIN M_ENROLLMENT_STATUS ON M_ENROLLMENT_STATUS.PK_ENROLLMENT_STATUS = S_STUDENT_ENROLLMENT.PK_ENROLLMENT_STATUS 
		LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_STUDENT_ENROLLMENT.PK_SESSION 
		LEFT JOIN S_TERM_BLOCK ON S_TERM_BLOCK.PK_TERM_BLOCK = S_STUDENT_ENROLLMENT.ENROLLMENT_PK_TERM_BLOCK
		WHERE PK_STUDENT_MASTER='$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['ENROLLMENT'][$j]['ID']					= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['FIRST_TERM_DATE']		= $res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['FIRST_TERM_DATE_ID']	= $res_det->fields['PK_TERM_MASTER'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['PROGRAM']				= $res_det->fields['PROGRAM'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['PROGRAM_ID']			= $res_det->fields['PK_CAMPUS_PROGRAM'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['STATUS']				= $res_det->fields['STATUS'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['STATUS_ID']			= $res_det->fields['PK_STUDENT_STATUS'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['STATUS_DATE']			= $res_det->fields['STATUS_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['ADMISSION_REP']		= $res_det->fields['ADMISSION_REP'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['ADMISSION_REP_ID']		= $res_det->fields['PK_REPRESENTATIVE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['LEAD_SOURCE']			= $res_det->fields['LEAD_SOURCE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['LEAD_SOURCE_ID']		= $res_det->fields['PK_LEAD_SOURCE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['CONTACT_SOURCE']		= $CONTACT_SOURCE;
			$data['LEAD'][$i]['ENROLLMENT'][$j]['CONTACT_SOURCE_ID']	= $PK_LEAD_CONTACT_SOURCE;
			$data['LEAD'][$i]['ENROLLMENT'][$j]['CONTRACT_SIGNED_DATE']	= $res_det->fields['CONTRACT_SIGNED_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['CONTRACT_END_DATE']	= $res_det->fields['CONTRACT_END_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['ENTRY_DATE']			= $ENTRY_DATE;
			$data['LEAD'][$i]['ENROLLMENT'][$j]['ENTRY_TIME']			= $ENTRY_TIME;
			$data['LEAD'][$i]['ENROLLMENT'][$j]['EXPECTED_GRAD_DATE']	= $res_det->fields['EXPECTED_GRAD_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['PART_FULL_TIME']		= $res_det->fields['ENROLLMENT_STATUS'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['PART_FULL_TIME_ID']	= $res_det->fields['PK_ENROLLMENT_STATUS'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['SESSION_ID']			= $res_det->fields['PK_SESSION'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['SESSION']				= $res_det->fields['SESSION'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['FUNDING']				= $res_det->fields['FUNDING'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['FUNDING_ID']			= $res_det->fields['PK_FUNDING'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['STUDENT_GROUP']		= $res_det->fields['STUDENT_GROUP'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['STUDENT_GROUP_ID']		= $res_det->fields['PK_STUDENT_GROUP'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['TERM_BLOCK']			= $res_det->fields['TERM_BLOCK'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['TERM_BLOCK_ID']		= $res_det->fields['ENROLLMENT_PK_TERM_BLOCK'];
			
			$data['LEAD'][$i]['ENROLLMENT'][$j]['LDA']					= $res_det->fields['LDA'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['DETERMINATION_DATE']	= $res_det->fields['DETERMINATION_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['DROP_DATE']			= $res_det->fields['DROP_DATE'];
			$data['LEAD'][$i]['ENROLLMENT'][$j]['MIDPOINT_DATE']		= $res_det->fields['MIDPOINT_DATE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_CAMPUS,OFFICIAL_CAMPUS_NAME,S_CAMPUS.PK_CAMPUS, S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT, CODE,IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1 FROM 
		S_STUDENT_CAMPUS
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER  
		, S_CAMPUS 
		WHERE S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS AND S_STUDENT_CAMPUS.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND S_STUDENT_CAMPUS.PK_ACCOUNT = '$PK_ACCOUNT'"); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['CAMPUS'][$j]['ENROLLMENT']		= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['CAMPUS'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			
			$data['LEAD'][$i]['CAMPUS'][$j]['NAME']			= $res_det->fields['OFFICIAL_CAMPUS_NAME'];
			$data['LEAD'][$i]['CAMPUS'][$j]['CAMPUS_ID']	= $res_det->fields['PK_CAMPUS'];
			//$data['EMPLOYEE'][$i]['CAMPUS'][$j]['STUDENT_CAMPUS_ID']	= $res_det->fields['PK_STUDENT_CAMPUS'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_TASK,TASK_TIME, CODE,IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, S_STUDENT_TASK.PK_TASK_TYPE, TASK_TYPE, S_STUDENT_TASK.PK_TASK_STATUS, TASK_STATUS, EVENT_OTHER, S_STUDENT_TASK.PK_EVENT_OTHER ,S_STUDENT_TASK.NOTES , TASK_DATE, FOLLOWUP_DATE, FOLLOWUP_TIME, IF(COMPLETED = 1,'Yes','No') as COMPLETED, CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, NOTES_PRIORITY, S_STUDENT_TASK.PK_NOTES_PRIORITY_MASTER , NOTES_PRIORITY, S_STUDENT_TASK.PK_STUDENT_ENROLLMENT 
		FROM 
		S_STUDENT_TASK 
		LEFT JOIN M_EVENT_OTHER ON M_EVENT_OTHER.PK_EVENT_OTHER = S_STUDENT_TASK.PK_EVENT_OTHER 
		LEFT JOIN M_NOTES_PRIORITY_MASTER ON M_NOTES_PRIORITY_MASTER.PK_NOTES_PRIORITY_MASTER = S_STUDENT_TASK.PK_NOTES_PRIORITY_MASTER 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_TASK.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
		LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_STUDENT_TASK.PK_EMPLOYEE_MASTER JOIN M_TASK_TYPE ON M_TASK_TYPE.PK_TASK_TYPE = S_STUDENT_TASK.PK_TASK_TYPE 
		LEFT JOIN M_TASK_STATUS ON M_TASK_STATUS.PK_TASK_STATUS = S_STUDENT_TASK.PK_TASK_STATUS WHERE S_STUDENT_TASK.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND S_STUDENT_TASK.PK_ACCOUNT = '$PK_ACCOUNT' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['TASK'][$j]['ENROLLMENT']		= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['TASK'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			
			$data['LEAD'][$i]['TASK'][$j]['TASK_TYPE']		= $res_det->fields['TASK_TYPE'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_TYPE_ID']	= $res_det->fields['PK_TASK_TYPE'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_STATUS']	= $res_det->fields['TASK_STATUS'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_STATUS_ID']	= $res_det->fields['PK_TASK_STATUS'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_OTHER']		= $res_det->fields['EVENT_OTHER'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_OTHER_ID']	= $res_det->fields['PK_EVENT_OTHER'];
			$data['LEAD'][$i]['TASK'][$j]['PRIORITY']		= $res_det->fields['PRIORITY'];
			$data['LEAD'][$i]['TASK'][$j]['PRIORITY_ID']	= $res_det->fields['PK_NOTES_PRIORITY_MASTER'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_TIME']		= $res_det->fields['TASK_TIME'];
			$data['LEAD'][$i]['TASK'][$j]['TASK_DATE']		= $res_det->fields['TASK_DATE'];
			$data['LEAD'][$i]['TASK'][$j]['FOLLOWUP_DATE']	= $res_det->fields['FOLLOWUP_DATE'];
			$data['LEAD'][$i]['TASK'][$j]['FOLLOWUP_TIME']	= $res_det->fields['FOLLOWUP_TIME'];
			$data['LEAD'][$i]['TASK'][$j]['EMPLOYEE']		= $res_det->fields['NAME'];
			$data['LEAD'][$i]['TASK'][$j]['COMPLETED']		= $res_det->fields['COMPLETED'];
			$data['LEAD'][$i]['TASK'][$j]['COMMENTS']		= $res_det->fields['NOTES'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_NOTES, NOTE_STATUS, CODE,IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, NOTE_DATE, NOTE_TIME, S_STUDENT_NOTES.NOTES, NOTE_TYPE, CONCAT(EMP.FIRST_NAME,' ',EMP.LAST_NAME) AS EMP_NAME, IF(IS_EVENT = 1,'Yes', 'No') AS IS_EVENT, NOTES_PRIORITY, FOLLOWUP_DATE, SATISFIED, CONCAT(CREATED_EMP.FIRST_NAME,' ',CREATED_EMP.LAST_NAME) AS CREATED_BY,PK_NOTE_TYPE_MASTER, if(S_STUDENT_NOTES.PK_DEPARTMENT = -1, 'All Departments', DEPARTMENT) AS DEPARTMENT, S_STUDENT_NOTES.PK_STUDENT_ENROLLMENT, S_STUDENT_NOTES.PK_DEPARTMENT, S_STUDENT_NOTES.PK_NOTE_STATUS, M_NOTE_TYPE.PK_NOTE_TYPE, FOLLOWUP_DATE, FOLLOWUP_TIME , IF(SATISFIED = 1,'Yes','No') as COMPLETED    
		FROM 
		S_STUDENT_NOTES 
		LEFT JOIN M_DEPARTMENT ON M_DEPARTMENT.PK_DEPARTMENT = S_STUDENT_NOTES.PK_DEPARTMENT 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_NOTES.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
		LEFT JOIN S_EMPLOYEE_MASTER AS EMP ON EMP.PK_EMPLOYEE_MASTER = S_STUDENT_NOTES.PK_EMPLOYEE_MASTER 
		LEFT JOIN M_NOTES_PRIORITY_MASTER ON M_NOTES_PRIORITY_MASTER.PK_NOTES_PRIORITY_MASTER = S_STUDENT_NOTES.PK_NOTES_PRIORITY_MASTER 
		LEFT JOIN M_NOTE_STATUS ON M_NOTE_STATUS.PK_NOTE_STATUS = S_STUDENT_NOTES.PK_NOTE_STATUS 
		LEFT JOIN M_NOTE_TYPE ON S_STUDENT_NOTES.PK_NOTE_TYPE = M_NOTE_TYPE.PK_NOTE_TYPE
		, S_EMPLOYEE_MASTER AS CREATED_EMP, Z_USER  WHERE S_STUDENT_NOTES.PK_ACCOUNT = '$PK_ACCOUNT' AND IS_EVENT = 0 AND S_STUDENT_NOTES.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND Z_USER.PK_USER = S_STUDENT_NOTES.CREATED_BY AND PK_USER_TYPE IN (1,2) AND Z_USER.ID = CREATED_EMP.PK_EMPLOYEE_MASTER "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['TASK'][$j]['ENROLLMENT']		= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['TASK'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['NOTES'][$j]['DEPARTMENT']	= $res_det->fields['DEPARTMENT'];
			$data['LEAD'][$i]['NOTES'][$j]['DEPARTMENT_ID']	= $res_det->fields['PK_DEPARTMENT'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_STATUS']	= $res_det->fields['NOTE_STATUS'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_STATUS_ID']= $res_det->fields['PK_NOTE_STATUS'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_TYPE']		= $res_det->fields['NOTE_TYPE'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_TYPE_ID']	= $res_det->fields['PK_NOTE_TYPE'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_DATE']		= $res_det->fields['NOTE_DATE'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_TIME']		= $res_det->fields['NOTE_TIME'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_TIME']		= $res_det->fields['TASK_TIME'];
			$data['LEAD'][$i]['NOTES'][$j]['NOTE_DATE']		= $res_det->fields['TASK_DATE'];
			$data['LEAD'][$i]['NOTES'][$j]['FOLLOWUP_DATE']	= $res_det->fields['FOLLOWUP_DATE'];
			$data['LEAD'][$i]['NOTES'][$j]['FOLLOWUP_TIME']	= $res_det->fields['FOLLOWUP_TIME'];
			$data['LEAD'][$i]['NOTES'][$j]['EMPLOYEE']		= $res_det->fields['EMP_NAME'];
			$data['LEAD'][$i]['NOTES'][$j]['COMPLETED']		= $res_det->fields['COMPLETED'];
			$data['LEAD'][$i]['NOTES'][$j]['COMMENTS']		= $res_det->fields['NOTES'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_NOTES, NOTE_STATUS, CODE,IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, NOTE_DATE, NOTE_TIME, S_STUDENT_NOTES.NOTES, NOTE_TYPE, CONCAT(EMP.FIRST_NAME,' ',EMP.LAST_NAME) AS EMP_NAME, IF(IS_EVENT = 1,'Yes', 'No') AS IS_EVENT, NOTES_PRIORITY, FOLLOWUP_DATE, SATISFIED, CONCAT(CREATED_EMP.FIRST_NAME,' ',CREATED_EMP.LAST_NAME) AS CREATED_BY,PK_NOTE_TYPE_MASTER, DEPARTMENT, S_STUDENT_NOTES.PK_STUDENT_ENROLLMENT, S_STUDENT_NOTES.PK_DEPARTMENT, S_STUDENT_NOTES.PK_NOTE_STATUS, M_NOTE_TYPE.PK_NOTE_TYPE, FOLLOWUP_DATE, FOLLOWUP_TIME , IF(SATISFIED = 1,'Yes','No') as COMPLETED    
		FROM 
		S_STUDENT_NOTES 
		LEFT JOIN M_DEPARTMENT ON M_DEPARTMENT.PK_DEPARTMENT = S_STUDENT_NOTES.PK_DEPARTMENT 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_NOTES.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
		LEFT JOIN S_EMPLOYEE_MASTER AS EMP ON EMP.PK_EMPLOYEE_MASTER = S_STUDENT_NOTES.PK_EMPLOYEE_MASTER 
		LEFT JOIN M_NOTES_PRIORITY_MASTER ON M_NOTES_PRIORITY_MASTER.PK_NOTES_PRIORITY_MASTER = S_STUDENT_NOTES.PK_NOTES_PRIORITY_MASTER 
		LEFT JOIN M_NOTE_STATUS ON M_NOTE_STATUS.PK_NOTE_STATUS = S_STUDENT_NOTES.PK_NOTE_STATUS 
		LEFT JOIN M_NOTE_TYPE ON S_STUDENT_NOTES.PK_NOTE_TYPE = M_NOTE_TYPE.PK_NOTE_TYPE
		, S_EMPLOYEE_MASTER AS CREATED_EMP, Z_USER  WHERE S_STUDENT_NOTES.PK_ACCOUNT = '$PK_ACCOUNT'  AND IS_EVENT = 1 AND S_STUDENT_NOTES.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND Z_USER.PK_USER = S_STUDENT_NOTES.CREATED_BY AND PK_USER_TYPE IN (1,2) AND Z_USER.ID = CREATED_EMP.PK_EMPLOYEE_MASTER "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['EVENTS'][$j]['ENROLLMENT']		= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['EVENTS'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['EVENTS'][$j]['DEPARTMENT']		= $res_det->fields['DEPARTMENT'];
			$data['LEAD'][$i]['EVENTS'][$j]['DEPARTMENT_ID']	= $res_det->fields['PK_DEPARTMENT'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_STATUS']	= $res_det->fields['NOTE_STATUS'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_STATUS_ID']	= $res_det->fields['PK_NOTE_STATUS'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_TYPE']		= $res_det->fields['NOTE_TYPE'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_TYPE_ID']	= $res_det->fields['PK_NOTE_TYPE'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_DATE']		= $res_det->fields['NOTE_DATE'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_TIME']		= $res_det->fields['NOTE_TIME'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_TIME']		= $res_det->fields['TASK_TIME'];
			$data['LEAD'][$i]['EVENTS'][$j]['EVENTS_DATE']		= $res_det->fields['TASK_DATE'];
			$data['LEAD'][$i]['EVENTS'][$j]['FOLLOWUP_DATE']	= $res_det->fields['FOLLOWUP_DATE'];
			$data['LEAD'][$i]['EVENTS'][$j]['FOLLOWUP_TIME']	= $res_det->fields['FOLLOWUP_TIME'];
			$data['LEAD'][$i]['EVENTS'][$j]['EMPLOYEE']			= $res_det->fields['EMP_NAME'];
			$data['LEAD'][$i]['EVENTS'][$j]['COMPLETED']		= $res_det->fields['COMPLETED'];
			$data['LEAD'][$i]['EVENTS'][$j]['COMMENTS']			= $res_det->fields['NOTES'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_DOCUMENTS,CODE,IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, DOCUMENT_TYPE, S_STUDENT_DOCUMENTS.NOTES, REQUESTED_DATE, IF(RECEIVED = 1,'Yes', 'No') as RECEIVED, DATE_RECEIVED, FOLLOWUP_DATE, CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT FROM S_STUDENT_DOCUMENTS LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_STUDENT_DOCUMENTS.PK_EMPLOYEE_MASTER WHERE S_STUDENT_DOCUMENTS.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['DOCUMENTS'][$j]['ENROLLMENT']	= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['REQUESTED_DATE']= $res_det->fields['REQUESTED_DATE'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['DOCUMENT_TYPE']	= $res_det->fields['DOCUMENT_TYPE'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['EMPLOYEE']		= $res_det->fields['NAME'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['FOLLOWUP_DATE']	= $res_det->fields['FOLLOWUP_DATE'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['RECEIVED']		= $res_det->fields['RECEIVED'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['DATE_RECEIVED']	= $res_det->fields['DATE_RECEIVED'];
			$data['LEAD'][$i]['DOCUMENTS'][$j]['NOTES']			= $res_det->fields['NOTES'];
			
			$DEPARTMENT_NAME	  = array();
			$PK_STUDENT_DOCUMENTS = $res_det->fields['PK_STUDENT_DOCUMENTS'];
			$res_dep = $db->Execute("SELECT M_DEPARTMENT.PK_DEPARTMENT,DEPARTMENT FROM S_STUDENT_DOCUMENTS_DEPARTMENT, M_DEPARTMENT WHERE M_DEPARTMENT.PK_DEPARTMENT = S_STUDENT_DOCUMENTS_DEPARTMENT.PK_DEPARTMENT AND PK_STUDENT_DOCUMENTS = '$PK_STUDENT_DOCUMENTS' "); 
			while (!$res_dep->EOF) {
				$DEPARTMENT_NAME[] = $res_dep->fields['PK_DEPARTMENT'];
				$res_dep->MoveNext();
			}
			$data['LEAD'][$i]['DOCUMENTS'][$j]['DEPARTMENTS'] = $DEPARTMENT_NAME;
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("SELECT PK_STUDENT_REQUIREMENT, MANDATORY AS MANDATORY_1, REQUIREMENT,IF(MANDATORY = 1,'Yes','No') as MANDATORY, IF(COMPLETED = 1,'Yes','No') as  COMPLETED, COMPLETED_ON, IF(TYPE = 1, 'School',  IF(TYPE = 2, 'Program', '')) AS TYPE, CODE, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, S_STUDENT_REQUIREMENT.PK_STUDENT_ENROLLMENT FROM S_STUDENT_REQUIREMENT LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_REQUIREMENT.PK_STUDENT_ENROLLMENT LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER WHERE S_STUDENT_REQUIREMENT.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' ORDER BY REQUIREMENT ASC"); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['REQUIREMENT'][$j]['ENROLLMENT']			= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['REQUIREMENT'][$j]['ENROLLMENT_ID']		= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			
			$data['LEAD'][$i]['REQUIREMENT'][$j]['REQUIREMENT']			= $res_det->fields['REQUIREMENT'];
			$data['LEAD'][$i]['REQUIREMENT'][$j]['MANDATORY']			= $res_det->fields['MANDATORY'];
			$data['LEAD'][$i]['REQUIREMENT'][$j]['COMPLETED']			= $res_det->fields['COMPLETED'];
			$data['LEAD'][$i]['REQUIREMENT'][$j]['COMPLETED_ON']		= $res_det->fields['COMPLETED_ON'];
			$data['LEAD'][$i]['REQUIREMENT'][$j]['REQUIREMENT_TYPE']	= $res_det->fields['TYPE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("SELECT QUESTION,PK_QUESTIONNAIRE, DEPARTMENT, M_QUESTIONNAIRE.PK_DEPARTMENT FROM M_QUESTIONNAIRE LEFT JOIN M_DEPARTMENT ON M_QUESTIONNAIRE.PK_DEPARTMENT = M_DEPARTMENT.PK_DEPARTMENT  WHERE M_QUESTIONNAIRE.PK_ACCOUNT = '$PK_ACCOUNT' "); 
		while (!$res_det->EOF) { 
			$PK_QUESTIONNAIRE = $res_det->fields['PK_QUESTIONNAIRE'];
			$res_det1 = $db->Execute("SELECT ANSWER, CODE, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, S_STUDENT_QUESTIONNAIRE.PK_STUDENT_ENROLLMENT  FROM S_STUDENT_QUESTIONNAIRE LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_QUESTIONNAIRE.PK_STUDENT_ENROLLMENT LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER WHERE S_STUDENT_QUESTIONNAIRE.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_QUESTIONNAIRE = '$PK_QUESTIONNAIRE'  ");
			
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['ENROLLMENT']	= $res_det1->fields['CODE'].' - '.$res_det1->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['ENROLLMENT_ID']	= $res_det1->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['ANSWER']		= $res_det1->fields['ANSWER'];
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['QUESTION']		= $res_det->fields['QUESTION'];
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['QUESTION_ID']	= $PK_QUESTIONNAIRE;
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['DEPARTMENT']	= $res_det->fields['DEPARTMENT'];
			$data['LEAD'][$i]['QUESTIONNAIRE'][$j]['DEPARTMENT_ID']	= $res_det->fields['PK_DEPARTMENT'];
			
			$j++;
			$res_det->MoveNext();
		}
		/* */
		$j = 0;
		$res_det = $db->Execute("select EDUCATION_TYPE, S_STUDENT_OTHER_EDU.PK_EDUCATION_TYPE, IF(GRADUATED = 1,'Yes','No') as GRADUATED, GRADUATED_DATE, IF(TRANSCRIPT_REQUESTED = 1,'Yes','No') as TRANSCRIPT_REQUESTED, TRANSCRIPT_REQUESTED_DATE, IF(TRANSCRIPT_RECEIVED = 1,'Yes','No') as TRANSCRIPT_RECEIVED, TRANSCRIPT_RECEIVED_DATE, SCHOOL_NAME, ADDRESS, ADDRESS_1, CITY, STATE_NAME, ZIP, OTHER_SCHOOL_PHONE, OTHER_SCHOOL_FAX from 
		S_STUDENT_OTHER_EDU 
		LEFT JOIN Z_STATES ON Z_STATES.PK_STATES = S_STUDENT_OTHER_EDU.PK_STATE  
		LEFT JOIN M_EDUCATION_TYPE ON M_EDUCATION_TYPE.PK_EDUCATION_TYPE = S_STUDENT_OTHER_EDU.PK_EDUCATION_TYPE
		WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER'"); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['EDUCATION_TYPE']				= $res_det->fields['EDUCATION_TYPE'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['EDUCATION_TYPE_ID']			= $res_det->fields['PK_EDUCATION_TYPE'];
			
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['GRADUATED']					= $res_det->fields['GRADUATED'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['GRADUATED_DATE']				= $res_det->fields['GRADUATED_DATE'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['TRANSCRIPT_REQUESTED']		= $res_det->fields['TRANSCRIPT_REQUESTED'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['TRANSCRIPT_REQUESTED_DATE']	= $res_det->fields['TRANSCRIPT_REQUESTED_DATE'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['TRANSCRIPT_RECEIVED']			= $res_det->fields['TRANSCRIPT_RECEIVED'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['TRANSCRIPT_RECEIVED_DATE']	= $res_det->fields['TRANSCRIPT_RECEIVED_DATE'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['SCHOOL_NAME']					= $res_det->fields['SCHOOL_NAME'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['ADDRESS']						= $res_det->fields['ADDRESS'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['ADDRESS_1']					= $res_det->fields['ADDRESS_1'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['CITY']						= $res_det->fields['CITY'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['STATE_NAME']					= $res_det->fields['STATE_NAME'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['ZIP']							= $res_det->fields['ZIP'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['SCHOOL_PHONE']				= $res_det->fields['OTHER_SCHOOL_PHONE'];
			$data['LEAD'][$i]['OTHER_EDUCATION'][$j]['SCHOOL_FAX']					= $res_det->fields['OTHER_SCHOOL_FAX'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_TEST, TEST_LABEL, TEST_RESULT, IF(PASSED = 1,'Yes', 'No') as PASSED, TEST_DATE, CODE, IF(BEGIN_DATE = '0000-00-00','', DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1  
		from 
		S_STUDENT_TEST LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_TEST.PK_STUDENT_ENROLLMENT LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER
		
		WHERE S_STUDENT_TEST.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['TESTS'][$j]['ENROLLMENT']	= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['TESTS'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			
			$data['LEAD'][$i]['TESTS'][$j]['TEST_LABEL']	= $res_det->fields['TEST_LABEL'];
			$data['LEAD'][$i]['TESTS'][$j]['TEST_RESULT']	= $res_det->fields['TEST_RESULT'];
			$data['LEAD'][$i]['TESTS'][$j]['PASSED']		= $res_det->fields['PASSED'];
			$data['LEAD'][$i]['TESTS'][$j]['TEST_DATE']		= $res_det->fields['TEST_DATE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select PK_STUDENT_ATB_TEST, S_STUDENT_ATB_TEST.PK_ATB_CODE, CONCAT(ATB_CODE,' - ',M_ATB_CODE.DESCRIPTION) as ATB_CODE, CONCAT(ATB_ADMIN_CODE,' - ',M_ATB_ADMIN_CODE.DESCRIPTION) as ATB_ADMIN_CODE , S_STUDENT_ATB_TEST.PK_ATB_TEST_CODE, S_STUDENT_ATB_TEST.PK_ATB_ADMIN_CODE, CODE, IF(BEGIN_DATE = '0000-00-00','', DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS BEGIN_DATE_1, COMPLETED_DATE, ATB_TEST_CODE   
		from 
		S_STUDENT_ATB_TEST  
		LEFT JOIN M_ATB_CODE ON M_ATB_CODE.PK_ATB_CODE = S_STUDENT_ATB_TEST.PK_ATB_CODE 
		LEFT JOIN M_ATB_TEST_CODE ON M_ATB_TEST_CODE.PK_ATB_TEST_CODE = S_STUDENT_ATB_TEST.PK_ATB_TEST_CODE 
		LEFT JOIN M_ATB_ADMIN_CODE ON M_ATB_ADMIN_CODE.PK_ATB_ADMIN_CODE = S_STUDENT_ATB_TEST.PK_ATB_ADMIN_CODE 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_ATB_TEST.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER
		
		WHERE S_STUDENT_ATB_TEST.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['ATB_TEST'][$j]['ENROLLMENT']		= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ENROLLMENT_ID']	= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_CODE']				= $res_det->fields['ATB_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_CODE_ID']			= $res_det->fields['PK_ATB_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_TEST_CODE']			= $res_det->fields['ATB_TEST_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_TEST_CODE_ID']		= $res_det->fields['PK_ATB_TEST_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_ADMIN_CODE']			= $res_det->fields['ATB_ADMIN_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['ATB_ADMIN_CODE_ID']		= $res_det->fields['PK_ATB_ADMIN_CODE'];
			$data['LEAD'][$i]['ATB_TEST'][$j]['COMPLETED_DATE']			= $res_det->fields['COMPLETED_DATE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select S_STUDENT_ACT_TEST.PK_ACT_MEASURE, CONCAT(ACT_MEASURE,' - ',M_ACT_MEASURE.DESCRIPTION) as  ACT_MEASURE, SCORE, STATE_RANK, NATIONAL_RANK, TEST_DATE   
		from 
		S_STUDENT_ACT_TEST  
		LEFT JOIN M_ACT_MEASURE ON M_ACT_MEASURE.PK_ACT_MEASURE = S_STUDENT_ACT_TEST.PK_ACT_MEASURE 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_ACT_TEST.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER
		
		WHERE S_STUDENT_ACT_TEST.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['ACT_TEST'][$j]['ENROLLMENT']			= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['ENROLLMENT_ID']		= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['ACT_MEASURE']		= $res_det->fields['ACT_MEASURE'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['ACT_MEASURE_ID']		= $res_det->fields['PK_ACT_MEASURE'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['SCORE']				= $res_det->fields['SCORE'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['STATE_RANK']			= $res_det->fields['STATE_RANK'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['NATIONAL_RANK']		= $res_det->fields['NATIONAL_RANK'];
			$data['LEAD'][$i]['ACT_TEST'][$j]['TEST_DATE']			= $res_det->fields['TEST_DATE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_det = $db->Execute("select S_STUDENT_SAT_TEST.PK_SAT_MEASURE, CONCAT(SAT_MEASURE,' - ',M_SAT_MEASURE.DESCRIPTION) as  SAT_MEASURE, SCORE, USER_RANK, TEST_DATE   
		from 
		S_STUDENT_SAT_TEST  
		LEFT JOIN M_SAT_MEASURE ON M_SAT_MEASURE.PK_SAT_MEASURE = S_STUDENT_SAT_TEST.PK_SAT_MEASURE 
		LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_SAT_TEST.PK_STUDENT_ENROLLMENT 
		LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM =  S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
		LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER
		
		WHERE S_STUDENT_SAT_TEST.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' "); 
		while (!$res_det->EOF) { 
			$data['LEAD'][$i]['SAT_TEST'][$j]['ENROLLMENT']			= $res_det->fields['CODE'].' - '.$res_det->fields['BEGIN_DATE_1'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['ENROLLMENT_ID']		= $res_det->fields['PK_STUDENT_ENROLLMENT'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['SAT_MEASURE']		= $res_det->fields['SAT_MEASURE'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['SAT_MEASURE_ID']		= $res_det->fields['PK_SAT_MEASURE'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['SCORE']				= $res_det->fields['SCORE'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['USER_RANK']			= $res_det->fields['USER_RANK'];
			$data['LEAD'][$i]['SAT_TEST'][$j]['TEST_DATE']			= $res_det->fields['TEST_DATE'];
			
			$j++;
			$res_det->MoveNext();
		}
		
		$j = 0;
		$res_type = $db->Execute("select PK_CUSTOM_FIELDS,FIELD_NAME,PK_DATA_TYPES, PK_USER_DEFINED_FIELDS from S_CUSTOM_FIELDS WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND SECTION = 1"); 
		while (!$res_type->EOF) { 
			$PK_CUSTOM_FIELDS 		= $res_type->fields['PK_CUSTOM_FIELDS'];
			$PK_USER_DEFINED_FIELDS = $res_type->fields['PK_USER_DEFINED_FIELDS'];
			
			$res_1 = $db->Execute("select FIELD_VALUE from S_STUDENT_CUSTOM_FIELDS WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_CUSTOM_FIELDS = '$PK_CUSTOM_FIELDS' ");
			
			$FIELD_VALUE = '';
			if($res_type->fields['PK_DATA_TYPES'] == 1 || $res_type->fields['PK_DATA_TYPES'] == 4)
				$FIELD_VALUE = $res_1->fields['FIELD_VALUE'];
			else if($res_type->fields['PK_DATA_TYPES'] == 2 || $res_type->fields['PK_DATA_TYPES'] == 3) {
				$OPTIONS = explode(",",$res_1->fields['FIELD_VALUE']);
				$res_dd = $db->Execute("select OPTION_NAME from S_USER_DEFINED_FIELDS_DETAIL WHERE ACTIVE = '1' AND PK_USER_DEFINED_FIELDS_DETAIL IN (".$res_1->fields['FIELD_VALUE'].") ");
				while (!$res_dd->EOF) { 
					if($FIELD_VALUE != '')
						$FIELD_VALUE .= ', ';
					$FIELD_VALUE .= $res_dd->fields['OPTION_NAME'];
					
					$res_dd->MoveNext();
				}
			}
			
			$data['LEAD'][$i]['CUSTOM_FIELDS'][$j]['NAME']	= $res_type->fields['FIELD_NAME'];
			$data['LEAD'][$i]['CUSTOM_FIELDS'][$j]['VALUE']	= $FIELD_VALUE;
			
			$j++;
			$res_type->MoveNext();
		}
		
		$i++;
		$res->MoveNext();
	}
}

$data = json_encode($data);
echo $data;