<? require_once("../global/config.php"); 
require_once("../language/instructor_select_students.php");
require_once("../language/common.php");

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == ''){ 
	header("location:../index");
	exit;
}

$cond = "";

if($_REQUEST['type'] == 'select_stu')
	$cond .= " AND S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT NOT IN (SELECT PK_STUDENT_ENROLLMENT FROM S_INSTRUCTOR_STUDENT WHERE PK_EMPLOYEE_MASTER = '$_SESSION[PK_EMPLOYEE_MASTER]') ";
if($_REQUEST['PK_STUDENT_GROUP'] != '')
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP  = '$_REQUEST[PK_STUDENT_GROUP]' ";
if($_REQUEST['PK_TERM_MASTER'] != '')
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_TERM_MASTER  = '$_REQUEST[PK_TERM_MASTER]' ";
if($_REQUEST['PK_CAMPUS_PROGRAM'] != '')
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM  = '$_REQUEST[PK_CAMPUS_PROGRAM]' ";
if($_REQUEST['PK_STUDENT_STATUS'] != '')
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS  = '$_REQUEST[PK_STUDENT_STATUS]' ";
	
?>
<table class="table table-bordered">
	<thead>
		<tr>
			<th >
				<input type="checkbox" id="CHECK_ALL" onclick="fun_check_all()" >
			</th>
			<th ><?=LAST_NAME?></th>
			<th ><?=FIRST_NAME?></th>
			<th ><?=START_DATE?></th>
			<th ><?=STATUS?></th>
			<th ><?=PROGRAM?></th>
		</tr>
	</thead>
	<tbody>
	<? $res_cs = $db->Execute("select S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT,S_STUDENT_MASTER.PK_STUDENT_MASTER,LAST_NAME, FIRST_NAME, IF(S_TERM_MASTER.BEGIN_DATE = '0000-00-00','',DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE,'%m/%d/%Y' )) AS BEGIN_DATE, M_CAMPUS_PROGRAM.CODE, STUDENT_STATUS 
	FROM 
	S_STUDENT_MASTER, S_STUDENT_COURSE, 
	S_COURSE_OFFERING 
	LEFT JOIN S_COURSE_OFFERING_ASSISTANT ON S_COURSE_OFFERING_ASSISTANT.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING 
	, S_STUDENT_ENROLLMENT
	LEFT JOIN M_STUDENT_GROUP ON M_STUDENT_GROUP.PK_STUDENT_GROUP = S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP 
	LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
	LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
	LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
	WHERE 
	S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
	ARCHIVED = 0 AND 
	S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND 
	S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND 
	S_COURSE_OFFERING.PK_COURSE_OFFERING = S_STUDENT_COURSE.PK_COURSE_OFFERING AND 
	(INSTRUCTOR = '$_SESSION[PK_EMPLOYEE_MASTER]' OR S_COURSE_OFFERING_ASSISTANT.ASSISTANT = '$_SESSION[PK_EMPLOYEE_MASTER]') $cond  
	GROUP BY S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT ORDER BY CONCAT(LAST_NAME,', ',FIRST_NAME)"); 
	while (!$res_cs->EOF) { ?>
		<tr>
			<td><input type="checkbox" id="PK_STUDENT_ENROLLMENT_<?=$res_cs->fields['PK_STUDENT_ENROLLMENT']?>" name="PK_STUDENT_ENROLLMENT[]" value="<?=$res_cs->fields['PK_STUDENT_ENROLLMENT']?>" ></td>
			<td><?=$res_cs->fields['LAST_NAME']?></td>
			<td><?=$res_cs->fields['FIRST_NAME']?></td>
			<td><?=$res_cs->fields['BEGIN_DATE']?></td>
			<td><?=$res_cs->fields['STUDENT_STATUS']?></td>
			<td><?=$res_cs->fields['CODE']?></td>
		</tr>
	<?	$res_cs->MoveNext();
	} ?>
	</tbody>
</table>
