<? require_once("../global/config.php");
if($_SESSION['PK_LANGUAGE'] == 1){
	//English
	define("ADDRESS", "Address", true);
	define("ADDRESS_1", "Address 2nd Line", true);
	define("CITY", "City", true);
	define("STATE", "State", true);
	define("ZIP", "Zip", true);
	define("COUNTRY", "Country", true);
	define("CONTACT_TYPE", "Contact Type", true);
	define("NAME", "Name", true);
	define("FIRST_NAME", "First Name", true);
	define("LAST_NAME", "Last Name", true);
	define("MIDDLE_NAME", "Middle Name", true);
	define("OTHER_NAME", "Other Name", true);
	define("PREFIX", "Prefix", true);
	define("SSN", "SSN", true);
	define("CREATE_LOGIN", "Create Login", true);
	define("REMOVE_LOGIN", "Remove Login", true);
	define("USER_ID", "User ID", true);
	define("USER_ID_EXISTS", "User ID already exists. Try with another.", true);
	define("PASSWORD", "Password", true);
	define("RESET_PASSWORD", "Reset Password", true);
	define("PHONE", "Phone", true);
	define("CELL_PHONE", "Mobile Phone", true);
	define("HOME_PHONE", "Home Phone", true);
	define("WORK_PHONE", "Work Phone", true);
	define("OTHER_PHONE", "Other Phone", true);
	define("CELL_PHONE_SHORT", "Mobile", true);
	define("HOME_PHONE_SHORT", "Home", true);
	define("WORK_PHONE_SHORT", "Work", true);
	define("OTHER_PHONE_SHORT", "Other", true);
	define("PHONES", "Phones", true);
	define("EMAIL", "Email", true);
	define("EMAIL_OTHER", "Email Other", true);
	define("USE_EMAIL", "Use Email", true);
	define("FAX", "Fax", true);
	define("WEBSITE", "Website", true);
	define("OPTOUT", "Opt Out", true);
	define("EMERGENCY", "Emergency", true);
	define("NOTES", "Notes", true);
	define("LOGO", "Logo", true);
	define("CHOOSE_FILE", "Choose file", true);
	define("SAVE", "Save", true);
	define("SAVE_CONTINUE", "Save", true);
	define("SAVE_EXIT", "Save & Exit", true);
	define("CANCEL", "Cancel", true);
	define("CREATE_NEW", "Create New", true);
	define("REQUEST_DOCUMENTS", "Request Documents", true);
	define("REQUEST", "Request", true);
	define("PRIMARY", "Primary", true);
	define("OPTIONS", "Options", true);
	define("OPTION", "Options", true);
	define("DELETE", "Delete", true);
	define("EDIT", "Edit", true);
	define("ACTIVE", "Active", true);
	define("HAS_LOGIN", "Has Login", true);
	define("SEARCH", "Search", true);
	define("DELETE_CONFIRMATION", "Delete Confirmation", true);
	define("INACTIVE_CONFIRMATION", "Are you sure want to mark this Record as Inactive?", true);
	define("YES", "Yes", true);
	define("NO", "No", true);
	define("DELETE_MESSAGE", "Are you sure you want to Delete this ", true);
	define("DELETE_MESSAGE_GENERAL", "Are you sure want to Delete this Record?", true);
	define("ADD", "Add", true);
	define("EDIT", "Edit", true);
	define("DESCRIPTION", "Description", true);
	define("CREATE_LOGIN", "Create Login", true);
	define("ROLE", "Role", true);
	define("RESET_LOGIN", "Reset Password", true);
	define("BACK", "Back", true);
	define("CHANGE", "Change", true);
	define("DATE", "Date", true);
	define("TYPE", "Type", true);
	define("COMMENTS", "Comments", true);
	define("CREATED_BY", "Created By", true);
	define("ASSIGN", "Assign", true);
	define("DATE", "Date", true);
	define("TIME", "Time", true);
	define("PREFERRED_LANGUAGE", "Preferred Language", true);
	define("TYPE", "Type", true);
	define("FULL_NAME", "Full Name", true);
	define("COMPLETED_ON", "Completed On", true);
	define("DUPLICATE", "Duplicate", true);
	define("UPLOAD", "Upload", true);
	define("UPLOAD_FILE", "Upload File", true);
	define("MAPPING", "Mapping", true);
	define("SELECT", "Select", true);
	define("SELECT_ALL", "Select All", true);
	define("NEXT", "Next", true);
	define("SHOW_ARCHIVED", "Show Archive", true);
	define("ARCHIVE", "Archive", true);
	define("UNARCHIVE", "Unarchive", true);
	define("ARCHIVE_CONFIRMATION", "Archive Confirmation", true);
	define("ARCHIVE_MESSAGE_GENERAL", "Are you sure want to Archive this Record?", true);
	define("UNARCHIVE_MESSAGE_GENERAL", "Are you sure want to Unarchive this Record?", true);
	define("CHANGE_STATUS", "Change Status", true);
	define("STATUS", "Status", true);
	define("PROCEED", "Proceed", true);
	define("VIEW", "View", true);
	define("NO_NOTIFICATION", "No Notification Found", true);
	define("ACTION", "Action", true);
	define("BULK_UPDATE", "Bulk Update", true);
	define("CAMPUS", "Campus", true);
	define("ADD_TO_UPDATE_LIST", "Add To Update List", true);
	define("UPDATE_LIST", "Update List", true);
	define("REMOVE", "Remove", true);
	define("UPDATE", "Update", true);
	define("IMPORT", "Import", true);
	define("FROM_DATE", "From Date", true);
	define("TO_DATE", "To Date", true);
	define("DUPLICATE_REPORT", "Duplicate Report", true);
	define("NO_RECORD_FOUND", "No Record Found", true);
	define("REASON", "Reason", true);
	define("OTHER_EDUCATION", "Other Education", true);
	define("DATA_VIEW", "Data View", true);
	define("AWARDS", "Awards", true);
	define("TOTAL_AMOUNT", "Total Amount", true);
	define("DISBURSEMENTS", "Disbursements", true);
	define("FIRST_DATE", "First Date", true);
	define("NO_OF_DAYS", "No. Of Days", true);
	define("PAYMENT_FREQUENCY", "Payment Frequency", true);
	define("DETAILS", "Details", true);
	define("FUNDS_REQUESTED", "Funds Requested", true);
	define("NO_OF_PAYMENTS", "No. Of Payments", true);
	define("TRANSACTION_DATE", "Transaction Date", true);
	define("DEBIT", "Debit", true);
	define("CREDIT", "Credit", true);
	define("BALANCE", "Balance", true);
	define("ERROR", "Error", true);
	define("DUE_AMOUNT", "Due Amount", true);
	define("PAID_AMOUNT", "Paid Amount", true);
	define("NEW_AMOUNT", "New Amount", true);
	define("STUDENT", "Student", true);
	define("WELCOME", "Welcome", true);
	define("SHOW", "Show", true);
	define("TOTAL", "Total", true);
	define("TOTALS", "Totals", true);
	define("IN_PROGRESS", "In Progress", true);
	define("ATTEMPTED", "Attempted", true);
	define("GPA", "GPA", true);
	define("ALL", "All", true);
	define("IMPORT", "Import", true);
	define("GROSS", "Gross", true);
	define("DUE_DATE", "Due Date", true);
	define("AMOUNT", "Amount", true);
	define("PAID_DATE", "Paid Date", true);
	define("HEADING_ROW_NO", "Heading Row #", true);
	define("ADD_TO_BULK_CREATE_LIST", "Add To Bulk Create List", true);
	define("BULK", "Bulk", true);
	define("STUDENT_NAME", "Student Name", true);
	define("LOGIN_ID", "Login ID", true);
	define("S_NO", "S NO.", true);
	define("EMAIL", "Email", true);
	define("TEXT", "Text", true);
	define("SUBJECT", "Subject", true);
	define("MESSAGE", "Message", true);
	define("SEND", "Send", true);
	define("START", "Start", true);
	define("END", "End", true);
	define("ACCEPTED", "Accepted", true);
	define("MNU_CREATE_STUDENT_LOGIN_DATA_VIEW", "Create Student Login Data View", true);
	define("RUN", "Run", true);
	define("PLEASE_CORRECT_FOLLOWING_ERRORS", "Please Correct The Following Errors", true);
	define("SELECT_REPORT_TYPE", "Select Report Type", true);
	define("DISPLAY_ORDER", "Display Order", true);
	define("TAB_GENERAL", "General", true);
	define("SUMMARY", "Summary", true);
	define("GENERATE", "Generate", true);
	define("SCHOOL", "School", true);
	define("TOTAL_COUNT", "Total Count", true);
	define("MAKE_PAYMENT", "Make Payment", true);
	define("LOGOUT", "Logout", true);
	define("LOGOUT_MESSAGE", "You will be Logged Out due to Inactive Session.<br />Click \"I AM IN\" to Continue", true);
	define("I_AM_IN", "I AM IN", true);
	define("MAKE_PAYMENT_BY_CARD", "Make Payment By Card", true);
	define("UPLOADS", "Uploads", true);
	define("LEAD_UPLOAD", "Lead Upload", true);
	define("RESET_PASSWORD_MESSAGE", "Are you sure you want to reset the password?", true);
	define("INVALID_USER_ID", "Invalid User ID", true);
	define("LOGIN_NOT_FOUND", "Login Not Found", true);
	define("ACCOUNT_BLOCKED", "This Account is Blocked Already", true);
	define("RESET_EMAIL_SENT_TO", "Reset Email Sent To ", true);
	define("EMAIL_ID_NOT_FOUND", "Email ID Not Found", true);
	define("EMAIL_EXISTS", "Email ID Already Exists", true);
} else if($_SESSION['PK_LANGUAGE'] == 2){
	//Spanish
	
	define("ADDRESS", "Address", true);
	define("ADDRESS_1", "Address 2nd Line", true);
	define("CITY", "City", true);
	define("STATE", "State", true);
	define("ZIP", "Zip", true);
	define("COUNTRY", "Country", true);
	define("CONTACT_TYPE", "Contact Type", true);
	define("NAME", "Name", true);
	define("FIRST_NAME", "First Name", true);
	define("LAST_NAME", "Last Name", true);
	define("MIDDLE_NAME", "Middle Name", true);
	define("OTHER_NAME", "Other Name", true);
	define("PREFIX", "Prefix", true);
	define("SSN", "SSN", true);
	define("CREATE_LOGIN", "Create Login", true);
	define("REMOVE_LOGIN", "Remove Login", true);
	define("USER_ID", "User ID", true);
	define("USER_ID_EXISTS", "User ID already exists. Try with another.", true);
	define("PASSWORD", "Password", true);
	define("RESET_PASSWORD", "Reset Password", true);
	define("PHONE", "Phone", true);
	define("CELL_PHONE", "Mobile Phone", true);
	define("HOME_PHONE", "Home Phone", true);
	define("WORK_PHONE", "Work Phone", true);
	define("OTHER_PHONE", "Other Phone", true);
	define("CELL_PHONE_SHORT", "Mobile", true);
	define("HOME_PHONE_SHORT", "Home", true);
	define("WORK_PHONE_SHORT", "Work", true);
	define("OTHER_PHONE_SHORT", "Other", true);
	define("EMAIL", "Email", true);
	define("EMAIL_OTHER", "Email Other", true);
	define("USE_EMAIL", "Use Email", true);
	define("FAX", "Fax", true);
	define("WEBSITE", "Website", true);
	define("OPTOUT", "Opt Out", true);
	define("EMERGENCY", "Emergency", true);
	define("NOTES", "Notes", true);
	define("LOGO", "Logo", true);
	define("CHOOSE_FILE", "Choose file", true);
	define("SAVE", "Save", true);
	define("SAVE_CONTINUE", "Save", true);
	define("SAVE_EXIT", "Save & Exit", true);
	define("CANCEL", "Cancel", true);
	define("CREATE_NEW", "Create New", true);
	define("REQUEST_DOCUMENTS", "Request Documents", true);
	define("REQUEST", "Request", true);
	define("PRIMARY", "Primary", true);
	define("OPTIONS", "Options", true);
	define("OPTION", "Options", true);
	define("DELETE", "Delete", true);
	define("EDIT", "Edit", true);
	define("ACTIVE", "Active", true);
	define("HAS_LOGIN", "Has Login", true);
	define("SEARCH", "Search", true);
	define("DELETE_CONFIRMATION", "Delete Confirmation", true);
	define("INACTIVE_CONFIRMATION", "Are you sure want to mark this Record as Inactive?", true);
	define("YES", "Yes", true);
	define("NO", "No", true);
	define("DELETE_MESSAGE", "Are you sure you want to Delete this ", true);
	define("DELETE_MESSAGE_GENERAL", "Are you sure want to Delete this Record?", true);
	define("ADD", "Add", true);
	define("EDIT", "Edit", true);
	define("DESCRIPTION", "Description", true);
	define("CREATE_LOGIN", "Create Login", true);
	define("ROLE", "Role", true);
	define("RESET_LOGIN", "Reset Password", true);
	define("BACK", "Back", true);
	define("CHANGE", "Change", true);
	define("DATE", "Date", true);
	define("TYPE", "Type", true);
	define("COMMENTS", "Comments", true);
	define("CREATED_BY", "Created By", true);
	define("ASSIGN", "Assign", true);
	define("DATE", "Date", true);
	define("TIME", "Time", true);
	define("PREFERRED_LANGUAGE", "Preferred Language", true);
	define("PHONES", "Phones", true);
	define("TYPE", "Type", true);
	define("FULL_NAME", "Full Name", true);
	define("COMPLETED_ON", "Completed On", true);
	define("DUPLICATE", "Duplicate", true);
	define("UPLOAD", "Upload", true);
	define("UPLOAD_FILE", "Upload File", true);
	define("MAPPING", "Mapping", true);
	define("SELECT", "Select", true);
	define("SELECT_ALL", "Select All", true);
	define("NEXT", "Next", true);
	define("SHOW_ARCHIVED", "Show Archive", true);
	define("ARCHIVE", "Archive", true);
	define("UNARCHIVE", "Unarchive", true);
	define("ARCHIVE_CONFIRMATION", "Archive Confirmation", true);
	define("ARCHIVE_MESSAGE_GENERAL", "Are you sure want to Archive this Record?", true);
	define("UNARCHIVE_MESSAGE_GENERAL", "Are you sure want to Unarchive this Record?", true);
	define("CHANGE_STATUS", "Change Status", true);
	define("STATUS", "Status", true);
	define("PROCEED", "Proceed", true);
	define("VIEW", "View", true);
	define("NO_NOTIFICATION", "No Notification Found", true);
	define("ACTION", "Action", true);
	define("BULK_UPDATE", "Bulk Update", true);
	define("CAMPUS", "Campus", true);
	define("ADD_TO_UPDATE_LIST", "Add To Update List", true);
	define("UPDATE_LIST", "Update List", true);
	define("REMOVE", "Remove", true);
	define("UPDATE", "Update", true);
	define("IMPORT", "Import", true);
	define("FROM_DATE", "From Date", true);
	define("TO_DATE", "To Date", true);
	define("DUPLICATE_REPORT", "Duplicate Report", true);
	define("NO_RECORD_FOUND", "No Record Found", true);
	define("REASON", "Reason", true);
	define("OTHER_EDUCATION", "Other Education", true);
	define("DATA_VIEW", "Data View", true);
	define("AWARDS", "Awards", true);
	define("TOTAL_AMOUNT", "Total Amount", true);
	define("DISBURSEMENTS", "Disbursements", true);
	define("FIRST_DATE", "First Date", true);
	define("NO_OF_DAYS", "No. Of Days", true);
	define("PAYMENT_FREQUENCY", "Payment Frequency", true);
	define("DETAILS", "Details", true);
	define("FUNDS_REQUESTED", "Funds Requested", true);
	define("NO_OF_PAYMENTS", "No. Of Payments", true);
	define("TRANSACTION_DATE", "Transaction Date", true);
	define("DEBIT", "Debit", true);
	define("CREDIT", "Credit", true);
	define("BALANCE", "Balance", true);
	define("ERROR", "Error", true);
	define("DUE_AMOUNT", "Due Amount", true);
	define("PAID_AMOUNT", "Paid Amount", true);
	define("NEW_AMOUNT", "New Amount", true);
	define("RECEIPT_NO", "Receipt #", true);
	define("STUDENT", "Student", true);
	define("WELCOME", "Welcome", true);
	define("SHOW", "Show", true);
	define("TOTAL", "Total", true);
	define("TOTALS", "Totals", true);
	define("IN_PROGRESS", "In Progress", true);
	define("ATTEMPTED", "Attempted", true);
	define("GPA", "GPA", true);
	define("ALL", "All", true);
	define("IMPORT", "Import", true);
	define("GROSS", "Gross", true);
	define("DUE_DATE", "Due Date", true);
	define("AMOUNT", "Amount", true);
	define("PAID_DATE", "Paid Date", true);
	define("HEADING_ROW_NO", "Heading Row #", true);
	define("ADD_TO_BULK_CREATE_LIST", "Add To Bulk Create List", true);
	define("BULK", "Bulk", true);
	define("STUDENT_NAME", "Student Name", true);
	define("LOGIN_ID", "Login ID", true);
	define("S_NO", "S NO.", true);
	define("EMAIL", "Email", true);
	define("TEXT", "Text", true);
	define("SUBJECT", "Subject", true);
	define("MESSAGE", "Message", true);
	define("SEND", "Send", true);
	define("START", "Start", true);
	define("END", "End", true);
	define("ACCEPTED", "Accepted", true);
	define("MNU_CREATE_STUDENT_LOGIN_DATA_VIEW", "Create Student Login Data View", true);
	define("RUN", "Run", true);
	define("PLEASE_CORRECT_FOLLOWING_ERRORS", "Please Correct The Following Errors", true);
	define("SELECT_REPORT_TYPE", "Select Report Type", true);
	define("DISPLAY_ORDER", "Display Order", true);
	define("TAB_GENERAL", "General", true);
	define("SUMMARY", "Summary", true);
	define("GENERATE", "Generate", true);
	define("SCHOOL", "School", true);
	define("TOTAL_COUNT", "Total Count", true);
	define("MAKE_PAYMENT", "Make Payment", true);
	define("LOGOUT", "Logout", true);
	define("LOGOUT_MESSAGE", "You will be Logged Out due to Inactive Session.<br />Click \"I AM IN\" to Continue", true);
	define("I_AM_IN", "I AM IN", true);
	define("MAKE_PAYMENT_BY_CARD", "Make Payment By Card", true);
	define("UPLOADS", "Uploads", true);
	define("LEAD_UPLOAD", "Lead Upload", true);
	define("RESET_PASSWORD_MESSAGE", "Are you sure you want to reset the password?", true);
	define("INVALID_USER_ID", "Invalid User ID", true);
	define("LOGIN_NOT_FOUND", "Login Not Found", true);
	define("ACCOUNT_BLOCKED", "This Account is Blocked Already", true);
	define("RESET_EMAIL_SENT_TO", "Reset Email Sent To ", true);
	define("EMAIL_ID_NOT_FOUND", "Email ID Not Found", true);
	define("EMAIL_EXISTS", "Email ID Already Exists", true);
}
?>