<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("../language/student.php");

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' || $_SESSION['PK_ROLES'] != 3 ){  
	header("location:../index");
	exit;
}

$page = isset($_POST['page']) ? intval($_POST['page']) : $_SESSION['PAGE'];
$rows = isset($_POST['rows']) ? intval($_POST['rows']) : $_SESSION['rows'];
$sort = isset($_POST['sort']) ? strval($_POST['sort']) : $_SESSION['SORT_FIELD'];  
$order = isset($_POST['order']) ? strval($_POST['order']) : $_SESSION['SORT_ORDER'];

$_SESSION['rows'] 		= $rows;
$_SESSION['PAGE'] 		= $page;
$_SESSION['SORT_FIELD'] = $sort;
$_SESSION['SORT_ORDER'] = $order;

$SEARCH 			 = isset($_REQUEST['SEARCH']) ? mysql_real_escape_string($_REQUEST['SEARCH']) : $_SESSION['SRC_SEARCH'];
$PK_STUDENT_STATUS	 = isset($_REQUEST['PK_STUDENT_STATUS']) ? ($_REQUEST['PK_STUDENT_STATUS']) : $_SESSION['SRC_PK_STUDENT_STATUS'];
$PK_CAMPUS_PROGRAM	 = isset($_REQUEST['PK_CAMPUS_PROGRAM']) ? ($_REQUEST['PK_CAMPUS_PROGRAM']) : $_SESSION['SRC_PK_CAMPUS_PROGRAM'];
$PK_CAMPUS			 = isset($_REQUEST['PK_CAMPUS']) ? ($_REQUEST['PK_CAMPUS']) : $_SESSION['SRC_PK_CAMPUS'];
$PK_FUNDING		 	 = isset($_REQUEST['PK_FUNDING']) ? ($_REQUEST['PK_FUNDING']) : $_SESSION['SRC_PK_FUNDING'];
$PK_TERM_MASTER		 = isset($_REQUEST['PK_TERM_MASTER']) ? ($_REQUEST['PK_TERM_MASTER']) : $_SESSION['SRC_PK_TERM_MASTER'];

$PK_STUDENT_GROUP	= isset($_REQUEST['PK_STUDENT_GROUP']) ? ($_REQUEST['PK_STUDENT_GROUP']) : $_SESSION['SRC_PK_STUDENT_GROUP'];
$PK_COURSE		 	= isset($_REQUEST['PK_COURSE']) ? ($_REQUEST['PK_COURSE']) : $_SESSION['SRC_PK_COURSE'];
$PK_SESSION		 	= isset($_REQUEST['PK_SESSION']) ? ($_REQUEST['PK_SESSION']) : $_SESSION['SRC_PK_SESSION'];

$offset = ($page-1)*$rows;
	
$result = array();
$where = " S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_STUDENT_ACADEMICS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND (INSTRUCTOR = '$_SESSION[PK_EMPLOYEE_MASTER]' OR S_COURSE_OFFERING_ASSISTANT.ASSISTANT = '$_SESSION[PK_EMPLOYEE_MASTER]') AND S_COURSE_OFFERING.PK_COURSE_OFFERING = S_STUDENT_COURSE.PK_COURSE_OFFERING AND S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT  ";

if($SEARCH != '') {
	$sub = "";
	$MOBILE_NO = preg_replace( '/[^0-9]/', '', $SEARCH);
	if($MOBILE_NO != '') {
		$sub = " OR (REPLACE(REPLACE(REPLACE(REPLACE(CELL_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(HOME_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(WORK_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') ";
	}
	
	$where .= " AND (STUDENT_ID like '%$SEARCH%' OR CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) like '%$SEARCH%' $sub OR S_STUDENT_CONTACT.EMAIL like '%$SEARCH%' OR S_STUDENT_CONTACT.EMAIL_OTHER like '%$SEARCH%'  )";
	
	$_SESSION['SRC_SEARCH'] = $SEARCH;
} else {
	$_SESSION['SRC_SEARCH'] = '';
}
	
if(!empty($PK_STUDENT_STATUS) != '') {
	$PK_STUDENT_STATUS1 = implode(",",$PK_STUDENT_STATUS);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS IN ($PK_STUDENT_STATUS1) ";
	$_SESSION['SRC_PK_STUDENT_STATUS'] = $PK_STUDENT_STATUS;
} else {
	$_SESSION['SRC_PK_STUDENT_STATUS'] = '';
}

if(!empty($PK_CAMPUS_PROGRAM) != '') {
	$PK_CAMPUS_PROGRAM1 = implode(",",$PK_CAMPUS_PROGRAM);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM IN ($PK_CAMPUS_PROGRAM1) ";
	$_SESSION['SRC_PK_CAMPUS_PROGRAM'] = $PK_CAMPUS_PROGRAM;
} else {
	$_SESSION['SRC_PK_CAMPUS_PROGRAM'] = '';
}

if(!empty($PK_CAMPUS) != '' || $_SESSION['PK_ROLES'] == 3) {
	if(!empty($PK_CAMPUS) != '') {
		$PK_CAMPUS1 = implode(",",$PK_CAMPUS);
		$where .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS1) ";
		$_SESSION['SRC_PK_CAMPUS'] = $PK_CAMPUS;
	} else {
		$where .= " AND (S_STUDENT_CAMPUS.PK_CAMPUS IN ($_SESSION[PK_CAMPUS],0)  ) ";
		$_SESSION['SRC_PK_CAMPUS'] = '';
	}
}

if(!empty($PK_FUNDING) != '') {
	$PK_FUNDING1 = implode(",",$PK_FUNDING);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_FUNDING IN ($PK_FUNDING1) ";
	$_SESSION['SRC_PK_FUNDING'] = $PK_FUNDING;
} else {
	$_SESSION['SRC_PK_FUNDING'] = '';
}

if(!empty($PK_TERM_MASTER) != '') {
	$PK_TERM_MASTER1 = implode(",",$PK_TERM_MASTER);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_TERM_MASTER IN ($PK_TERM_MASTER1) ";
	$_SESSION['SRC_PK_TERM_MASTER'] = $PK_TERM_MASTER;
} else {
	$_SESSION['SRC_PK_TERM_MASTER'] = '';
}

if(!empty($PK_STUDENT_GROUP) != '') {
	$PK_STUDENT_GROUP1 = implode(",",$PK_STUDENT_GROUP);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP IN ($PK_STUDENT_GROUP1) ";
	$_SESSION['SRC_PK_STUDENT_GROUP'] = $PK_STUDENT_GROUP;
} else {
	$_SESSION['SRC_PK_STUDENT_GROUP'] = '';
}

if(!empty($PK_SESSION) != '') {
	$PK_SESSION1 = implode(",",$PK_SESSION);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_SESSION IN ($PK_SESSION1) ";
	$_SESSION['SRC_PK_SESSION'] = $PK_SESSION;
} else {
	$_SESSION['SRC_PK_SESSION'] = '';
}


$qs = "";
$group_by = " GROUP BY S_STUDENT_MASTER.PK_STUDENT_MASTER ";

$sts = "";
$res_type = $db->Execute("select PK_STUDENT_STATUS from M_STUDENT_STATUS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND ADMISSIONS = 0 ");
while (!$res_type->EOF) {
	if($sts != '')
		$sts .= ',';
		
	$sts .= $res_type->fields['PK_STUDENT_STATUS'];
	
	$res_type->MoveNext();
}
$where .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS IN ($sts) ";

$_SESSION['WHERE'] = $where;

$rs = mysql_query("SELECT DISTINCT(S_STUDENT_MASTER.PK_STUDENT_MASTER) 
FROM 
S_STUDENT_MASTER 
LEFT JOIN S_STUDENT_CONTACT On S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = 1 
, S_STUDENT_ACADEMICS, S_COURSE_OFFERING 
LEFT JOIN S_COURSE_OFFERING_ASSISTANT ON S_COURSE_OFFERING_ASSISTANT.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING 
,S_STUDENT_COURSE, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN M_FUNDING ON M_FUNDING.PK_FUNDING = S_STUDENT_ENROLLMENT.PK_FUNDING 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
WHERE " . $where." ".$group_by)or die(mysql_error());
$row = mysql_fetch_row($rs);
$result["total"] = mysql_num_rows($rs);

$query = "SELECT S_STUDENT_MASTER.PK_STUDENT_MASTER, S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT, CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) AS NAME,  STUDENT_ID, S_TERM_MASTER.BEGIN_DATE,FUNDING, STUDENT_STATUS, CONCAT(M_CAMPUS_PROGRAM.CODE,' - ',M_CAMPUS_PROGRAM.DESCRIPTION) as PROGRAM 
FROM 
S_STUDENT_MASTER 
LEFT JOIN S_STUDENT_CONTACT On S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = 1 
, S_STUDENT_ACADEMICS, S_COURSE_OFFERING 
LEFT JOIN S_COURSE_OFFERING_ASSISTANT ON S_COURSE_OFFERING_ASSISTANT.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING 
,S_STUDENT_COURSE, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN M_FUNDING ON M_FUNDING.PK_FUNDING = S_STUDENT_ENROLLMENT.PK_FUNDING 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
WHERE " . $where." ".$group_by." order by $sort $order " ;
//echo $query;exit;	
$rs = mysql_query($query. " limit $offset,$rows")or die(mysql_error());	
	
$items = array();
while($row = mysql_fetch_array($rs)){

	$row['NAME'] = '<a href="student?id='.$row['PK_STUDENT_MASTER'].'&eid='.$row['PK_STUDENT_ENROLLMENT'].'&t='.$_GET['t'].$qs.'" >'.$row['NAME'].'</a>';

	$CAMPUS = "";
	$res_campus = $db->Execute("SELECT OFFICIAL_CAMPUS_NAME FROM S_CAMPUS, S_STUDENT_CAMPUS WHERE S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS  AND PK_STUDENT_ENROLLMENT = '".$row['PK_STUDENT_ENROLLMENT']."' ");
	while (!$res_campus->EOF) { 
		if($CAMPUS != '')
			$CAMPUS .= ', ';
			
		$CAMPUS .= $res_campus->fields['OFFICIAL_CAMPUS_NAME'];
		$res_campus->MoveNext();
	}
	$row['CAMPUS'] = $CAMPUS;
	
	if($row['BEGIN_DATE'] != '0000-00-00' && $row['BEGIN_DATE'] != '')
		$row['BEGIN_DATE'] = date("m/d/Y",strtotime($row['BEGIN_DATE']));
	else
		$row['BEGIN_DATE'] = '';
	
	$str  = '&nbsp;<a href="student?id='.$row['PK_STUDENT_MASTER'].'&eid='.$row['PK_STUDENT_ENROLLMENT'].'&t='.$_GET['t'].$qs.'" title="'.EDIT.'" class="btn edit-color btn-circle"><i class="far fa-edit"></i> </a>&nbsp;';
	
	$row['ACTION'] = $str;
	
	array_push($items, $row);
}
$result["rows"] = $items;
echo json_encode($result);