<? require_once("../global/config.php"); 
require_once("../language/announcement.php");

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == ''){ 
	header("location:../index");
	exit;
}

$PK_CAMPUS 		 = $_REQUEST['str'];
$PK_ANNOUNCEMENT = $_REQUEST['id'];

if($_SESSION['PK_ROLES'] != 1 && $_SESSION['PK_ROLES'] != 2) {
	$where .= " AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN ($_SESSION[PK_CAMPUS]) ";
}
?>

<div class="col-12 col-sm-6 focused">
	<span class="bar"></span> 
	<label for="PK_EMPLOYEE_MASTER"><?=STAFF?></label>
</div>
<div class="col-12 col-sm-12 form-group " id="PK_CAMPUS_DIV" >
	<select id="PK_EMPLOYEE_MASTER" name="PK_EMPLOYEE_MASTER[]" multiple class="form-control required-entry" >
	<? /*$res_type = $db->Execute("SELECT * FROM (SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER, CONCAT(FIRST_NAME,' ',MIDDLE_NAME,' ',LAST_NAME) AS NAME, EMPLOYEE_ID FROM S_EMPLOYEE_MASTER, S_EMPLOYEE_CAMPUS WHERE S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND  S_EMPLOYEE_MASTER.ACTIVE = 1 AND LOGIN_CREATED = 1 AND S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS) $where 
	UNION 
	SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER, CONCAT(FIRST_NAME,' ',MIDDLE_NAME,' ',LAST_NAME) AS NAME, EMPLOYEE_ID FROM S_EMPLOYEE_MASTER WHERE S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND  S_EMPLOYEE_MASTER.ACTIVE = 1 AND IS_ADMIN = 1)
	as TEMP GROUP BY TEMP.PK_EMPLOYEE_MASTER ORDER BY NAME ASC"); 
	*/
	$res_type = $db->Execute("SELECT * FROM (
		SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER, CONCAT(FIRST_NAME,' ',MIDDLE_NAME,' ',LAST_NAME) AS NAME, EMPLOYEE_ID, '1' as TYPE FROM S_EMPLOYEE_MASTER, S_EMPLOYEE_CAMPUS WHERE S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND  S_EMPLOYEE_MASTER.ACTIVE = 1 AND LOGIN_CREATED = 1 AND S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS) $where 
		UNION 
		SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER, CONCAT(FIRST_NAME,' ',MIDDLE_NAME,' ',LAST_NAME) AS NAME, EMPLOYEE_ID, '2' as TYPE FROM S_EMPLOYEE_MASTER, S_EMPLOYEE_CAMPUS WHERE S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND  S_EMPLOYEE_MASTER.ACTIVE = 1 AND LOGIN_CREATED = 0 AND S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS) $where 
		UNION 
		SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER, CONCAT(FIRST_NAME,' ',MIDDLE_NAME,' ',LAST_NAME) AS NAME, EMPLOYEE_ID, '3' as TYPE FROM S_EMPLOYEE_MASTER, S_EMPLOYEE_CAMPUS WHERE S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND  S_EMPLOYEE_MASTER.ACTIVE = 0 AND S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS) $where 
	) as TEMP GROUP BY TEMP.PK_EMPLOYEE_MASTER ORDER BY TYPE ASC, NAME ASC"); 
	while (!$res_type->EOF) { 
		$selected = '';
		$PK_EMPLOYEE_MASTER = $res_type->fields['PK_EMPLOYEE_MASTER'];
		$res = $db->Execute("select PK_ANNOUNCEMENT_EMPLOYEE FROM Z_ANNOUNCEMENT_EMPLOYEE WHERE PK_EMPLOYEE_MASTER = '$PK_EMPLOYEE_MASTER' AND PK_ANNOUNCEMENT = '$PK_ANNOUNCEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
		if($res->RecordCount() > 0)
			$selected = 'selected'; 
			
		$str = "";
		if($res_type->fields['TYPE'] == 2)
			$str = " (Active/No Login)"; 
		else if($res_type->fields['TYPE'] == 3)
			$str = " (Inactive)"; ?>
		<option value="<?=$PK_EMPLOYEE_MASTER ?>" <?=$selected ?> <? if($res_type->fields['TYPE'] != 1) echo "disabled"; ?> ><?=$res_type->fields['NAME'].$str ?></option>
	<?	$res_type->MoveNext();
	} ?>
	</select>
</div>