<? require_once("../global/config.php"); 

$FA_PK_ENROLLMENT 	= $_REQUEST['FA_PK_ENROLLMENT'];
$ACADEMIC_YEAR		= $_REQUEST['AY'];

$res = $db->Execute("SELECT MONTHS FROM M_CAMPUS_PROGRAM_AY, S_STUDENT_ENROLLMENT WHERE ACADEMIC_YEAR = '$ACADEMIC_YEAR' AND M_CAMPUS_PROGRAM_AY.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM AND PK_STUDENT_ENROLLMENT = '$FA_PK_ENROLLMENT' "); 
echo $res->fields['MONTHS'];