<? require_once("../global/config.php"); 
$PK_COURSE_OFFERING = $_REQUEST['PK_COURSE_OFFERING1'];
$date 				= $_REQUEST['date'];
$PK_STUDENT_MASTER  = $_REQUEST['PK_STUDENT_MASTER'];
//$PK_STUDENT_MASTER = $_REQUEST['PK_STUDENT_MASTER'];
//echo "SELECT S_TIME_CLOCK_PROCESSOR_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL, SCHEDULE_DATE, START_TIME, END_TIME FROM S_TIME_CLOCK_PROCESSOR_DETAIL, S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_TIME_CLOCK_PROCESSOR = '$_REQUEST[batch_id]' AND S_TIME_CLOCK_PROCESSOR_DETAIL.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_TIME_CLOCK_PROCESSOR_DETAIL.PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' AND S_TIME_CLOCK_PROCESSOR_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL = S_COURSE_OFFERING_SCHEDULE_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL AND SCHEDULE_DATE = '$date' GROUP BY S_TIME_CLOCK_PROCESSOR_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL";
if($_SESSION['PK_ACCOUNT']==505)
{

$sql="SELECT PK_COURSE_OFFERING_SCHEDULE_DETAIL, SCHEDULE_DATE, START_TIME, END_TIME FROM S_STUDENT_COURSE, S_COURSE_OFFERING, S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE S_STUDENT_COURSE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_STUDENT_COURSE.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND S_STUDENT_COURSE.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_COURSE_OFFERING.PK_COURSE_OFFERING = S_COURSE_OFFERING_SCHEDULE_DETAIL.PK_COURSE_OFFERING AND SCHEDULE_DATE='".$date."'";

}else{

$sql="SELECT PK_COURSE_OFFERING_SCHEDULE_DETAIL, SCHEDULE_DATE, START_TIME, END_TIME FROM S_STUDENT_COURSE, S_COURSE_OFFERING, S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE S_STUDENT_COURSE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_STUDENT_COURSE.PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND S_COURSE_OFFERING.PK_COURSE_OFFERING='$PK_COURSE_OFFERING' AND S_STUDENT_COURSE.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_COURSE_OFFERING.PK_COURSE_OFFERING = S_COURSE_OFFERING_SCHEDULE_DETAIL.PK_COURSE_OFFERING AND SCHEDULE_DATE='".$date."'";

}
?>
<select name="PK_COURSE_OFFERING_SCHEDULE_DETAIL_<?=$_REQUEST['count_id']?>" id="PK_COURSE_OFFERING_SCHEDULE_DETAIL_<?=$_REQUEST['count_id']?>" class="form-control" onchange="set_validation(this.value,'<?=$_REQUEST['count_id']?>')" >
	<option value=""></option>
	<? $res = $db->Execute($sql);
	while (!$res->EOF) { ?>
		<option value="<?=$res->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL']?>" <? if($res->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL'] == $_REQUEST['def']) echo "selected";?> ><?=date("m/d/Y",strtotime($res->fields['SCHEDULE_DATE'])).' '.date("h:i A",strtotime($res->fields['START_TIME'])).' - '.date("h:i A",strtotime($res->fields['END_TIME'])) ?></option>
	<?	$res->MoveNext();
	} ?>
</select>
