<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("../language/menu.php");
require_once("../language/lead_documents_not_received_with_notes.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_ADMISSION') == 0 && check_access('REPORT_CUSTOM_REPORT') == 0 && check_access('MANAGEMENT_ADMISSION') == 0){
	header("location:../index");
	exit;
}

$cond = "";
$table ="";
$table1 ='';
if($_REQUEST['sid'] != ''){
	$cond 		= " AND S_STUDENT_MASTER.PK_STUDENT_MASTER = '$_REQUEST[sid]' ";
} else {
	$field = "";
	if($_POST['DATE_TYPE'] == '1')
		$field = "REQUESTED_DATE";
	else if($_POST['DATE_TYPE'] == '2')
		$field = "FOLLOWUP_DATE";
	else if($_POST['DATE_TYPE'] == '3')
		$field = "DATE_RECEIVED";
		
	if($_POST['START_DATE'] != '' && $_POST['END_DATE'] != '') {
		$ST = date("Y-m-d",strtotime($_POST['START_DATE']));
		$ET = date("Y-m-d",strtotime($_POST['END_DATE']));
		$cond .= " AND $field BETWEEN '$ST' AND '$ET' ";
	} else if($_POST['START_DATE'] != ''){
		$ST = date("Y-m-d",strtotime($_POST['START_DATE']));
		$cond .= " AND $field >= '$ST' ";
	} else if($_POST['END_DATE'] != ''){
		$ET = date("Y-m-d",strtotime($_POST['END_DATE']));
		$cond .= " AND $field <= '$ET' ";
	}

	if($_POST['PK_EMPLOYEE_MASTER'] != '')
		$cond .= " AND S_STUDENT_DOCUMENTS.PK_EMPLOYEE_MASTER IN ($_POST[PK_EMPLOYEE_MASTER]) ";

	if($_POST['RECEIVED'] == 1)
		$cond .= " AND RECEIVED = 1";
	else if($_POST['RECEIVED'] == 2) // DIAM-1439
		$cond .= " AND RECEIVED = 0";

	if($_POST['PK_DOCUMENT_TYPE'] != '')
		$cond .= " AND S_STUDENT_DOCUMENTS.PK_DOCUMENT_TYPE IN ($_POST[PK_DOCUMENT_TYPE]) ";

	if($_POST['PK_TERM_MASTER'] != '')
		$cond .= " AND S_STUDENT_ENROLLMENT.PK_TERM_MASTER = '$_POST[PK_TERM_MASTER]' ";

		/*//$cond = "";
		$table ="";
		if(!empty($_REQUEST['PK_CAMPUS'])) {
			$table .= ",S_STUDENT_CAMPUS ";
			$cond .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN (".$_REQUEST['PK_CAMPUS'].") AND S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT ";
		}*/
		//DIAM-1439 
		if ($_POST['DOC_DEPARTMENT'] != '') {
			$table1 .= "LEFT JOIN S_STUDENT_DOCUMENTS_DEPARTMENT  ON S_STUDENT_DOCUMENTS_DEPARTMENT.PK_STUDENT_DOCUMENTS = S_STUDENT_DOCUMENTS.PK_STUDENT_DOCUMENTS ";
			$cond .= " AND S_STUDENT_DOCUMENTS_DEPARTMENT.PK_DEPARTMENT IN ($_REQUEST[DOC_DEPARTMENT]) ";
		}
		
		//DIAM-1439 
		if(!empty($_REQUEST['PK_CAMPUS'])) {
			$table .= " LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT";
			$cond .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN (".$_REQUEST['PK_CAMPUS'].")  ";
		}



}
//AND M_STUDENT_STATUS.ADMISSIONS = 1
/*$query = "select PK_STUDENT_DOCUMENTS, CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) AS STU_NAME ,DOCUMENT_TYPE, CONCAT(S_EMPLOYEE_MASTER.FIRST_NAME,' ',S_EMPLOYEE_MASTER.LAST_NAME,' ',S_EMPLOYEE_MASTER.MIDDLE_NAME) AS EMP_NAME, IF(REQUESTED_DATE = '0000-00-00', '',  DATE_FORMAT(REQUESTED_DATE,'%Y-%m-%d')) AS REQUESTED_DATE, S_STUDENT_DOCUMENTS.NOTES, S_STUDENT_MASTER.PK_STUDENT_MASTER, S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT , S_STUDENT_CONTACT.CELL_PHONE ,S_STUDENT_CONTACT.EMAIL, IF(DATE_RECEIVED = '0000-00-00', '',  DATE_FORMAT(DATE_RECEIVED,'%Y-%m-%d')) AS DATE_RECEIVED, IF(FOLLOWUP_DATE = '0000-00-00', '',  DATE_FORMAT(FOLLOWUP_DATE,'%Y-%m-%d')) AS FOLLOWUP_DATE, IF(RECEIVED = 1,'Yes', 'No') as RECEIVED, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%Y-%m-%d' )) AS BEGIN_DATE_1  

FROM 

S_STUDENT_MASTER LEFT JOIN S_STUDENT_CONTACT ON S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = '1'  $table,
S_STUDENT_ENROLLMENT 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
, M_STUDENT_STATUS, S_STUDENT_DOCUMENTS 
LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_STUDENT_DOCUMENTS.PK_EMPLOYEE_MASTER 
WHERE 
S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
S_STUDENT_MASTER.ARCHIVED = 0 AND 
S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND 
S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS = M_STUDENT_STATUS.PK_STUDENT_STATUS AND 
S_STUDENT_MASTER.PK_STUDENT_MASTER  = S_STUDENT_DOCUMENTS.PK_STUDENT_MASTER AND 
S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT  = S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT $cond  
GROUP BY PK_STUDENT_DOCUMENTS  ";*/

$query = "SELECT
S_STUDENT_DOCUMENTS.PK_STUDENT_DOCUMENTS,
CONCAT(
	S_STUDENT_MASTER.LAST_NAME,
	', ',
	S_STUDENT_MASTER.FIRST_NAME
) AS STU_NAME,
DOCUMENT_TYPE,
CONCAT(
	S_EMPLOYEE_MASTER.FIRST_NAME,
	' ',
	S_EMPLOYEE_MASTER.LAST_NAME,
	' ',
	S_EMPLOYEE_MASTER.MIDDLE_NAME
) AS EMP_NAME,
IF(
	REQUESTED_DATE = '0000-00-00',
	'',
	DATE_FORMAT(REQUESTED_DATE, '%Y-%m-%d')
) AS REQUESTED_DATE,
S_STUDENT_DOCUMENTS.NOTES,
S_STUDENT_MASTER.PK_STUDENT_MASTER,
S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT,
S_STUDENT_CONTACT.CELL_PHONE,
S_STUDENT_CONTACT.EMAIL,
IF(
	DATE_RECEIVED = '0000-00-00',
	'',
	DATE_FORMAT(DATE_RECEIVED, '%Y-%m-%d')
) AS DATE_RECEIVED,
IF(
	FOLLOWUP_DATE = '0000-00-00',
	'',
	DATE_FORMAT(FOLLOWUP_DATE, '%Y-%m-%d')
) AS FOLLOWUP_DATE,
IF(RECEIVED = 1, 'Yes', 'No') AS RECEIVED,
IF(
	BEGIN_DATE = '0000-00-00',
	'',
	DATE_FORMAT(BEGIN_DATE, '%Y-%m-%d')
) AS BEGIN_DATE_1
FROM
S_STUDENT_MASTER
LEFT JOIN S_STUDENT_CONTACT ON S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = '1'
LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER 
$table
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER
LEFT JOIN M_STUDENT_STATUS ON S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS = M_STUDENT_STATUS.PK_STUDENT_STATUS 
LEFT JOIN S_STUDENT_DOCUMENTS ON S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_DOCUMENTS.PK_STUDENT_MASTER  AND S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT = S_STUDENT_DOCUMENTS.PK_STUDENT_ENROLLMENT 
LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_STUDENT_DOCUMENTS.PK_EMPLOYEE_MASTER
$table1
WHERE
S_STUDENT_MASTER.PK_ACCOUNT =  '$_SESSION[PK_ACCOUNT]' 
AND S_STUDENT_MASTER.ARCHIVED = 0  AND S_STUDENT_DOCUMENTS.PK_STUDENT_DOCUMENTS IS NOT NULL    
$cond 
GROUP BY S_STUDENT_DOCUMENTS.PK_STUDENT_DOCUMENTS ";
$order_by = " ORDER BY CONCAT(S_STUDENT_MASTER.LAST_NAME,' ',S_STUDENT_MASTER.FIRST_NAME) ASC ";

$_SESSION['document_report_query'] = $query.$order_by;
//echo $query.$group_by.$order_by;
$res_stud = $db->Execute($query.$group_by.$order_by); ?>
<table class="table table-hover" id="student_update_table" width="100%">
	<thead>
		<tr>
			<th width="13%"><?=STUDENT ?></th>
			<th width="15%"><?=EMAIL ?></th>
			<th width="4%"><?=CAMPUS?></th><!-- DIAM-1439 -->
			<th width="11%"><?=FIRST_TERM ?></th>
			<th width="12%"><?=DEPARTMENT ?></th>
			<th width="8%"><?=DOCUMENT ?></th>
			<th width="8%"><?=EMPLOYEE ?></th>
			<th width="11%"><?=REQUESTED ?></th>
			<th width="11%"><?=FOLLOW_UP ?></th>
			<th width="11%" colspan="2">			
				<span style="display:inline-block;width:145px;"><?=TOTAL_COUNT.': '.$res_stud->RecordCount() ?></sapn>
				<br/><br/><?=RECEIVED ?>
			</th>
		</tr>
	</thead>
	<tbody>
	<? while (!$res_stud->EOF) { 
		$PK_STUDENT_DOCUMENTS = $res_stud->fields['PK_STUDENT_DOCUMENTS']; 
		$DEPARTMENT_NAME		= '';
		$res_dep = $db->Execute("SELECT DEPARTMENT FROM S_STUDENT_DOCUMENTS_DEPARTMENT, M_DEPARTMENT WHERE M_DEPARTMENT.PK_DEPARTMENT = S_STUDENT_DOCUMENTS_DEPARTMENT.PK_DEPARTMENT AND PK_STUDENT_DOCUMENTS = '$PK_STUDENT_DOCUMENTS' ORDER BY DEPARTMENT ASC "); 
		while (!$res_dep->EOF) { 
			if($DEPARTMENT_NAME != '')
				$DEPARTMENT_NAME .= ', ';
				
			$DEPARTMENT_NAME .= $res_dep->fields['DEPARTMENT'];
			$res_dep->MoveNext();
		} ?>
		<tr>
			<td >
				<?=$res_stud->fields['STU_NAME']?>
			</td>
			<td >
				<?=$res_stud->fields['EMAIL']?>
			</td>
			<td >
				<? $PK_STUDENT_ENROLLMENT = $res_stud->fields['PK_STUDENT_ENROLLMENT'];
				/*DIAM-1439  */
				$res_camp_1 = $db->Execute("SELECT CAMPUS_CODE, CAMPUS_CODE FROM S_STUDENT_CAMPUS, S_CAMPUS WHERE S_STUDENT_CAMPUS.PK_CAMPUS = S_CAMPUS.PK_CAMPUS AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ");
				echo $res_camp_1->fields['CAMPUS_CODE'];
				/* DIAM-1439 */ ?>
			</td>
			<td >
				<?=$res_stud->fields['BEGIN_DATE_1']?>
			</td>
			<td >
				<?=$DEPARTMENT_NAME ?>
			</td>
			<td >
				<?=$res_stud->fields['DOCUMENT_TYPE']?>
			</td>
			<td >
				<?=$res_stud->fields['EMP_NAME']?>
			</td>
			<td >
				<?=$res_stud->fields['REQUESTED_DATE']?>
			</td>
			<td >
				<?=$res_stud->fields['FOLLOWUP_DATE']?>
			</td>
			<td colspan="2" >
				<?=$res_stud->fields['DATE_RECEIVED']?>
			</td>
		</tr>
		
	<?	$res_stud->MoveNext();
	} ?>
	</tbody>
</table>
