<? require_once("../global/config.php"); 

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' ){ 
	header("location:../index");
	exit;
}

$EMPLOYEE_MASTER['TURN_OFF_ASSIGNMENTS'] = $_REQUEST['TURN_OFF_ASSIGNMENTS_MASTER'];
db_perform('S_EMPLOYEE_MASTER', $EMPLOYEE_MASTER, 'update'," PK_EMPLOYEE_MASTER = '$_SESSION[PK_EMPLOYEE_MASTER]' ");
$_SESSION['TURN_OFF_ASSIGNMENTS'] = $EMPLOYEE_MASTER['TURN_OFF_ASSIGNMENTS'];

echo $_SESSION['TURN_OFF_ASSIGNMENTS'].' -- '." PK_EMPLOYEE_MASTER = '$_SESSION[PK_EMPLOYEE_MASTER]' ";