<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_REGISTRAR') == 0 && $_SESSION['PK_ROLES'] != 3){
	header("location:../index");
	exit;
}

$PK_TERM_MASTER		= $_REQUEST['PK_TERM_MASTER'];
$PK_COURSE_OFFERING	= $_REQUEST['PK_COURSE_OFFERING'];
$CLASS_DATE			= $_REQUEST['CLASS_DATE'];

$SCHEDULE_DATE 		= date("Y-m-d",strtotime($CLASS_DATE));
$ii = 0;
//S_STUDENT_SCHEDULE.SCHEDULE_DATE = '$SCHEDULE_DATE' AND 
/* Ticket # 1459 */

/* Ticket # 1601 */
/*$res_ns = $db->Execute("select PK_STUDENT_ATTENDANCE, SCHEDULE_DATE, START_TIME, END_TIME, HOURS, ATTENDANCE_HOURS, PK_ATTENDANCE_CODE, S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT, S_STUDENT_MASTER.PK_STUDENT_MASTER, S_STUDENT_ATTENDANCE.PK_STUDENT_SCHEDULE, PK_ATTENDANCE_ACTIVITY_TYPESS, ATTENDANCE_COMMENTS   
from 
S_STUDENT_ATTENDANCE, S_STUDENT_SCHEDULE, S_STUDENT_COURSE, S_STUDENT_MASTER, S_STUDENT_ENROLLMENT   
WHERE 
S_STUDENT_ATTENDANCE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND 
S_STUDENT_ATTENDANCE.PK_STUDENT_SCHEDULE  = S_STUDENT_SCHEDULE.PK_STUDENT_SCHEDULE AND 
S_STUDENT_COURSE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' AND 
PK_SCHEDULE_TYPE = 2 AND 
S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_COURSE.PK_STUDENT_MASTER AND 
S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND 
S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND 
S_STUDENT_COURSE.PK_STUDENT_COURSE = S_STUDENT_SCHEDULE.PK_STUDENT_COURSE ORDER BY S_STUDENT_SCHEDULE.SCHEDULE_DATE ASC ");
*/
//DIAM-1967
$res_ns = $db->Execute("SELECT
PK_STUDENT_ATTENDANCE,
SCHEDULE_DATE,
START_TIME,
END_TIME,
HOURS,
ATTENDANCE_HOURS,
PK_ATTENDANCE_CODE,
S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT,
S_STUDENT_MASTER.PK_STUDENT_MASTER,
S_STUDENT_ATTENDANCE.PK_STUDENT_SCHEDULE,
PK_ATTENDANCE_ACTIVITY_TYPESS,
ATTENDANCE_COMMENTS
FROM
S_STUDENT_ATTENDANCE
LEFT JOIN S_STUDENT_SCHEDULE  ON S_STUDENT_ATTENDANCE.PK_STUDENT_SCHEDULE = S_STUDENT_SCHEDULE.PK_STUDENT_SCHEDULE
LEFT JOIN S_STUDENT_COURSE   ON S_STUDENT_COURSE.PK_STUDENT_COURSE = S_STUDENT_SCHEDULE.PK_STUDENT_COURSE
LEFT JOIN S_STUDENT_MASTER ON S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_COURSE.PK_STUDENT_MASTER
LEFT JOIN S_STUDENT_ENROLLMENT ON S_STUDENT_ATTENDANCE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER 
WHERE 
S_STUDENT_COURSE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' AND S_STUDENT_SCHEDULE.PK_SCHEDULE_TYPE = 2  AND S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT  
ORDER BY
S_STUDENT_SCHEDULE.SCHEDULE_DATE ASC");
/* Ticket # 1601 */

/* Ticket # 1459 */
while (!$res_ns->EOF) {
	
	$_REQUEST['stu_id'] = $ii;
	$_REQUEST['PK_STUDENT_ATTENDANCE'] 	= $res_ns->fields['PK_STUDENT_ATTENDANCE'];
	$_REQUEST['PK_STUDENT_SCHEDULE'] 	= $res_ns->fields['PK_STUDENT_SCHEDULE'];
	
	$_REQUEST['PK_STUDENT_ENROLLMENT'] 	= $res_ns->fields['PK_STUDENT_ENROLLMENT'];
	$_REQUEST['START_TIME'] 			= $res_ns->fields['START_TIME'];
	$_REQUEST['END_TIME'] 				= $res_ns->fields['END_TIME'];
	$_REQUEST['HOURS'] 					= $res_ns->fields['HOURS'];
	$_REQUEST['ATTENDANCE_HOURS'] 		= $res_ns->fields['ATTENDANCE_HOURS'];
	$_REQUEST['PK_ATTENDANCE_CODE'] 	= $res_ns->fields['PK_ATTENDANCE_CODE'];
	$_REQUEST['SCHEDULE_DATE'] 			= $res_ns->fields['SCHEDULE_DATE'];
	$_REQUEST['PK_ATTENDANCE_ACTIVITY_TYPE'] = $res_ns->fields['PK_ATTENDANCE_ACTIVITY_TYPESS']; //Ticket # 1459
	$_REQUEST['ATTENDANCE_COMMENTS'] 		 = $res_ns->fields['ATTENDANCE_COMMENTS']; //Ticket # 1601
	
	if($_REQUEST['SCHEDULE_DATE'] == '' || $_REQUEST['SCHEDULE_DATE'] == '0000-00-00')
		$_REQUEST['SCHEDULE_DATE'] = '';
	else
		$_REQUEST['SCHEDULE_DATE'] = date("m/d/Y",strtotime($_REQUEST['SCHEDULE_DATE']));
	
	if($_REQUEST['START_TIME'] == '' || $_REQUEST['START_TIME'] == '00:00:00')
		$_REQUEST['START_TIME'] = '';
	else
		$_REQUEST['START_TIME'] = date("h:i A",strtotime($_REQUEST['START_TIME']));
		
	if($_REQUEST['END_TIME'] == '' || $_REQUEST['END_TIME'] == '00:00:00')
		$_REQUEST['END_TIME'] = '';
	else
		$_REQUEST['END_TIME'] = date("h:i A",strtotime($_REQUEST['END_TIME']));
	
	$_REQUEST['show_date'] = 1;
	
	include('../instructor/ajax_get_student_from_course_offering.php');
	
	$ii++;
	
	$res_ns->MoveNext();
} 
echo "|||".$ii;?>
