<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("function_update_disbursement_status.php");
require_once("function_student_ledger.php");

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' || ($_SESSION['PK_ROLES'] != 2 && $_SESSION['PK_ROLES'] != 3)){  
	header("location:../index");
	exit;
}

$PK_STUDENT_MASTER 		= $_REQUEST['sid'];
$PK_STUDENT_ENROLLMENT 	= $_REQUEST['eid'];
/*
if($_REQUEST['type'] == 1) {
	$APPROVED_DATE = date("Y-m-d");
	// AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' 
	$db->Execute("UPDATE S_STUDENT_DISBURSEMENT SET APPROVED_DATE = '$APPROVED_DATE' WHERE APPROVED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_DISBURSEMENT_STATUS != 2 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND DISBURSEMENT_DATE != '0000-00-00' ");
} else if($_REQUEST['type'] == 2) {
	$APPROVED_DATE = date("Y-m-d");
	//AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT'
	$db->Execute("UPDATE S_STUDENT_DISBURSEMENT SET APPROVED_DATE = '$APPROVED_DATE' WHERE APPROVED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_AR_LEDGER_CODE IN ($_REQUEST[ledger]) AND PK_DISBURSEMENT_STATUS != 2 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND DISBURSEMENT_DATE != '0000-00-00'  ");
} else if($_REQUEST['type'] == 3) {
	$APPROVED_DATE = date("Y-m-d");
	$db->Execute("UPDATE S_STUDENT_DISBURSEMENT SET APPROVED_DATE = '$APPROVED_DATE' WHERE APPROVED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND ACADEMIC_YEAR = '$_REQUEST[AY]' AND PK_DISBURSEMENT_STATUS != 2 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND DISBURSEMENT_DATE != '0000-00-00' ");
} else */

if($_REQUEST['type'] == 4) {
	//delete unpaid award
	$ledger_data_del = array();
	//AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT'
	$res_disb = $db->Execute("SELECT PK_STUDENT_DISBURSEMENT FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'  AND PK_DISBURSEMENT_STATUS IN (0,2) "); 
	while (!$res_disb->EOF) {
		$PK_STUDENT_DISBURSEMENT = $res_disb->fields['PK_STUDENT_DISBURSEMENT'];
		
		$db->Execute("DELETE FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' "); 
		
		$ledger_data_del['PK_STUDENT_DISBURSEMENT'] = $PK_STUDENT_DISBURSEMENT;
		delete_student_ledger($ledger_data_del);
		
		$res_disb->MoveNext();
	}
} else if($_REQUEST['type'] == 5) {
	//unapprove awards
	$ledger_data_del = array();
	//AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT'
	$res_disb = $db->Execute("UPDATE S_STUDENT_DISBURSEMENT SET PK_DISBURSEMENT_STATUS = 0, APPROVED_DATE=''  WHERE PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_DISBURSEMENT_STATUS IN (2) "); 
	
}
update_disbursement_status($PK_STUDENT_MASTER,'');