<? require_once("../global/config.php"); 

$EMPLOYEE_NOTES['PK_ACCOUNT']   		 = $_SESSION['PK_ACCOUNT'];
$EMPLOYEE_NOTES['PK_EMPLOYEE_MASTER'] 	 = $_REQUEST['id'];
$EMPLOYEE_NOTES['PK_EMPLOYEE_NOTE_TYPE'] = $_REQUEST['PK_EMPLOYEE_NOTE_TYPE'];
$EMPLOYEE_NOTES['PK_NOTE_STATUS'] 		 = $_REQUEST['PK_NOTE_STATUS'];
$EMPLOYEE_NOTES['NOTES'] 				 = $_REQUEST['NOTES'];

$EMPLOYEE_NOTES['CREATED_BY']  			= $_SESSION['PK_USER'];
$EMPLOYEE_NOTES['CREATED_ON']  			= date("Y-m-d H:i");
db_perform('S_EMPLOYEE_NOTES', $EMPLOYEE_NOTES, 'insert');