<? require_once("../global/config.php"); 
ENABLE_DEBUGGING(TRUE);
if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' || ($_SESSION['PK_ROLES'] != 2 && $_SESSION['PK_ROLES'] != 3)){  
	header("location:../index");
	exit;
}

$PK_COURSE 		= $_REQUEST['PK_COURSE'];
$PK_TERM_MASTER = $_REQUEST['PK_TERM_MASTER'];
$PK_CAMPUS 		= $_REQUEST['PK_CAMPUS'];
$PK_SESSION 	= $_REQUEST['PK_SESSION'];
$POSTED_SESSION_NO 	= $_REQUEST['SESSION_NO'];
$PK_COURSE_OFFERING_COND = '';
if(isset($_REQUEST['PK_COURSE_OFFERING']) && $_REQUEST['PK_COURSE_OFFERING'] != ''){
	$PK_COURSE_OFFERING = $_REQUEST['PK_COURSE_OFFERING'];
	$PK_COURSE_OFFERING_COND = " AND PK_COURSE_OFFERING != '$PK_COURSE_OFFERING' ";
}


$res = $db->Execute("SELECT * FROM S_COURSE_OFFERING WHERE PK_COURSE = '$PK_COURSE' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_TERM_MASTER = '$PK_TERM_MASTER' /*AND PK_CAMPUS = '$PK_CAMPUS'*/ AND PK_SESSION = '$PK_SESSION' AND SESSION_NO = $POSTED_SESSION_NO $PK_COURSE_OFFERING_COND"); 
if($res->RecordCount() > 0){
	echo "duplicate_found";
}else{
	echo "unique";
}