<? require_once("../global/config.php"); 

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' || ($_SESSION['PK_ROLES'] != 2 && $_SESSION['PK_ROLES'] != 3)){ 
	header("location:../index");
	exit;
}

$PK_COURSE_OFFERING_WAITING_LIST = $_REQUEST['PK_COURSE_OFFERING_WAITING_LIST'];
$db->Execute("DELETE FROM S_COURSE_OFFERING_WAITING_LIST WHERE PK_COURSE_OFFERING_WAITING_LIST = '$PK_COURSE_OFFERING_WAITING_LIST' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'");