<? require_once("../global/config.php"); 

if($_SESSION['PK_USER'] == 0 || $_SESSION['PK_USER'] == '' || ($_SESSION['PK_ROLES'] != 2 && $_SESSION['PK_ROLES'] != 3)){ 
	header("location:../index");
	exit;
}

$PK_COURSE_OFFERING 	= $_REQUEST['PK_COURSE_OFFERING'];
$PK_STUDENT_MASTER 		= $_REQUEST['id'];
$PK_STUDENT_ENROLLMENT 	= $_REQUEST['eid'];

$res = $db->Execute("SELECT PK_COURSE_OFFERING_WAITING_LIST FROM S_COURSE_OFFERING_WAITING_LIST WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_COURSE_OFFERING = '$PK_COURSE_OFFERING'");
if($res->RecordCount() == 0){
	$WAITING_LIST['PK_COURSE_OFFERING'] 	= $PK_COURSE_OFFERING;
	$WAITING_LIST['PK_STUDENT_MASTER'] 		= $PK_STUDENT_MASTER;
	$WAITING_LIST['PK_STUDENT_ENROLLMENT'] 	= $PK_STUDENT_ENROLLMENT;
	$WAITING_LIST['PK_ACCOUNT'] 			= $_SESSION['PK_ACCOUNT'];
	$WAITING_LIST['CREATED_ON'] 			= date("Y-m-d H:i:s");
	$WAITING_LIST['CREATED_BY'] 			= $_SESSION['PK_USER']; 
	db_perform('S_COURSE_OFFERING_WAITING_LIST', $WAITING_LIST, 'insert');
}