<? require_once("../global/config.php"); 
require_once("function_student_ledger.php");
require_once("function_update_disbursement_status.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_ACCOUNTING') == 0 ){
	header("location:../index");
	exit;
}

$PK_PAYMENT_BATCH_DETAIL = $_REQUEST['id'];
$res_det = $db->Execute("select PK_STUDENT_DISBURSEMENT,PK_BATCH_STATUS, S_PAYMENT_BATCH_DETAIL.PK_PAYMENT_BATCH_MASTER from S_PAYMENT_BATCH_DETAIL LEFT JOIN S_PAYMENT_BATCH_MASTER ON S_PAYMENT_BATCH_MASTER.PK_PAYMENT_BATCH_MASTER = S_PAYMENT_BATCH_DETAIL.PK_PAYMENT_BATCH_MASTER WHERE S_PAYMENT_BATCH_DETAIL.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL'");
$PK_STUDENT_DISBURSEMENT = $res_det->fields['PK_STUDENT_DISBURSEMENT'];
$PK_BATCH_STATUS 		 = $res_det->fields['PK_BATCH_STATUS'];
$PK_PAYMENT_BATCH_MASTER = $res_det->fields['PK_PAYMENT_BATCH_MASTER'];

if($PK_BATCH_STATUS == 1 || $PK_BATCH_STATUS == 3) {
	$db->Execute("DELETE FROM S_PAYMENT_BATCH_DETAIL WHERE PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 		
	$ledger_data_del['PK_PAYMENT_BATCH_DETAIL'] = $PK_PAYMENT_BATCH_DETAIL;
	delete_student_ledger($ledger_data_del);
	
	$STUDENT_DISBURSEMENT['PK_PAYMENT_BATCH_DETAIL'] = '';
	$STUDENT_DISBURSEMENT['DEPOSITED_DATE'] 		 = '';
	db_perform('S_STUDENT_DISBURSEMENT', $STUDENT_DISBURSEMENT, 'update'," PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' ");
	
	$res_disb = $db->Execute("select PK_STUDENT_MASTER, PK_STUDENT_ENROLLMENT from S_STUDENT_DISBURSEMENT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' ");
	update_disbursement_status($res_disb->fields['PK_STUDENT_MASTER'],$res_disb->fields['PK_STUDENT_ENROLLMENT']);
	
	if($_SESSION['DISB_ID'] != ''){
		$DISB_ARR = explode(",",$_SESSION['DISB_ID']);
		$str = "";
		foreach($DISB_ARR as $DISB1){
			if($DISB1 != $PK_STUDENT_DISBURSEMENT){
				if($str != '')
					$str .= ',';
				$str .= $DISB1;
			}
		}
	}
	
	$res_det = $db->Execute("select SUM(RECEIVED_AMOUNT) as TOTAL_AMOUNT from S_PAYMENT_BATCH_DETAIL WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' ");
	$TOTAL_AMOUNT = $res_det->fields['TOTAL_AMOUNT'];
	$db->Execute("UPDATE S_PAYMENT_BATCH_MASTER SET AMOUNT = '$TOTAL_AMOUNT' WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' ");
}