<? require_once("../global/config.php");

$PK_STUDENT_ENROLLMENT = $_REQUEST['eid'];
$res = $db->Execute("call REGR10101('Graduation100', ".$PK_STUDENT_ENROLLMENT.", 'DATE')");

if($res->fields['CALCULATED_DATE'] != '' && $res->fields['CALCULATED_DATE'] != '0000-00-00') {
	//$db->Execute("UPDATE S_STUDENT_ENROLLMENT SET EXPECTED_GRAD_DATE = '".$res->fields['CALCULATED_DATE']."' WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_ENROLLMENT > 0");
	//$db->Execute("UPDATE S_STUDENT_ENROLLMENT SET ORIGINAL_EXPECTED_GRAD_DATE = '".$res->fields['CALCULATED_DATE']."' WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND (ORIGINAL_EXPECTED_GRAD_DATE = '' OR ORIGINAL_EXPECTED_GRAD_DATE = '0000-00-00') AND PK_STUDENT_ENROLLMENT > 0 ");
	
	echo date("m/d/Y", strtotime($res->fields['CALCULATED_DATE']));
} else
	echo "";