<? require_once("../global/config.php"); 
require_once("function_student_ledger.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_ACCOUNTING') == 0 ){
	header("location:../index");
	exit;
}

$PK_PAYMENT_BATCH_DETAIL 	= $_REQUEST['id'];
$PAID_AMOUNT 				= $_REQUEST['PAID_AMOUNT'];
$DISBURSEMENT_TYPE 			= $_REQUEST['DISBURSEMENT_TYPE'];
$PRIOR_YEAR 				= $_REQUEST['PRIOR_YEAR'];

$res_det = $db->Execute("SELECT RECEIVED_AMOUNT,PK_STUDENT_DISBURSEMENT FROM S_PAYMENT_BATCH_DETAIL WHERE PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
if($res_det->RecordCount() > 0) {
	$OLD_AMOUNT 			 = $res_det->fields['RECEIVED_AMOUNT'];
	$PK_STUDENT_DISBURSEMENT = $res_det->fields['PK_STUDENT_DISBURSEMENT'];
	
	$db->Execute("UPDATE S_PAYMENT_BATCH_DETAIL SET RECEIVED_AMOUNT='$PAID_AMOUNT', PRIOR_YEAR='$PRIOR_YEAR' WHERE PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' ");
	$db->Execute("UPDATE S_STUDENT_LEDGER SET CREDIT = '$PAID_AMOUNT' WHERE PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' "); 
	$db->Execute("UPDATE S_STUDENT_DISBURSEMENT SET DISBURSEMENT_AMOUNT = '$PAID_AMOUNT' WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	
	if($DISBURSEMENT_TYPE == 1){
		$res_disb_1 = $db->Execute("SELECT * FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		
		$STUDENT_DISBURSEMENT1['PK_AR_LEDGER_CODE'] 	 = $res_disb_1->fields['PK_AR_LEDGER_CODE'];
		$STUDENT_DISBURSEMENT1['ACADEMIC_YEAR'] 		 = $res_disb_1->fields['ACADEMIC_YEAR'];
		$STUDENT_DISBURSEMENT1['ACADEMIC_PERIOD'] 		 = $res_disb_1->fields['ACADEMIC_PERIOD'];
		$STUDENT_DISBURSEMENT1['DISBURSEMENT_DATE'] 	 = $res_disb_1->fields['DISBURSEMENT_DATE'];
		$STUDENT_DISBURSEMENT1['DISBURSEMENT_AMOUNT'] 	 = $OLD_AMOUNT - $PAID_AMOUNT;
		$STUDENT_DISBURSEMENT1['PK_AWARD_YEAR'] 		 = $res_disb_1->fields['PK_AWARD_YEAR'];
		$STUDENT_DISBURSEMENT1['APPROVED_DATE'] 		 = $res_disb_1->fields['APPROVED_DATE'];
		$STUDENT_DISBURSEMENT1['DEPOSITED_DATE'] 		 = $res_disb_1->fields['DEPOSITED_DATE'];
		$STUDENT_DISBURSEMENT1['HOURS_REQUIRED'] 		 = $res_disb_1->fields['HOURS_REQUIRED'];
		$STUDENT_DISBURSEMENT1['PK_TERM_BLOCK'] 		 = $res_disb_1->fields['PK_TERM_BLOCK'];
		$STUDENT_DISBURSEMENT1['PK_DETAIL_TYPE'] 		 = $res_disb_1->fields['PK_DETAIL_TYPE'];
		$STUDENT_DISBURSEMENT1['DETAIL'] 				 = $res_disb_1->fields['DETAIL'];
		$STUDENT_DISBURSEMENT1['FUNDS_REQUESTED'] 		 = $res_disb_1->fields['FUNDS_REQUESTED'];
		$STUDENT_DISBURSEMENT1['COMMENTS'] 				 = $res_disb_1->fields['COMMENTS'];
		$STUDENT_DISBURSEMENT1['PK_STUDENT_ENROLLMENT']  = $res_disb_1->fields['PK_STUDENT_ENROLLMENT'];
		$STUDENT_DISBURSEMENT1['PK_STUDENT_MASTER'] 	 = $res_disb_1->fields['PK_STUDENT_MASTER'];
		$STUDENT_DISBURSEMENT1['PK_ACCOUNT'] 			 = $_SESSION['PK_ACCOUNT'];
		$STUDENT_DISBURSEMENT1['CREATED_BY']  			 = $_SESSION['PK_USER'];
		$STUDENT_DISBURSEMENT1['CREATED_ON']  			 = date("Y-m-d H:i");
		db_perform('S_STUDENT_DISBURSEMENT', $STUDENT_DISBURSEMENT1, 'insert');
	}
}