<? require_once("../global/config.php");

$PK_STUDENT_ENROLLMENT = $_REQUEST['eid'];
	
$res_present_att_code = $db->Execute("select GROUP_CONCAT(M_ATTENDANCE_CODE.PK_ATTENDANCE_CODE) as PK_ATTENDANCE_CODE from M_ATTENDANCE_CODE, S_ATTENDANCE_CODE WHERE M_ATTENDANCE_CODE.ACTIVE = 1 AND S_ATTENDANCE_CODE.PK_ATTENDANCE_CODE = M_ATTENDANCE_CODE.PK_ATTENDANCE_CODE AND S_ATTENDANCE_CODE.ACTIVE = 1 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PRESENT = 1");
$present_att_code = $res_present_att_code->fields['PK_ATTENDANCE_CODE'];
		
$res_sch = $db->Execute("select MAX(SCHEDULE_DATE) as SCHEDULE_DATE FROM S_STUDENT_SCHEDULE, S_STUDENT_ATTENDANCE WHERE S_STUDENT_SCHEDULE.PK_STUDENT_SCHEDULE = S_STUDENT_ATTENDANCE.PK_STUDENT_SCHEDULE AND S_STUDENT_SCHEDULE.PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND S_STUDENT_SCHEDULE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_ATTENDANCE_CODE IN ($present_att_code) AND S_STUDENT_ATTENDANCE.COMPLETED = 1");
if($res_sch->fields['SCHEDULE_DATE'] != '' && $res_sch->fields['SCHEDULE_DATE'] != '0000-00-00' )
	echo date("m/d/Y",strtotime($res_sch->fields['SCHEDULE_DATE']));
else
	echo "";