<? require_once("../global/config.php");
require_once("../language/common.php");
require_once("../language/menu.php");
require_once("../language/student_balance.php");
require_once("check_access.php");

if (check_access('REPORT_ACCOUNTING') == 0) {
	header("location:../index");
	exit;
}
$cond = "";

if (!empty($_REQUEST['PK_CAMPUS'])) {
	$cond .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN (" . $_REQUEST['PK_CAMPUS'] . ") ";
}
//echo $cond;

$PK_STUDENT_STATUS1 = "";
if (!empty($_REQUEST['PK_STUDENT_STATUS'])) {
	$PK_STUDENT_STATUS1 = $_REQUEST['PK_STUDENT_STATUS'];
}

if ($_REQUEST['INCLUDE_ALL_LEADS'] == 1) {
	if ($PK_STUDENT_STATUS1 != '') {
		$res_type = $db->Execute("select PK_STUDENT_STATUS from M_STUDENT_STATUS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND ACTIVE = 1 AND ADMISSIONS = 1");
		while (!$res_type->EOF) {
			if ($PK_STUDENT_STATUS1 != '')
				$PK_STUDENT_STATUS1 .= ',';
			$PK_STUDENT_STATUS1 .= $res_type->fields['PK_STUDENT_STATUS'];
			$res_type->MoveNext();
		}
	}
} else {
	if ($PK_STUDENT_STATUS1 == '')
		$cond .= " AND M_STUDENT_STATUS.ADMISSIONS = 0 ";
}
if ($PK_STUDENT_STATUS1 != '')
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS IN (" . $PK_STUDENT_STATUS1 . ") ";

if (!empty($_REQUEST['PK_CAMPUS_PROGRAM'])) {
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM in (" . $_REQUEST['PK_CAMPUS_PROGRAM'] . ") ";
}

if (!empty($_REQUEST['PK_TERM_MASTER'])) {
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_TERM_MASTER in (" . $_REQUEST['PK_TERM_MASTER'] . ") ";
}

if (!empty($_REQUEST['PK_STUDENT_GROUP']))
	$cond .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP IN (" . $_REQUEST['PK_STUDENT_GROUP'] . ") ";

/* Ticket # 1552 */
if ($_REQUEST['SEARCH_TXT'] != '') {
	$cond .= " AND (CONCAT(TRIM(S_STUDENT_MASTER.LAST_NAME),', ', TRIM(S_STUDENT_MASTER.FIRST_NAME)) LIKE '$_REQUEST[SEARCH_TXT]%' OR  TRIM(S_STUDENT_MASTER.FIRST_NAME) LIKE '$_REQUEST[SEARCH_TXT]%' OR  TRIM(S_STUDENT_MASTER.LAST_NAME) LIKE '$_REQUEST[SEARCH_TXT]%' ) ";
}
/* Ticket # 1552 */

$HAVING = "";
if ($_REQUEST['REPORT_OPTIONS'] == 2)
	$HAVING = " HAVING BALANCE > 0 ";
else if ($_REQUEST['REPORT_OPTIONS'] == 3)
	$HAVING = " HAVING BALANCE = 0 ";
else if ($_REQUEST['REPORT_OPTIONS'] == 4)
	$HAVING = " HAVING BALANCE < 0 ";
else if ($_REQUEST['REPORT_OPTIONS'] == 5)
	$HAVING = " HAVING BALANCE != 0 ";
else if ($_REQUEST['REPORT_OPTIONS'] == 6)
	$HAVING = " HAVING BALANCE >= 0 ";
else if ($_REQUEST['REPORT_OPTIONS'] == 7)
	$HAVING = " HAVING BALANCE <= 0 ";

$PK_STUDENT_MASTER_ARR = array();

//DIAM1469
$table  = ' LEFT JOIN S_STUDENT_LEDGER ON S_STUDENT_LEDGER.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT';
//DIAM1469

/*
$res_stud = $db->Execute("select S_STUDENT_MASTER.PK_STUDENT_MASTER, CONCAT(LAST_NAME,', ',FIRST_NAME) as STU_NAME, SUM(DEBIT) as DEBIT, SUM(CREDIT) as CREDIT, (SUM(DEBIT) - SUM(CREDIT)) as BALANCE, STUDENT_STATUS, M_CAMPUS_PROGRAM.CODE, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS  BEGIN_DATE_1
from 
S_STUDENT_MASTER, S_STUDENT_ENROLLMENT 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
, S_STUDENT_LEDGER $table  
WHERE 
S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER AND 
S_STUDENT_LEDGER.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND 
S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
(S_STUDENT_LEDGER.PK_PAYMENT_BATCH_DETAIL > 0 OR PK_MISC_BATCH_DETAIL > 0 OR PK_TUITION_BATCH_DETAIL > 0 ) $cond 
GROUP BY S_STUDENT_MASTER.PK_STUDENT_MASTER $HAVING 
ORDER BY CONCAT(LAST_NAME,', ',FIRST_NAME) "); */

//DIAM1469
/*$res_stud = $db->Execute("select S_STUDENT_MASTER.PK_STUDENT_MASTER, CONCAT(LAST_NAME,', ',FIRST_NAME) as STU_NAME, STUDENT_STATUS, M_CAMPUS_PROGRAM.CODE, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS  BEGIN_DATE_1, STUDENT_ID, CAMPUS_CODE, STUDENT_GROUP,IFNULL((SUM(DEBIT) - SUM(CREDIT)),0) as BALANCE 
from 
S_STUDENT_ENROLLMENT 
LEFT JOIN M_STUDENT_GROUP ON M_STUDENT_GROUP.PK_STUDENT_GROUP = S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT  
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS  
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
$table, S_STUDENT_MASTER, S_STUDENT_ACADEMICS
WHERE 
S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER AND 
S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_ACADEMICS.PK_STUDENT_MASTER AND 
S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' $cond 
GROUP BY S_STUDENT_MASTER.PK_STUDENT_MASTER $HAVING 
ORDER BY CONCAT(LAST_NAME,', ',FIRST_NAME) ");*/
//DIAM-2148
$ledger_cond = " AND S_STUDENT_LEDGER.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER ";
$cond 		.= "";
// $cond 		.= " AND IS_ACTIVE_ENROLLMENT = 1 ";
$group_by = " S_STUDENT_LEDGER.PK_STUDENT_MASTER ";

$query = "select S_STUDENT_MASTER.PK_STUDENT_MASTER, CONCAT(LAST_NAME,', ',FIRST_NAME) as STU_NAME, STUDENT_STATUS, M_CAMPUS_PROGRAM.CODE, IF(BEGIN_DATE = '0000-00-00','',DATE_FORMAT(BEGIN_DATE, '%m/%d/%Y' )) AS  BEGIN_DATE_1, STUDENT_ID, CAMPUS_CODE, STUDENT_GROUP,IFNULL((SUM(DEBIT) - SUM(CREDIT)),0) as BALANCE      
from 
S_STUDENT_MASTER 
LEFT JOIN S_STUDENT_ACADEMICS ON S_STUDENT_ACADEMICS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER 
, S_STUDENT_ENROLLMENT
LEFT JOIN M_STUDENT_GROUP ON M_STUDENT_GROUP.PK_STUDENT_GROUP = S_STUDENT_ENROLLMENT.PK_STUDENT_GROUP 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT  
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS 
LEFT JOIN M_STUDENT_STATUS On M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_STUDENT_ENROLLMENT.PK_TERM_MASTER 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_FUNDING ON M_FUNDING.PK_FUNDING = S_STUDENT_ENROLLMENT.PK_FUNDING 
, S_STUDENT_LEDGER 
WHERE 
S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER AND 
S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND 
S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT IN (SELECT PK_STUDENT_ENROLLMENT FROM S_STUDENT_CAMPUS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]') AND
(S_STUDENT_LEDGER.PK_PAYMENT_BATCH_DETAIL > 0 OR PK_MISC_BATCH_DETAIL > 0 OR PK_TUITION_BATCH_DETAIL > 0 ) $cond $ledger_cond 
GROUP BY $group_by $HAVING ORDER BY CONCAT(LAST_NAME,', ',FIRST_NAME, ' ',S_STUDENT_MASTER.MIDDLE_NAME) ";

$res_stud = $db->Execute($query);
//DIAM-2148
//Ticket #1149 
?>

<table class="table table-hover" id="student_update_table">
	<thead>
		<tr>
			<? if ($_REQUEST['show_count'] == 1) { ?>
				<th>
					<input type="checkbox" name="SEARCH_SELECT_ALL" id="SEARCH_SELECT_ALL" value="1" onclick="fun_select_all()" />
				</th>
			<? } ?>
			<th><?= STUDENT ?></th>
			<th><?= STUDENT_ID ?></th>
			<th><?= CAMPUS ?></th>
			<th><?= FIRST_TERM ?></th>
			<th><?= PROGRAM ?></th>
			<th><?= STATUS ?></th>
			<th><?= STUDENT_GROUP ?></th>
			<th>
				<?= TOTAL_COUNT . ': ' . $res_stud->RecordCount() ?>
				<? if ($_REQUEST['show_count'] == 1) { ?>
					<br /><?= SELECTED_COUNT . ': ' ?><span id="SELECTED_COUNT"></span>
				<? } ?>
			</th>
		</tr>
	</thead>
	<tbody>
		<? while (!$res_stud->EOF) { ?>
			<tr>
				<? if ($_REQUEST['show_count'] == 1) { ?>
					<td>
						<input type="checkbox" name="PK_STUDENT_MASTER[]" id="PK_STUDENT_MASTER_<?= $res_stud->fields['PK_STUDENT_MASTER'] ?>" value="<?= $res_stud->fields['PK_STUDENT_MASTER'] ?>" onclick="get_count()" />
					</td>
				<? } ?>
				<td>
					<? if ($_REQUEST['show_count'] != 1) { ?>
						<input type="hidden" name="PK_STUDENT_MASTER[]" value="<?= $res_stud->fields['PK_STUDENT_MASTER'] ?>">
					<? } ?>

					<?= $res_stud->fields['STU_NAME'] ?>
				</td>
				<td>
					<?= $res_stud->fields['STUDENT_ID'] ?>
				</td>
				<td>
					<?= $res_stud->fields['CAMPUS_CODE'] ?>
				</td>
				<td>
					<?= $res_stud->fields['BEGIN_DATE_1'] ?>
				</td>
				<td>
					<?= $res_stud->fields['CODE'] ?>
				</td>
				<td>
					<?= $res_stud->fields['STUDENT_STATUS'] ?>
				</td>
				<td colspan="2">
					<?= $res_stud->fields['STUDENT_GROUP'] ?>
				</td>

			</tr>

		<? $res_stud->MoveNext();
		} ?>
	</tbody>
</table>