<?php
$page="batch_payment_post";
if($_GET['id'] == ''){
	$res_acc = $db->Execute("SELECT PAYMENT_BATCH_NO FROM Z_ACCOUNT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
	$PAYMENT_BATCH_MASTER['BATCH_NO'] 			= 'P'.$res_acc->fields['PAYMENT_BATCH_NO'];
	$PAYMENT_BATCH_MASTER['PK_ACCOUNT']  		= $_SESSION['PK_ACCOUNT'];
	$PAYMENT_BATCH_MASTER['CREATED_BY']  		= $_SESSION['PK_USER'];
	$PAYMENT_BATCH_MASTER['CREATED_ON']  		= date("Y-m-d H:i");
	$where_duplicate="";
		$j=0;
		foreach($PAYMENT_BATCH_MASTER as $key=>$val){
			if($val!="" && $key!="CREATED_ON" &&  $key!="BATCH_NO"){
				$where_duplicate .= ($j==0?'':'AND')." ".$key."='".$val."'";
				$j++;
			}
		}
	//double check the logic for duplicate batch
	$res_duplicate_check= $db->Execute("SELECT PK_PAYMENT_BATCH_MASTER FROM S_PAYMENT_BATCH_MASTER WHERE $where_duplicate "); 		
	if($res_duplicate_check->RecordCount()==0){
		db_perform('S_PAYMENT_BATCH_MASTER', $PAYMENT_BATCH_MASTER, 'insert');
		$PK_PAYMENT_BATCH_MASTER = $db->insert_ID();
		
		$NEW_BATCH_NO = $res_acc->fields['PAYMENT_BATCH_NO'] + 1;
		$db->Execute("UPDATE Z_ACCOUNT SET PAYMENT_BATCH_NO = '$NEW_BATCH_NO' WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 

	}else{
		$PK_PAYMENT_BATCH_MASTER = $res_duplicate_check->fields['PK_PAYMENT_BATCH_MASTER'];		
		/* Ticket # 1670  */
		$res = $db->Execute("SELECT DATE_RECEIVED, PK_BATCH_STATUS FROM S_PAYMENT_BATCH_MASTER WHERE PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'"); 
		$old_PK_BATCH_STATUS = $res->fields['PK_BATCH_STATUS'];
		
		if($old_PK_BATCH_STATUS != 2) {
			$PAYMENT_BATCH_MASTER['EDITED_BY'] = $_SESSION['PK_USER'];
			$PAYMENT_BATCH_MASTER['EDITED_ON'] = date("Y-m-d H:i");
			db_perform('S_PAYMENT_BATCH_MASTER', $PAYMENT_BATCH_MASTER, 'update'," PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT='$_SESSION[PK_ACCOUNT]' ");
		}

	}
} else {


	$PK_PAYMENT_BATCH_MASTER = $_GET['id'];
	
	/* Ticket # 1670  */
	$res = $db->Execute("SELECT DATE_RECEIVED, PK_BATCH_STATUS FROM S_PAYMENT_BATCH_MASTER WHERE PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'"); 
	$old_PK_BATCH_STATUS = $res->fields['PK_BATCH_STATUS'];
	// unpost batch tracking DIAM-993
	if($old_PK_BATCH_STATUS==3){
		payment_unpost_batch_history($PK_PAYMENT_BATCH_MASTER,$PAYMENT_BATCH_MASTER);
	}
	if($old_PK_BATCH_STATUS != 2) {
		$PAYMENT_BATCH_MASTER['EDITED_BY'] = $_SESSION['PK_USER'];
		$PAYMENT_BATCH_MASTER['EDITED_ON'] = date("Y-m-d H:i");
	
		db_perform('S_PAYMENT_BATCH_MASTER', $PAYMENT_BATCH_MASTER, 'update'," PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT='$_SESSION[PK_ACCOUNT]' ");
		
		if($res->RecordCount() > 0){
			if($res->fields['DATE_RECEIVED'] != $PAYMENT_BATCH_MASTER['DATE_RECEIVED']) {
				//$db->Execute("UPDATE S_STUDENT_LEDGER SET TRANSACTION_DATE = '$PAYMENT_BATCH_MASTER[DATE_RECEIVED]' WHERE PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' AND PK_ACCOUNT='$_SESSION[PK_ACCOUNT]' "); 
			}
		}
	}
	/* Ticket # 1670  */
}


if($PK_PAYMENT_BATCH_MASTER != "" && $old_PK_BATCH_STATUS!=2) { 
	
	$res = $db->Execute("SELECT PK_BATCH_STATUS FROM S_PAYMENT_BATCH_MASTER WHERE PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
	$PAYMENT_BATCH_MASTER['PK_BATCH_STATUS'] = $res->fields['PK_BATCH_STATUS'];
	logpaymentbatch('post disbursement students',json_encode($_POST['PK_STUDENT_DISBURSEMENT']));
	// $reverified=explode(',',$_POST['disbusement_students']);
	// if(count($reverified)!=count($_POST['PK_STUDENT_DISBURSEMENT'])){
	// 	$new_arr=array_merge($reverified,$_POST['PK_STUDENT_DISBURSEMENT']);
	// 	$_POST['PK_STUDENT_DISBURSEMENT']=array_unique($new_arr);
	// }
	foreach($_POST['PK_STUDENT_DISBURSEMENT'] as $PK_STUDENT_DISBURSEMENT){
		
		$res_disb = $db->Execute("SELECT PK_STUDENT_MASTER, PK_STUDENT_ENROLLMENT, PK_AR_LEDGER_CODE FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 

		/* DIAM-737 */
		if($res_disb->fields['PK_STUDENT_ENROLLMENT'] != $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT]) 
		{
			$PK_STUDENT_ENROLLMENT_ID 	= $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT];
		}
		else{
			$PK_STUDENT_ENROLLMENT_ID 	= $res_disb->fields['PK_STUDENT_ENROLLMENT'];
		}
		/* End DIAM-737 */
		
		$PAYMENT_BATCH_DETAIL = array();
		
		
		$res_bat = $db->Execute("SELECT RECEIPT_NO FROM Z_ACCOUNT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		$RECEIPT_NO = $res_bat->fields['RECEIPT_NO'];
		
		$RECEIPT_NO1 = $RECEIPT_NO + 1;
		$db->Execute("UPDATE Z_ACCOUNT SET RECEIPT_NO = '$RECEIPT_NO1' WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		
		$PAYMENT_BATCH_DETAIL['PK_BATCH_PAYMENT_STATUS'] = 3;
		
		
		$PAYMENT_BATCH_DETAIL['RECEIPT_NO'] 				= $RECEIPT_NO;
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_MASTER']  		= $res_disb->fields['PK_STUDENT_MASTER'];
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_ENROLLMENT']  	= $PK_STUDENT_ENROLLMENT_ID;
		$PAYMENT_BATCH_DETAIL['PK_PAYMENT_BATCH_MASTER']  	= $PK_PAYMENT_BATCH_MASTER;
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_DISBURSEMENT']  	= $PK_STUDENT_DISBURSEMENT;
		$PAYMENT_BATCH_DETAIL['DUE_AMOUNT']  				= $_POST['DISBURSEMENT_AMOUNT_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE']  	= $_POST['BATCH_TRANSACTION_DATE_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT']  			= $_POST['PAID_AMOUNT_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PRIOR_YEAR']  				= $_POST['PRIOR_YEAR_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PK_TERM_BLOCK']  			= $_POST['PK_TERM_BLOCK_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['CHECK_NO']  					= $_POST['STUD_CHECK_NO_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['BATCH_DETAIL_DESCRIPTION']  	= $_POST['BATCH_DETAIL_DESCRIPTION_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PK_ACCOUNT']  				= $_SESSION['PK_ACCOUNT'];
		$PAYMENT_BATCH_DETAIL['CREATED_BY']  				= $_SESSION['PK_USER'];
		$PAYMENT_BATCH_DETAIL['CREATED_ON']  				= date("Y-m-d H:i");
		
		if($PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE'] != '')
		{
			$PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE'] = date("Y-m-d",strtotime($PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE']));
		}
		
		if($PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'] != $PAYMENT_BATCH_DETAIL['DUE_AMOUNT'])
		{
			$PAYMENT_BATCH_DETAIL['DISBURSEMENT_TYPE'] = $_POST['DISBURSEMENT_TYPE_'.$PK_STUDENT_DISBURSEMENT];
		}

		//print_r($_POST['PK_PAYMENT_BATCH_DETAIL_'.$PK_STUDENT_DISBURSEMENT]);exit;
		if($_POST['PK_PAYMENT_BATCH_DETAIL_'.$PK_STUDENT_DISBURSEMENT] == '') {
			$res_batch_det = $db->Execute("SELECT PK_PAYMENT_BATCH_DETAIL FROM S_PAYMENT_BATCH_DETAIL WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' "); 
			
			if($res_batch_det->RecordCount() == 0) {
				db_perform('S_PAYMENT_BATCH_DETAIL', $PAYMENT_BATCH_DETAIL, 'insert');
				$PK_PAYMENT_BATCH_DETAIL = $db->insert_ID();
			} else {
				$PK_PAYMENT_BATCH_DETAIL = $res_batch_det->fields['PK_PAYMENT_BATCH_DETAIL'];				
			}			
			$PK_PAYMENT_BATCH_DETAIL_ARR[] = $PK_PAYMENT_BATCH_DETAIL;

		} else {
			$PK_PAYMENT_BATCH_DETAIL = $_POST['PK_PAYMENT_BATCH_DETAIL_'.$PK_STUDENT_DISBURSEMENT];
			// unpost batch tracking DIAM-993
			if($old_PK_BATCH_STATUS==3){
				payment_unpost_batch_history($PK_PAYMENT_BATCH_MASTER,$PAYMENT_BATCH_DETAIL,$PK_PAYMENT_BATCH_DETAIL);
			}
			db_perform('S_PAYMENT_BATCH_DETAIL', $PAYMENT_BATCH_DETAIL, 'update'," PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' ");
			
			$PK_PAYMENT_BATCH_DETAIL_ARR[] = $PK_PAYMENT_BATCH_DETAIL;			
		}

		if($PAYMENT_BATCH_MASTER['PK_BATCH_STATUS'] == 2) {
			$STUDENT_DISBURSEMENT = array();
			$STUDENT_DISBURSEMENT['PK_PAYMENT_BATCH_DETAIL'] = $PK_PAYMENT_BATCH_DETAIL;
			//$STUDENT_DISBURSEMENT['DEPOSITED_DATE'] 		 = $PAYMENT_BATCH_MASTER['DATE_RECEIVED'];
			$STUDENT_DISBURSEMENT['DEPOSITED_DATE'] 		 = date("Y-m-d", strtotime($_POST['BATCH_TRANSACTION_DATE_'.$PK_STUDENT_DISBURSEMENT])); //DIAM-1158
			$STUDENT_DISBURSEMENT['PK_DETAIL_TYPE']  		 = 4; 
			$STUDENT_DISBURSEMENT['DETAIL']  				 = $_POST['DISBURSEMENT_DETAIL_'.$PK_STUDENT_DISBURSEMENT];
			
			$res_disb_1 = $db->Execute("SELECT PK_TERM_BLOCK,PK_STUDENT_ENROLLMENT FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
			if($res_disb_1->fields['PK_TERM_BLOCK'] == 0)
			{
				$STUDENT_DISBURSEMENT['PK_TERM_BLOCK'] = $_POST['PK_TERM_BLOCK_'.$PK_STUDENT_DISBURSEMENT];
			}

			/* DIAM-737 */
			if($res_disb_1->fields['PK_STUDENT_ENROLLMENT'] != $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT]) 
			{
				$STUDENT_DISBURSEMENT['PK_STUDENT_ENROLLMENT'] 	= $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT];
			}
			/* End DIAM-737 */
			
			if($PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'] != $PAYMENT_BATCH_DETAIL['DUE_AMOUNT'])
			{

				if($PAYMENT_BATCH_DETAIL['DISBURSEMENT_TYPE'] == 1)
				{
					$res_disb_1 = $db->Execute("SELECT * FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
					
					$STUDENT_DISBURSEMENT1 = array();
					if($res_disb_1->fields['PK_TERM_BLOCK'] == 0)
					{
						$STUDENT_DISBURSEMENT1['PK_TERM_BLOCK'] = $_POST['PK_TERM_BLOCK_'.$PK_STUDENT_DISBURSEMENT];
					}
					else
					{
						$STUDENT_DISBURSEMENT1['PK_TERM_BLOCK'] = $res_disb_1->fields['PK_TERM_BLOCK'];
					}

					/* DIAM-737 */
					if($res_disb_1->fields['PK_STUDENT_ENROLLMENT'] != $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT]) 
					{
						$PK_STUDENT_ENROLLMENT_IDS 	= $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT];
					}
					else{
						$PK_STUDENT_ENROLLMENT_IDS 	= $res_disb_1->fields['PK_STUDENT_ENROLLMENT'];
					}
					/* End DIAM-737 */

					$STUDENT_DISBURSEMENT1['PK_DISBURSEMENT_STATUS'] = 2;
					$STUDENT_DISBURSEMENT1['PK_DETAIL_TYPE']  		 = 4; 
					$STUDENT_DISBURSEMENT1['DETAIL']				 = $STUDENT_DISBURSEMENT['DETAIL'];
					$STUDENT_DISBURSEMENT1['PK_AR_LEDGER_CODE'] 	 = $res_disb_1->fields['PK_AR_LEDGER_CODE'];
					$STUDENT_DISBURSEMENT1['ACADEMIC_YEAR'] 		 = $res_disb_1->fields['ACADEMIC_YEAR'];
					$STUDENT_DISBURSEMENT1['ACADEMIC_PERIOD'] 		 = $res_disb_1->fields['ACADEMIC_PERIOD'];
					$STUDENT_DISBURSEMENT1['DISBURSEMENT_DATE'] 	 = $res_disb_1->fields['DISBURSEMENT_DATE'];
					$STUDENT_DISBURSEMENT1['DISBURSEMENT_AMOUNT'] 	 = $PAYMENT_BATCH_DETAIL['DUE_AMOUNT'] - $PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'];
					$STUDENT_DISBURSEMENT1['PK_AWARD_YEAR'] 		 = $res_disb_1->fields['PK_AWARD_YEAR'];
					$STUDENT_DISBURSEMENT1['APPROVED_DATE'] 		 = $res_disb_1->fields['APPROVED_DATE'];
					$STUDENT_DISBURSEMENT1['DEPOSITED_DATE'] 		 = $res_disb_1->fields['DEPOSITED_DATE'];
					$STUDENT_DISBURSEMENT1['HOURS_REQUIRED'] 		 = $res_disb_1->fields['HOURS_REQUIRED'];
					$STUDENT_DISBURSEMENT1['PK_DETAIL_TYPE'] 		 = $res_disb_1->fields['PK_DETAIL_TYPE'];
					$STUDENT_DISBURSEMENT1['PK_STUDENT_ENROLLMENT']  = $PK_STUDENT_ENROLLMENT_IDS;
					$STUDENT_DISBURSEMENT1['PK_STUDENT_MASTER'] 	 = $res_disb_1->fields['PK_STUDENT_MASTER'];
					$STUDENT_DISBURSEMENT1['PK_ACCOUNT'] 			 = $_SESSION['PK_ACCOUNT'];
					$STUDENT_DISBURSEMENT1['CREATED_BY']  			 = $_SESSION['PK_USER'];
					$STUDENT_DISBURSEMENT1['CREATED_ON']  			 = date("Y-m-d H:i");
					db_perform('S_STUDENT_DISBURSEMENT', $STUDENT_DISBURSEMENT1, 'insert');
					
					$STUDENT_DISBURSEMENT['DISBURSEMENT_AMOUNT'] = $PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'];
				} else if($PAYMENT_BATCH_DETAIL['DISBURSEMENT_TYPE'] == 2){
					$STUDENT_DISBURSEMENT['DISBURSEMENT_AMOUNT'] = $PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'];
				}
			}			
			if($old_PK_BATCH_STATUS==3){
				payment_unpost_batch_history($PK_PAYMENT_BATCH_MASTER,$PAYMENT_BATCH_DETAIL,$PK_PAYMENT_BATCH_DETAIL,$STUDENT_DISBURSEMENT);
			}
			db_perform('S_STUDENT_DISBURSEMENT', $STUDENT_DISBURSEMENT, 'update'," PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
			
			$ledger_data['PK_PAYMENT_BATCH_DETAIL'] = $PK_PAYMENT_BATCH_DETAIL;
			$ledger_data['PK_STUDENT_DISBURSEMENT'] = $PK_STUDENT_DISBURSEMENT;
			$ledger_data['PK_AR_LEDGER_CODE'] 		= $res_disb->fields['PK_AR_LEDGER_CODE'];
			$ledger_data['AMOUNT'] 					= $PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'];
			$ledger_data['DATE'] 					= $PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE'];
			$ledger_data['PK_STUDENT_ENROLLMENT'] 	= $PK_STUDENT_ENROLLMENT_ID;
			$ledger_data['PK_STUDENT_MASTER'] 		= $res_disb->fields['PK_STUDENT_MASTER'];
			student_ledger($ledger_data);
			
			$res_noti = $db->Execute("SELECT PK_EMAIL_TEMPLATE,PK_TEXT_TEMPLATE, PK_AR_LEDGER_CODE FROM S_NOTIFICATION_SETTINGS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_EVENT_TYPE = 14");
			if($res_noti->RecordCount() > 0) {
				if($res_noti->fields['PK_EMAIL_TEMPLATE'] > 0) {
					send_payment_receipt_mail($PK_PAYMENT_BATCH_DETAIL,$res_noti->fields['PK_EMAIL_TEMPLATE'],$res_noti->fields['PK_AR_LEDGER_CODE']);
				}
				
				if($res_noti->fields['PK_TEXT_TEMPLATE'] > 0) {
					send_payment_receipt_text($PK_PAYMENT_BATCH_DETAIL,$res_noti->fields['PK_TEXT_TEMPLATE'],$res_noti->fields['PK_AR_LEDGER_CODE']);
				}
			}

			/* DIAM-2144 */
			$res_noti_led = $db->Execute("SELECT PK_EMAIL_TEMPLATE,PK_TEXT_TEMPLATE, PK_AR_LEDGER_CODE FROM S_NOTIFICATION_SETTINGS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_EVENT_TYPE = 21");
			if($res_noti_led->RecordCount() > 0) {
				if($res_noti_led->fields['PK_EMAIL_TEMPLATE'] > 0) {
					send_disbursement_notification_mail($PK_PAYMENT_BATCH_DETAIL,$res_noti_led->fields['PK_EMAIL_TEMPLATE'],$res_noti_led->fields['PK_AR_LEDGER_CODE']);
				}
				
				if($res_noti_led->fields['PK_TEXT_TEMPLATE'] > 0) {
					send_disbursement_notification_text($PK_PAYMENT_BATCH_DETAIL,$res_noti_led->fields['PK_TEXT_TEMPLATE'],$res_noti_led->fields['PK_AR_LEDGER_CODE']);
				}
			}
			/* DIAM-2144 */
			
		}

		update_disbursement_status($PAYMENT_BATCH_DETAIL['PK_STUDENT_MASTER'],$PAYMENT_BATCH_DETAIL['PK_STUDENT_ENROLLMENT']);
	}


	
}

?>
