<?php
$page="batch_payment_hold";
if($_GET['id'] == '' ){

	$res_acc = $db->Execute("SELECT PAYMENT_BATCH_NO FROM Z_ACCOUNT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 		
	
	$BATCH_NO='P'.$res_acc->fields['PAYMENT_BATCH_NO'];

	
    $old_PK_BATCH_STATUS=1;
	$PAYMENT_BATCH_MASTER['BATCH_NO'] 			= 'P'.$res_acc->fields['PAYMENT_BATCH_NO'];
	$PAYMENT_BATCH_MASTER['PK_ACCOUNT']  		= $_SESSION['PK_ACCOUNT'];
	$PAYMENT_BATCH_MASTER['CREATED_BY']  		= $_SESSION['PK_USER'];
	$PAYMENT_BATCH_MASTER['CREATED_ON']  		= date("Y-m-d H:i");
	$where_duplicate="";
		$j=0;
		foreach($PAYMENT_BATCH_MASTER as $key=>$val){
			if($val!="" && $key!="CREATED_ON" &&  $key!="BATCH_NO"){
				$where_duplicate .= ($j==0?'':'AND')." ".$key."='".$val."'";
				$j++;
			}
		}
	//double check the logic for duplicate batch
	// echo "SELECT PK_PAYMENT_BATCH_MASTER FROM S_PAYMENT_BATCH_MASTER WHERE $where_duplicate ";
	// exit;
	$res_duplicate_check= $db->Execute("SELECT PK_PAYMENT_BATCH_MASTER FROM S_PAYMENT_BATCH_MASTER WHERE $where_duplicate "); 		
	if($res_duplicate_check->RecordCount()==0){
		db_perform('S_PAYMENT_BATCH_MASTER', $PAYMENT_BATCH_MASTER, 'insert');
		$PK_PAYMENT_BATCH_MASTER = $db->insert_ID();
		$NEW_BATCH_NO = $res_acc->fields['PAYMENT_BATCH_NO'] + 1;
		$db->Execute("UPDATE Z_ACCOUNT SET PAYMENT_BATCH_NO = '$NEW_BATCH_NO' WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 

	}else{
		//it will redirect on same if the batch is exists
		$PK_PAYMENT_BATCH_MASTER = $res_duplicate_check->fields['PK_PAYMENT_BATCH_MASTER'];		
		header("location:batch_payment?msg=1&batch_id=".$PK_PAYMENT_BATCH_MASTER);
		exit;
		

	}
} else {
	$PK_PAYMENT_BATCH_MASTER = $_GET['id'];		
	$res = $db->Execute("SELECT DATE_RECEIVED, PK_BATCH_STATUS FROM S_PAYMENT_BATCH_MASTER WHERE PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'"); 
	$old_PK_BATCH_STATUS = $res->fields['PK_BATCH_STATUS'];	
	if($old_PK_BATCH_STATUS != 2) {
		$PAYMENT_BATCH_MASTER['EDITED_BY'] = $_SESSION['PK_USER'];
		$PAYMENT_BATCH_MASTER['EDITED_ON'] = date("Y-m-d H:i");
		db_perform('S_PAYMENT_BATCH_MASTER', $PAYMENT_BATCH_MASTER, 'update'," PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT='$_SESSION[PK_ACCOUNT]' ");
	}
}

if(($old_PK_BATCH_STATUS == 1 || $old_PK_BATCH_STATUS == 3) && $PK_PAYMENT_BATCH_MASTER!="") { 
	
	$res = $db->Execute("SELECT PK_BATCH_STATUS FROM S_PAYMENT_BATCH_MASTER WHERE PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
	$PAYMENT_BATCH_MASTER['PK_BATCH_STATUS'] = $res->fields['PK_BATCH_STATUS'];
	logpaymentbatch('hold disbursement students',json_encode($_POST['PK_STUDENT_DISBURSEMENT']));
	// $reverified=explode(',',$_POST['disbusement_students']);
	// if(count($reverified)!=count($_POST['PK_STUDENT_DISBURSEMENT'])){
	// 	$new_arr=array_merge($reverified,$_POST['PK_STUDENT_DISBURSEMENT']);
	// 	$_POST['PK_STUDENT_DISBURSEMENT']=array_unique($new_arr);
	// }
	foreach($_POST['PK_STUDENT_DISBURSEMENT'] as $PK_STUDENT_DISBURSEMENT)
	{
		$res_disb = $db->Execute("SELECT PK_STUDENT_MASTER, PK_STUDENT_ENROLLMENT, PK_AR_LEDGER_CODE FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 	
		/* DIAM-737 */
		if($res_disb->fields['PK_STUDENT_ENROLLMENT'] != $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT]) 
		{
			$PK_STUDENT_ENROLLMENT_ID 	= $_POST['DISBURSEMENT_PK_ENROLLMENT_'.$PK_STUDENT_DISBURSEMENT];
		}
		else{
			$PK_STUDENT_ENROLLMENT_ID 	= $res_disb->fields['PK_STUDENT_ENROLLMENT'];
		}
		/* End DIAM-737 */

		$PAYMENT_BATCH_DETAIL = array();
		$RECEIPT_NO = '';
		$PAYMENT_BATCH_DETAIL['PK_BATCH_PAYMENT_STATUS'] = 2;
		$PAYMENT_BATCH_DETAIL['RECEIPT_NO'] 				= $RECEIPT_NO;
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_MASTER']  		= $res_disb->fields['PK_STUDENT_MASTER'];
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_ENROLLMENT']  	= $PK_STUDENT_ENROLLMENT_ID;
		$PAYMENT_BATCH_DETAIL['PK_PAYMENT_BATCH_MASTER']  	= $PK_PAYMENT_BATCH_MASTER;
		$PAYMENT_BATCH_DETAIL['PK_STUDENT_DISBURSEMENT']  	= $PK_STUDENT_DISBURSEMENT;
		$PAYMENT_BATCH_DETAIL['DUE_AMOUNT']  				= $_POST['DISBURSEMENT_AMOUNT_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE']  	= $_POST['BATCH_TRANSACTION_DATE_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT']  			= $_POST['PAID_AMOUNT_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PRIOR_YEAR']  				= $_POST['PRIOR_YEAR_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PK_TERM_BLOCK']  			= $_POST['PK_TERM_BLOCK_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['CHECK_NO']  					= $_POST['STUD_CHECK_NO_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['BATCH_DETAIL_DESCRIPTION']  	= $_POST['BATCH_DETAIL_DESCRIPTION_'.$PK_STUDENT_DISBURSEMENT];
		$PAYMENT_BATCH_DETAIL['PK_ACCOUNT']  				= $_SESSION['PK_ACCOUNT'];
		$PAYMENT_BATCH_DETAIL['CREATED_BY']  				= $_SESSION['PK_USER'];
		$PAYMENT_BATCH_DETAIL['CREATED_ON']  				= date("Y-m-d H:i");
		
		if($PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE'] != '')
			$PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE'] = date("Y-m-d",strtotime($PAYMENT_BATCH_DETAIL['BATCH_TRANSACTION_DATE']));
		
		if($PAYMENT_BATCH_DETAIL['RECEIVED_AMOUNT'] != $PAYMENT_BATCH_DETAIL['DUE_AMOUNT'])
			$PAYMENT_BATCH_DETAIL['DISBURSEMENT_TYPE'] = $_POST['DISBURSEMENT_TYPE_'.$PK_STUDENT_DISBURSEMENT];
			
			if($_POST['PK_PAYMENT_BATCH_DETAIL_'.$PK_STUDENT_DISBURSEMENT] == '') {
				$res_batch_det = $db->Execute("SELECT PK_PAYMENT_BATCH_DETAIL FROM S_PAYMENT_BATCH_DETAIL WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_PAYMENT_BATCH_MASTER = '$PK_PAYMENT_BATCH_MASTER' "); 
				
				if($res_batch_det->RecordCount() == 0) {
					db_perform('S_PAYMENT_BATCH_DETAIL', $PAYMENT_BATCH_DETAIL, 'insert');
					$PK_PAYMENT_BATCH_DETAIL = $db->insert_ID();
				} else {
					$PK_PAYMENT_BATCH_DETAIL = $res_batch_det->fields['PK_PAYMENT_BATCH_DETAIL'];
				}
				
				$PK_PAYMENT_BATCH_DETAIL_ARR[] = $PK_PAYMENT_BATCH_DETAIL;

			} else {
				$PK_PAYMENT_BATCH_DETAIL = $_POST['PK_PAYMENT_BATCH_DETAIL_'.$PK_STUDENT_DISBURSEMENT];
				db_perform('S_PAYMENT_BATCH_DETAIL', $PAYMENT_BATCH_DETAIL, 'update'," PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' ");
				
				$PK_PAYMENT_BATCH_DETAIL_ARR[] = $PK_PAYMENT_BATCH_DETAIL;
			}
			
			$STUDENT_DISBURSEMENT = array();
			$STUDENT_DISBURSEMENT['PK_PAYMENT_BATCH_DETAIL'] = $PK_PAYMENT_BATCH_DETAIL;
			$STUDENT_DISBURSEMENT['PK_DETAIL_TYPE']  		 = 4; 
			$STUDENT_DISBURSEMENT['DETAIL']  				 = $_POST['DISBURSEMENT_DETAIL_'.$PK_STUDENT_DISBURSEMENT];

			
			db_perform('S_STUDENT_DISBURSEMENT', $STUDENT_DISBURSEMENT, 'update'," PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
			
			update_disbursement_status($PAYMENT_BATCH_DETAIL['PK_STUDENT_MASTER'],$PAYMENT_BATCH_DETAIL['PK_STUDENT_ENROLLMENT']);
	}
}

?>
