<?php
function update_estimate_fee_status($PK_STUDENT_MASTER,$PK_STUDENT_ENROLLMENT){
	global $db;
	
	$en_cond = "";
	if($PK_STUDENT_ENROLLMENT != '')
		$en_cond = " AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ";
	
	//if Approved date are null then display nothing
	$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '0' WHERE FEE_BUDGET_APPROVED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND FEE_BUDGET_DEPOSITED_DATE = '0000-00-00' ");
	
	//If Deposited date is null and Approved date is set then display "Approved"
	$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '2' WHERE FEE_BUDGET_APPROVED_DATE != '0000-00-00' AND FEE_BUDGET_DEPOSITED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' $en_cond AND PK_TUITION_BATCH_DETAIL = 0 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'");
	
	/*if Deposited date is null and Approved date is set and Estimate Fee is in a batch then display:
    "Hold" (if status is set to "Hold" in the batch)
    "In Batch"*/
	$res = $db->Execute("SELECT PK_STUDENT_FEE_BUDGET, PK_TUITION_BATCH_DETAIL FROM S_STUDENT_FEE_BUDGET WHERE FEE_BUDGET_APPROVED_DATE != '0000-00-00' AND FEE_BUDGET_DEPOSITED_DATE = '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' $en_cond AND PK_TUITION_BATCH_DETAIL > 0 AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'");
	while (!$res->EOF){
		$PK_STUDENT_FEE_BUDGET = $res->fields['PK_STUDENT_FEE_BUDGET'];
		$PK_TUITION_BATCH_DETAIL = $res->fields['PK_TUITION_BATCH_DETAIL'];
		
		$res_bat = $db->Execute("SELECT PK_BATCH_STATUS FROM S_TUITION_BATCH_MASTER, S_TUITION_BATCH_DETAIL WHERE S_TUITION_BATCH_MASTER.PK_TUITION_BATCH_MASTER = S_TUITION_BATCH_DETAIL.PK_TUITION_BATCH_MASTER AND PK_TUITION_BATCH_DETAIL = '$PK_TUITION_BATCH_DETAIL' ");
		if($res_bat->fields['PK_BATCH_STATUS'] == 1)
			$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '3' WHERE PK_STUDENT_FEE_BUDGET = '$PK_STUDENT_FEE_BUDGET' ");
		else if($res_bat->fields['PK_BATCH_STATUS'] == 2)
			$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '1' WHERE PK_STUDENT_FEE_BUDGET = '$PK_STUDENT_FEE_BUDGET' ");
		else if($res_bat->fields['PK_BATCH_STATUS'] == 3)
			$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '4' WHERE PK_STUDENT_FEE_BUDGET = '$PK_STUDENT_FEE_BUDGET' ");
			
		$res->MoveNext();
	}
	
	//If Deposited date and Approved date are set then display "Posted"
	$db->Execute("UPDATE S_STUDENT_FEE_BUDGET SET PK_ESTIMATE_FEE_STATUS = '1' WHERE FEE_BUDGET_APPROVED_DATE != '0000-00-00' AND FEE_BUDGET_DEPOSITED_DATE != '0000-00-00' AND PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' $en_cond AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'");
}