<? function make_attendance_inactive($PK_STUDENT_COURSE,$date,$return_date){ //Ticket # 1661
	global $db;
	
	/* Ticket # 1661 */
	if($return_date == '') {
		$res = $db->Execute("SELECT PK_COURSE_OFFERING FROM  S_STUDENT_COURSE WHERE PK_STUDENT_COURSE = '$PK_STUDENT_COURSE' "); 
		$PK_COURSE_OFFERING	= $res->fields['PK_COURSE_OFFERING'];
		make_attendance_active($PK_STUDENT_COURSE, $PK_COURSE_OFFERING, $date, 2);
		
		$cond2 = " AND S_STUDENT_SCHEDULE.SCHEDULE_DATE >= '$date' ";
	} else {
		$cond2 = " AND S_STUDENT_SCHEDULE.SCHEDULE_DATE >= '$date' AND S_STUDENT_SCHEDULE.SCHEDULE_DATE <= '$return_date' ";
	}
	/* Ticket # 1661 */
	
	$res = $db->Execute("SELECT PK_STUDENT_MASTER,PK_STUDENT_ENROLLMENT,PK_STUDENT_SCHEDULE,S_STUDENT_SCHEDULE.PK_COURSE_OFFERING_SCHEDULE_DETAIL FROM S_STUDENT_SCHEDULE, S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_STUDENT_COURSE = '$PK_STUDENT_COURSE' AND S_STUDENT_SCHEDULE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_COURSE_OFFERING_SCHEDULE_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL = S_STUDENT_SCHEDULE.PK_COURSE_OFFERING_SCHEDULE_DETAIL AND COMPLETED = 0  $cond2 "); //Ticket # 1661 
	while (!$res->EOF) {
		$PK_STUDENT_SCHEDULE 				= $res->fields['PK_STUDENT_SCHEDULE'];
		$PK_COURSE_OFFERING_SCHEDULE_DETAIL = $res->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL'];
		$PK_STUDENT_ENROLLMENT 				= $res->fields['PK_STUDENT_ENROLLMENT'];
		
		$res_def_att_typ = $db->Execute("select PK_ATTENDANCE_ACTIVITY_TYPES from S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$PK_COURSE_OFFERING_SCHEDULE_DETAIL' ");
		
		$ATTENDANCE_DETAIL = array();
		$ATTENDANCE_DETAIL['ATTENDANCE_HOURS'] 				= 0;
		$ATTENDANCE_DETAIL['PK_ATTENDANCE_CODE'] 			= 7;
		$ATTENDANCE_DETAIL['COMPLETED'] 					= 0;
		$ATTENDANCE_DETAIL['PK_ATTENDANCE_ACTIVITY_TYPESS']	= $res_def_att_typ->fields['PK_ATTENDANCE_ACTIVITY_TYPES'];
		
		$res_att = $db->Execute("SELECT PK_STUDENT_ATTENDANCE FROM S_STUDENT_ATTENDANCE WHERE  PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$PK_COURSE_OFFERING_SCHEDULE_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'  AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' "); 
		if($res_att->RecordCount() == 0){
			$ATTENDANCE_DETAIL['PK_STUDENT_MASTER'] 					= $res->fields['PK_STUDENT_MASTER'];
			$ATTENDANCE_DETAIL['PK_STUDENT_ENROLLMENT'] 				= $res->fields['PK_STUDENT_ENROLLMENT'];
			$ATTENDANCE_DETAIL['PK_STUDENT_SCHEDULE'] 					= $res->fields['PK_STUDENT_SCHEDULE'];
			$ATTENDANCE_DETAIL['PK_COURSE_OFFERING_SCHEDULE_DETAIL'] 	= $res->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL'];
			$ATTENDANCE_DETAIL['PK_ACCOUNT']  							= $_SESSION['PK_ACCOUNT'];;
			$ATTENDANCE_DETAIL['CREATED_BY']  							= $_SESSION['PK_USER'];
			$ATTENDANCE_DETAIL['CREATED_ON']  							= date("Y-m-d H:i");
			db_perform('S_STUDENT_ATTENDANCE', $ATTENDANCE_DETAIL, 'insert');
		} else {
			$ATTENDANCE_DETAIL['EDITED_BY']  			= $_SESSION['PK_USER'];
			$ATTENDANCE_DETAIL['EDITED_ON']  			= date("Y-m-d H:i");
			db_perform('S_STUDENT_ATTENDANCE', $ATTENDANCE_DETAIL, 'update'," PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$PK_COURSE_OFFERING_SCHEDULE_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'  AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ");
		}
		$res->MoveNext();
	}
}

function make_attendance_active($PK_STUDENT_COURSE, $PK_COURSE_OFFERING, $date, $type){	//Ticket # 1661
	global $db;
	
	/* $type = 1, >= date
	$type = 2, < $type */
	
	/* Ticket # 1661 */
	if($type == 2)
		$cond = " AND S_STUDENT_SCHEDULE.SCHEDULE_DATE < '$date' ";
	else {
		$cond = " AND S_STUDENT_SCHEDULE.SCHEDULE_DATE >= '$date' ";
		
		$res =  $db->Execute("SELECT INACTIVE FROM S_STUDENT_COURSE WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_COURSE = '$PK_STUDENT_COURSE' "); 
		if($res->fields['INACTIVE'] != '' && $res->fields['INACTIVE'] != '0000-00-00'){
			$temp_INACTIVE 		= $res->fields['INACTIVE'];
			$temp_RETURN_DATE 	= date('Y-m-d', strtotime($date. ' -1 days'));
			
			make_attendance_inactive($PK_STUDENT_COURSE,$temp_INACTIVE,$temp_RETURN_DATE);
		}
	}
	/* Ticket # 1661 */
	
	$res =  $db->Execute("SELECT PK_ATTENDANCE_CODE FROM S_COURSE_OFFERING WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' "); 
	$PK_ATTENDANCE_CODE = $res->fields['PK_ATTENDANCE_CODE'];
	
	$res = $db->Execute("SELECT PK_STUDENT_MASTER,PK_STUDENT_ENROLLMENT,PK_STUDENT_SCHEDULE,S_STUDENT_SCHEDULE.PK_COURSE_OFFERING_SCHEDULE_DETAIL, S_STUDENT_SCHEDULE.HOURS FROM S_STUDENT_SCHEDULE, S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_STUDENT_COURSE = '$PK_STUDENT_COURSE' AND S_STUDENT_SCHEDULE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_COURSE_OFFERING_SCHEDULE_DETAIL.PK_COURSE_OFFERING_SCHEDULE_DETAIL = S_STUDENT_SCHEDULE.PK_COURSE_OFFERING_SCHEDULE_DETAIL AND COMPLETED = 0 $cond "); //Ticket # 1661
	while (!$res->EOF) {
		$PK_STUDENT_SCHEDULE 				= $res->fields['PK_STUDENT_SCHEDULE'];
		$PK_COURSE_OFFERING_SCHEDULE_DETAIL = $res->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL'];
		$PK_STUDENT_ENROLLMENT 				= $res->fields['PK_STUDENT_ENROLLMENT'];
		$HOURS 								= $res->fields['HOURS'];

		$res_att = $db->Execute("SELECT PK_STUDENT_ATTENDANCE FROM S_STUDENT_ATTENDANCE WHERE  PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$PK_COURSE_OFFERING_SCHEDULE_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'  AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_ATTENDANCE_CODE = 7"); 
		if($res_att->RecordCount() > 0){
			$ATTENDANCE_DETAIL = array();
			$ATTENDANCE_DETAIL['ATTENDANCE_HOURS'] 	 = $HOURS;
			$ATTENDANCE_DETAIL['PK_ATTENDANCE_CODE'] = $PK_ATTENDANCE_CODE;
			$ATTENDANCE_DETAIL['EDITED_BY']  		 = $_SESSION['PK_USER'];
			$ATTENDANCE_DETAIL['EDITED_ON']  		 = date("Y-m-d H:i");
			db_perform('S_STUDENT_ATTENDANCE', $ATTENDANCE_DETAIL, 'update'," PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$PK_COURSE_OFFERING_SCHEDULE_DETAIL' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'  AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ");
		}
		$res->MoveNext();
	}
}