<? require_once("../global/mail.php"); 
require_once("../global/texting.php"); 
function add_student_to_course_offering($PK_COURSE_OFFERING,$PK_STUDENT_ENROLLMENT_ARR){
	global $db;
	
	$SEND_ENROLLED_IN_CLASS_EMAIL_TEMPLATE 	= 0;
	$SEND_ENROLLED_IN_CLASS_TEXT_TEMPLATE 	= 0;
	$res_noti = $db->Execute("SELECT PK_EMAIL_TEMPLATE,PK_TEXT_TEMPLATE FROM S_NOTIFICATION_SETTINGS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_EVENT_TYPE = 7");
	if($res_noti->RecordCount() > 0) {
		$SEND_ENROLLED_IN_CLASS_EMAIL_TEMPLATE 	= $res_noti->fields['PK_EMAIL_TEMPLATE'];
		$SEND_ENROLLED_IN_CLASS_TEXT_TEMPLATE	= $res_noti->fields['PK_TEXT_TEMPLATE'];
	}
	
	$res = $db->Execute("SELECT PK_TERM_MASTER, UNITS, S_COURSE_OFFERING.PK_ATTENDANCE_CODE, S_COURSE_OFFERING.PK_COURSE FROM S_COURSE_OFFERING LEFT JOIN S_COURSE ON S_COURSE.PK_COURSE = S_COURSE_OFFERING.PK_COURSE WHERE PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' AND S_COURSE_OFFERING.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); //Ticket #1897
	$DEFAULT_ATTENDANCE_CODE  	= $res->fields['PK_ATTENDANCE_CODE'];
	$PK_COURSE  				= $res->fields['PK_COURSE']; //Ticket #1897
	
	$res_sts 	= $db->Execute("SELECT PK_COURSE_OFFERING_STUDENT_STATUS FROM M_COURSE_OFFERING_STUDENT_STATUS WHERE MAKE_AS_DEFAULT='1' AND PK_ACCOUNT='$_SESSION[PK_ACCOUNT]' ");
	$res_grade_def 	= $db->Execute("SELECT PK_GRADE, GRADE  FROM S_GRADE WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND IS_DEFAULT = 1 "); //Ticket # 1900 
	foreach($PK_STUDENT_ENROLLMENT_ARR as $PK_STUDENT_ENROLLMENT){ 
		$res_en = $res_sch = $db->Execute("SELECT PK_STUDENT_MASTER FROM S_STUDENT_ENROLLMENT WHERE PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		
		$STUDENT_COURSE['PK_TERM_MASTER'] 			 		 = $res->fields['PK_TERM_MASTER'];
		$STUDENT_COURSE['PK_COURSE_OFFERING'] 	 			 = $PK_COURSE_OFFERING;
		$STUDENT_COURSE['PK_STUDENT_ENROLLMENT'] 			 = $PK_STUDENT_ENROLLMENT;
		$STUDENT_COURSE['PK_STUDENT_MASTER'] 	 			 = $res_en->fields['PK_STUDENT_MASTER'];
		$STUDENT_COURSE['PK_COURSE_OFFERING_STUDENT_STATUS'] = $res_sts->fields['PK_COURSE_OFFERING_STUDENT_STATUS'];
		$STUDENT_COURSE['FINAL_GRADE'] 						 = $res_grade_def->fields['PK_GRADE']; //Ticket # 1900 
		$STUDENT_COURSE['FINAL_GRADE_GRADE'] 				 = $res_grade_def->fields['GRADE']; //Ticket # 1900 
		$STUDENT_COURSE['COURSE_UNITS'] 					 = $res->fields['UNITS'];
		$STUDENT_COURSE['PK_ACCOUNT'] 			 			 = $_SESSION['PK_ACCOUNT'];
		$STUDENT_COURSE['CREATED_BY']  			 			 = $_SESSION['PK_USER'];
		$STUDENT_COURSE['CREATED_ON']  						 = date("Y-m-d H:i");
		db_perform('S_STUDENT_COURSE', $STUDENT_COURSE, 'insert'); 
		$PK_STUDENT_COURSE = $db->insert_ID();
		
		/* $res_sts1  = $db->Execute("SELECT PK_COURSE_OFFERING_STUDENT_STATUS  FROM M_COURSE_OFFERING_STUDENT_STATUS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_COURSE_OFFERING_STUDENT_STATUS =1 ");
		
		$STUDENT_FINAL_GRADE['PK_STUDENT_MASTER'] 					= $res_en->fields['PK_STUDENT_MASTER'];
		$STUDENT_FINAL_GRADE['PK_STUDENT_ENROLLMENT'] 				= $PK_STUDENT_ENROLLMENT;
		$STUDENT_FINAL_GRADE['PK_COURSE_OFFERING'] 					= $PK_COURSE_OFFERING;
		$STUDENT_FINAL_GRADE['GRADE'] 								= $res_grade->fields['PK_GRADE'];
		$STUDENT_FINAL_GRADE['PK_COURSE_OFFERING_STUDENT_STATUS'] 	= $res_sts1->fields['PK_COURSE_OFFERING_STUDENT_STATUS'];
		$STUDENT_FINAL_GRADE['PK_ACCOUNT'] 							= $_SESSION['PK_ACCOUNT'];
		$STUDENT_FINAL_GRADE['CREATED_ON'] 							= date("Y-m-d H:i:s");
		$STUDENT_FINAL_GRADE['CREATED_BY'] 							= $_SESSION['ADMIN_PK_USER'];
		db_perform('S_STUDENT_FINAL_GRADE', $STUDENT_FINAL_GRADE, 'insert');*/
		
		$res_sch = $db->Execute("SELECT * FROM S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_COURSE_OFFERING = '$STUDENT_COURSE[PK_COURSE_OFFERING]' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		while (!$res_sch->EOF) {
			$STUDENT_SCHEDULE['SCHEDULE_DATE'] 	 	 	 			= $res_sch->fields['SCHEDULE_DATE'];
			$STUDENT_SCHEDULE['START_TIME'] 	 	 	 			= $res_sch->fields['START_TIME'];
			$STUDENT_SCHEDULE['END_TIME'] 	 	 		 			= $res_sch->fields['END_TIME'];
			$STUDENT_SCHEDULE['HOURS'] 	 	 			 			= $res_sch->fields['HOURS'];
			$STUDENT_SCHEDULE['PK_CAMPUS_ROOM'] 	 	 			= $res_sch->fields['PK_CAMPUS_ROOM'];
			$STUDENT_SCHEDULE['PK_STUDENT_COURSE'] 	 	 			= $PK_STUDENT_COURSE;
			$STUDENT_SCHEDULE['PK_STUDENT_ENROLLMENT'] 	 			= $PK_STUDENT_ENROLLMENT;
			$STUDENT_SCHEDULE['PK_SCHEDULE_TYPE'] 	 	 			= 1;
			$STUDENT_SCHEDULE['PK_COURSE_OFFERING_SCHEDULE_DETAIL']	= $res_sch->fields['PK_COURSE_OFFERING_SCHEDULE_DETAIL'];
			$STUDENT_SCHEDULE['PK_STUDENT_MASTER'] 	 	 			= $res_en->fields['PK_STUDENT_MASTER'];
			$STUDENT_SCHEDULE['PK_ACCOUNT'] 				 		= $_SESSION['PK_ACCOUNT'];
			$STUDENT_SCHEDULE['CREATED_BY']  			 			= $_SESSION['PK_USER'];
			$STUDENT_SCHEDULE['CREATED_ON']  			 			= date("Y-m-d H:i");
			db_perform('S_STUDENT_SCHEDULE', $STUDENT_SCHEDULE, 'insert');
			$PK_STUDENT_SCHEDULE = $db->insert_ID();
			
			if($res_sch->fields['COMPLETED'] == 1 || strtotime($STUDENT_SCHEDULE['SCHEDULE_DATE']) < strtotime(date("Y-m-d")) ){
				$COMPLETED = $res_sch->fields['COMPLETED'];
				if($COMPLETED == 1) {
					$PK_ATTENDANCE_CODE = 7;
					$ATTENDANCE_HOURS	= 0;
				} else {
					$PK_ATTENDANCE_CODE = $DEFAULT_ATTENDANCE_CODE;
					$ATTENDANCE_HOURS	= $STUDENT_SCHEDULE['HOURS'];
					
					if($PK_ATTENDANCE_CODE == "" || $PK_ATTENDANCE_CODE == 0)
						$PK_ATTENDANCE_CODE = 14;
				}
				$res_def_att_typ = $db->Execute("select PK_ATTENDANCE_ACTIVITY_TYPES from S_COURSE_OFFERING_SCHEDULE_DETAIL WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_COURSE_OFFERING_SCHEDULE_DETAIL = '$STUDENT_SCHEDULE[PK_COURSE_OFFERING_SCHEDULE_DETAIL]' ");
				
				//Ticket # 1100
				$res_att_pre = $db->Execute("SELECT PK_STUDENT_ATTENDANCE FROM S_STUDENT_ATTENDANCE WHERE PK_STUDENT_SCHEDULE = '$PK_STUDENT_SCHEDULE' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
				if($res_att_pre->RecordCount() == 0) {
					$ATTENDANCE_DETAIL = array();
					$ATTENDANCE_DETAIL['PK_STUDENT_MASTER'] 					= $STUDENT_SCHEDULE['PK_STUDENT_MASTER'];
					$ATTENDANCE_DETAIL['PK_STUDENT_ENROLLMENT'] 				= $STUDENT_SCHEDULE['PK_STUDENT_ENROLLMENT'];
					$ATTENDANCE_DETAIL['PK_STUDENT_SCHEDULE'] 					= $PK_STUDENT_SCHEDULE;
					$ATTENDANCE_DETAIL['ATTENDANCE_HOURS'] 						= $ATTENDANCE_HOURS;
					$ATTENDANCE_DETAIL['PK_ATTENDANCE_CODE'] 					= $PK_ATTENDANCE_CODE;
					$ATTENDANCE_DETAIL['PK_COURSE_OFFERING_SCHEDULE_DETAIL'] 	= $STUDENT_SCHEDULE['PK_COURSE_OFFERING_SCHEDULE_DETAIL'];
					$ATTENDANCE_DETAIL['PK_ATTENDANCE_ACTIVITY_TYPESS']			= $res_def_att_typ->fields['PK_ATTENDANCE_ACTIVITY_TYPES'];
					$ATTENDANCE_DETAIL['COMPLETED']   							= $COMPLETED;
					$ATTENDANCE_DETAIL['PK_ACCOUNT']  							= $_SESSION['PK_ACCOUNT'];;
					$ATTENDANCE_DETAIL['CREATED_BY']  							= $_SESSION['PK_USER'];
					$ATTENDANCE_DETAIL['CREATED_ON']  							= date("Y-m-d H:i");
					db_perform('S_STUDENT_ATTENDANCE', $ATTENDANCE_DETAIL, 'insert');
				}
			}
			
			$res_sch->MoveNext();
		}
		
		$res_grade = $db->Execute("SELECT * FROM S_COURSE_OFFERING_GRADE WHERE PK_COURSE_OFFERING = '$STUDENT_COURSE[PK_COURSE_OFFERING]' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]'");
		while (!$res_grade->EOF) {
			$STUDENT_GRADE['PK_COURSE_OFFERING_GRADE'] 	= $res_grade->fields['PK_COURSE_OFFERING_GRADE'];
			$STUDENT_GRADE['PK_COURSE_OFFERING']		= $STUDENT_COURSE['PK_COURSE_OFFERING'];
			$STUDENT_GRADE['PK_STUDENT_ENROLLMENT'] 	= $PK_STUDENT_ENROLLMENT;
			$STUDENT_GRADE['PK_STUDENT_MASTER'] 	 	= $res_en->fields['PK_STUDENT_MASTER'];;
			$STUDENT_GRADE['PK_ACCOUNT'] 			 	= $_SESSION['PK_ACCOUNT'];
			$STUDENT_GRADE['CREATED_BY']  			 	= $_SESSION['PK_USER'];
			$STUDENT_GRADE['CREATED_ON']  			 	= date("Y-m-d H:i");
			db_perform('S_STUDENT_GRADE', $STUDENT_GRADE, 'insert');
			
			$res_grade->MoveNext();
		}
		
		if($SEND_ENROLLED_IN_CLASS_EMAIL_TEMPLATE > 0) {
			send_enrolled_in_class_mail($PK_STUDENT_COURSE,$SEND_ENROLLED_IN_CLASS_EMAIL_TEMPLATE);
		}
		if($SEND_ENROLLED_IN_CLASS_EMAIL_TEMPLATE > 0) {
			send_enrolled_in_class_text($PK_STUDENT_COURSE,$SEND_ENROLLED_IN_CLASS_TEXT_TEMPLATE);
		}
		
		$db->Execute("UPDATE S_STUDENT_ENROLLMENT SET COURSE_ASSIGNED = 1 WHERE PK_STUDENT_MASTER = '".$res_en->fields['PK_STUDENT_MASTER']."' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' "); 
		
		/* Ticket #1897 */
		$res_grade_1 = $db->Execute("select PK_STUDENT_COURSE, RETAKE_UPDATE, RETAKE_GRADE FROM S_STUDENT_COURSE, S_COURSE_OFFERING, S_GRADE WHERE S_STUDENT_COURSE.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND S_COURSE_OFFERING.PK_COURSE_OFFERING = S_STUDENT_COURSE.PK_COURSE_OFFERING AND PK_COURSE = '$PK_COURSE' AND S_COURSE_OFFERING.PK_COURSE_OFFERING != '$STUDENT_COURSE[PK_COURSE_OFFERING]' AND S_GRADE.PK_GRADE = FINAL_GRADE ");
		while (!$res_grade_1->EOF) {
			if($res_grade_1->fields['RETAKE_UPDATE'] == 1 && $res_grade_1->fields['RETAKE_GRADE'] > 0){
				$OLD_PK_STUDENT_COURSE 	= $res_grade_1->fields['PK_STUDENT_COURSE'];
				$RETAKE_GRADE 			= $res_grade_1->fields['RETAKE_GRADE'];
				
				$db->Execute("UPDATE S_STUDENT_COURSE SET FINAL_GRADE = '$RETAKE_GRADE' WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' AND PK_STUDENT_COURSE = '$OLD_PK_STUDENT_COURSE' ");
			}
			$res_grade_1->MoveNext();
		}
		/* Ticket #1897 */
	}
	return $PK_STUDENT_COURSE;
}