<? function grade_input($PK_STUDENT_PROGRAM_GRADE,$PK_STUDENT_ENROLLMENT,$GRADE,$PK_COURSE_OFFERING_STUDENT_STATUS,$INACTIVE,$MIDPOINT_GRADE,$DETAIL,$NUMERIC_GRADE,$PK_CAMPUS_PROGRAM) {
	global $db;
	
	$STUDENT_PROGRAM_GRADE = array();
	$STUDENT_PROGRAM_GRADE['PK_STUDENT_ENROLLMENT']  			= $PK_STUDENT_ENROLLMENT;
	$STUDENT_PROGRAM_GRADE['GRADE']  							= $GRADE;
	$STUDENT_PROGRAM_GRADE['PK_COURSE_OFFERING_STUDENT_STATUS'] = $PK_COURSE_OFFERING_STUDENT_STATUS;
	$STUDENT_PROGRAM_GRADE['INACTIVE']  						= $INACTIVE;
	$STUDENT_PROGRAM_GRADE['MIDPOINT_GRADE']  					= $MIDPOINT_GRADE;
	$STUDENT_PROGRAM_GRADE['DETAIL']  							= $DETAIL;
	$STUDENT_PROGRAM_GRADE['NUMERIC_GRADE']  					= $NUMERIC_GRADE;
	
	if($STUDENT_PROGRAM_GRADE['INACTIVE'] != '')
		$STUDENT_PROGRAM_GRADE['INACTIVE'] = date("Y-m-d",strtotime($STUDENT_PROGRAM_GRADE['INACTIVE']));
	else
		$STUDENT_PROGRAM_GRADE['INACTIVE'] = '';
		
	$res_stu = $db->Execute("SELECT PK_STUDENT_MASTER FROM S_STUDENT_ENROLLMENT WHERE PK_STUDENT_ENROLLMENT = '$STUDENT_PROGRAM_GRADE[PK_STUDENT_ENROLLMENT]' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
	$STUDENT_PROGRAM_GRADE['PK_STUDENT_MASTER'] = $res_stu->fields['PK_STUDENT_MASTER'];
	
	if($PK_STUDENT_PROGRAM_GRADE == ''){
		$STUDENT_PROGRAM_GRADE['PK_CAMPUS_PROGRAM']  = $PK_CAMPUS_PROGRAM;
		$STUDENT_PROGRAM_GRADE['PK_ACCOUNT']  		 = $_SESSION['PK_ACCOUNT'];
		$STUDENT_PROGRAM_GRADE['CREATED_BY']  		 = $_SESSION['PK_USER'];
		$STUDENT_PROGRAM_GRADE['CREATED_ON']  		 = date("Y-m-d H:i");
		db_perform('S_STUDENT_PROGRAM_GRADE', $STUDENT_PROGRAM_GRADE, 'insert');

		$PK_STUDENT_PROGRAM_GRADE = $db->insert_ID();
	} else {
		$STUDENT_PROGRAM_GRADE['EDITED_BY']	 = $_SESSION['PK_USER'];
		$STUDENT_PROGRAM_GRADE['EDITED_ON']  = date("Y-m-d H:i");
		db_perform('S_STUDENT_PROGRAM_GRADE', $STUDENT_PROGRAM_GRADE, 'update'," PK_STUDENT_PROGRAM_GRADE = '$PK_STUDENT_PROGRAM_GRADE' AND PK_CAMPUS_PROGRAM = '$PK_CAMPUS_PROGRAM' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	}
	
	return $PK_STUDENT_PROGRAM_GRADE;	
} ?>