<?php
function student_ledger($data){
	global $db;
	
	$PK_STUDENT_MASTER 		 		= $data['PK_STUDENT_MASTER'];
	$PK_STUDENT_ENROLLMENT 	 		= $data['PK_STUDENT_ENROLLMENT'];
	$PK_STUDENT_FEE_BUDGET 	 		= $data['PK_STUDENT_FEE_BUDGET'];
	$PK_AR_LEDGER_CODE 		 		= $data['PK_AR_LEDGER_CODE'];
	$PK_PAYMENT_BATCH_DETAIL 		= $data['PK_PAYMENT_BATCH_DETAIL'];
	$PK_STUDENT_DISBURSEMENT 		= $data['PK_STUDENT_DISBURSEMENT'];
	$PK_MISC_BATCH_DETAIL	 		= $data['PK_MISC_BATCH_DETAIL'];
	$PK_TUITION_BATCH_DETAIL 		= $data['PK_TUITION_BATCH_DETAIL'];
	$PK_STUDENT_CREDIT_CARD_PAYMENT = $data['PK_STUDENT_CREDIT_CARD_PAYMENT'];
	$AMOUNT 				 		= $data['AMOUNT'];
	$DATE 					 		= $data['DATE'];
	if($_SESSION['PK_ACCOUNT'] != '')
		$PK_ACCOUNT = $_SESSION['PK_ACCOUNT'];
	else
		$PK_ACCOUNT = $data['PK_ACCOUNT'];
	
	if($PK_STUDENT_FEE_BUDGET > 0) {
		$res = $db->Execute("select PK_STUDENT_LEDGER,PK_AR_LEDGER_CODE,DEBIT,PK_STUDENT_ENROLLMENT from S_STUDENT_LEDGER WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND PK_STUDENT_FEE_BUDGET = '$PK_STUDENT_FEE_BUDGET' ");
		
		if($res->RecordCount() == 0) {
			$STUDENT_LEDGER['PK_STUDENT_FEE_BUDGET'] = $PK_STUDENT_FEE_BUDGET;
			$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] 	 = $PK_AR_LEDGER_CODE;
			$STUDENT_LEDGER['DEBIT'] 			 	 = $AMOUNT;
			$STUDENT_LEDGER['TRANSACTION_DATE']  	 = $DATE;
			$STUDENT_LEDGER['PK_STUDENT_ENROLLMENT'] = $PK_STUDENT_ENROLLMENT;
			$STUDENT_LEDGER['PK_STUDENT_MASTER'] 	 = $PK_STUDENT_MASTER;
			$STUDENT_LEDGER['PK_ACCOUNT'] 			 = $PK_ACCOUNT;
			$STUDENT_LEDGER['CREATED_BY']  			 = $_SESSION['PK_USER'];
			$STUDENT_LEDGER['CREATED_ON']  			 = date("Y-m-d H:i");
			db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'insert');
		} else {
			$update = 0;
			if($res->fields['PK_AR_LEDGER_CODE'] != $PK_AR_LEDGER_CODE || $res->fields['DEBIT'] != $AMOUNT || $res->fields['PK_STUDENT_ENROLLMENT'] != $PK_STUDENT_ENROLLMENT )
				$update = 1;
				
			if($update == 1) {
				$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] = $PK_AR_LEDGER_CODE;
				$STUDENT_LEDGER['DEBIT'] 			 = $AMOUNT;
				$STUDENT_LEDGER['EDITED_BY']  		 = $_SESSION['PK_USER'];
				$STUDENT_LEDGER['EDITED_ON']  		 = date("Y-m-d H:i");
				db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'update'," PK_STUDENT_LEDGER = '".$res->fields['PK_STUDENT_LEDGER']."' ");
			}
		}
	} else if($PK_STUDENT_DISBURSEMENT > 0) {
		/* Ticket # 1026*/ 
		$res_disb_1 = $db->Execute("SELECT GROSS_AMOUNT, FEE_AMOUNT FROM S_STUDENT_DISBURSEMENT WHERE PK_STUDENT_DISBURSEMENT = '$PK_STUDENT_DISBURSEMENT' AND PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
		$STUDENT_LEDGER['DISBURSEMENT_GROSS'] 	= $res_disb_1->fields['GROSS_AMOUNT'];
		$STUDENT_LEDGER['DISBURSEMENT_FEE'] 	= $res_disb_1->fields['FEE_AMOUNT'];
		/* Ticket # 1026*/ 
		
		$STUDENT_LEDGER['PK_STUDENT_DISBURSEMENT'] 			= $PK_STUDENT_DISBURSEMENT;
		$STUDENT_LEDGER['PK_STUDENT_CREDIT_CARD_PAYMENT'] 	= $PK_STUDENT_CREDIT_CARD_PAYMENT;
		$STUDENT_LEDGER['PK_PAYMENT_BATCH_DETAIL'] 			= $PK_PAYMENT_BATCH_DETAIL;
		$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] 	 			= $PK_AR_LEDGER_CODE;
		$STUDENT_LEDGER['CREDIT'] 			 	 			= $AMOUNT;
		$STUDENT_LEDGER['TRANSACTION_DATE']  	 			= $DATE;
		
		$res_led = $res = $db->Execute("select PK_STUDENT_LEDGER from S_STUDENT_LEDGER WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND PK_PAYMENT_BATCH_DETAIL = '$PK_PAYMENT_BATCH_DETAIL' AND PK_PAYMENT_BATCH_DETAIL > 0 AND PK_STUDENT_ENROLLMENT = '$PK_STUDENT_ENROLLMENT' ");
		if($res_led->RecordCount() == 0) {
			$STUDENT_LEDGER['PK_STUDENT_ENROLLMENT'] 			= $PK_STUDENT_ENROLLMENT;
			$STUDENT_LEDGER['PK_STUDENT_MASTER'] 	 			= $PK_STUDENT_MASTER;
			$STUDENT_LEDGER['PK_ACCOUNT'] 			 			= $PK_ACCOUNT;
			$STUDENT_LEDGER['CREATED_BY']  			 			= $_SESSION['PK_USER'];
			$STUDENT_LEDGER['CREATED_ON']  				 		= date("Y-m-d H:i");
			db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'insert');
		} else {
			$STUDENT_LEDGER['EDITED_BY']  		 = $_SESSION['PK_USER'];
			$STUDENT_LEDGER['EDITED_ON']  		 = date("Y-m-d H:i");
			db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'update'," PK_STUDENT_LEDGER = '".$res_led->fields['PK_STUDENT_LEDGER']."' ");
		}
	} else if($PK_MISC_BATCH_DETAIL > 0) {
		$res = $db->Execute("select PK_STUDENT_LEDGER,PK_AR_LEDGER_CODE,DEBIT,CREDIT,TRANSACTION_DATE from S_STUDENT_LEDGER WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND PK_MISC_BATCH_DETAIL = '$PK_MISC_BATCH_DETAIL' ");
		
		if($res->RecordCount() == 0) {
			$STUDENT_LEDGER['PK_MISC_BATCH_DETAIL']  = $PK_MISC_BATCH_DETAIL;
			$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] 	 = $PK_AR_LEDGER_CODE;
			$STUDENT_LEDGER['DEBIT'] 			 	 = $data['DEBIT_AMOUNT'];
			$STUDENT_LEDGER['CREDIT'] 			 	 = $data['CREDIT_AMOUNT'];;
			$STUDENT_LEDGER['TRANSACTION_DATE']  	 = $DATE;
			$STUDENT_LEDGER['PK_STUDENT_ENROLLMENT'] = $PK_STUDENT_ENROLLMENT;
			$STUDENT_LEDGER['PK_STUDENT_MASTER'] 	 = $PK_STUDENT_MASTER;
			$STUDENT_LEDGER['PK_ACCOUNT'] 			 = $PK_ACCOUNT;
			$STUDENT_LEDGER['CREATED_BY']  			 = $_SESSION['PK_USER'];
			$STUDENT_LEDGER['CREATED_ON']  			 = date("Y-m-d H:i");
			db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'insert');
		} else {
			$update = 0;
			if($res->fields['PK_AR_LEDGER_CODE'] != $PK_AR_LEDGER_CODE || $res->fields['DEBIT'] != $data['DEBIT_AMOUNT'] || $res->fields['CREDIT'] != $data['CREDIT_AMOUNT'] || $res->fields['TRANSACTION_DATE'] != $DATE)
				$update = 1;
				
			if($update == 1) {
				$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] = $PK_AR_LEDGER_CODE;
				$STUDENT_LEDGER['DEBIT'] 			 = $data['DEBIT_AMOUNT'];
				$STUDENT_LEDGER['CREDIT'] 			 = $data['CREDIT_AMOUNT'];
				$STUDENT_LEDGER['TRANSACTION_DATE']  = $DATE;
				$STUDENT_LEDGER['EDITED_BY']  		 = $_SESSION['PK_USER'];
				$STUDENT_LEDGER['EDITED_ON']  		 = date("Y-m-d H:i");
				db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'update'," PK_STUDENT_LEDGER = '".$res->fields['PK_STUDENT_LEDGER']."' ");
			}
		}
	} else if($PK_TUITION_BATCH_DETAIL > 0) {
		$res = $db->Execute("select PK_STUDENT_LEDGER,PK_AR_LEDGER_CODE,DEBIT,CREDIT,TRANSACTION_DATE from S_STUDENT_LEDGER WHERE PK_ACCOUNT = '$PK_ACCOUNT' AND PK_TUITION_BATCH_DETAIL = '$PK_TUITION_BATCH_DETAIL' ");
		
		if($res->RecordCount() == 0) {
			$STUDENT_LEDGER['PK_TUITION_BATCH_DETAIL']  = $PK_TUITION_BATCH_DETAIL;
			$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] 	 	= $PK_AR_LEDGER_CODE;
			$STUDENT_LEDGER['DEBIT'] 			 	 	= $data['AMOUNT'];
			$STUDENT_LEDGER['TRANSACTION_DATE']  	 	= $DATE;
			$STUDENT_LEDGER['PK_STUDENT_ENROLLMENT'] 	= $PK_STUDENT_ENROLLMENT;
			$STUDENT_LEDGER['PK_STUDENT_MASTER'] 	 	= $PK_STUDENT_MASTER;
			$STUDENT_LEDGER['PK_ACCOUNT'] 			 	= $PK_ACCOUNT;
			$STUDENT_LEDGER['CREATED_BY']  			 	= $_SESSION['PK_USER'];
			$STUDENT_LEDGER['CREATED_ON']  			 	= date("Y-m-d H:i");
			db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'insert');
		} else {
			$update = 0;
			if($res->fields['PK_AR_LEDGER_CODE'] != $PK_AR_LEDGER_CODE || $res->fields['DEBIT'] != $data['AMOUNT'] || $res->fields['TRANSACTION_DATE'] != $DATE)
				$update = 1;
				
			if($update == 1) {
				$STUDENT_LEDGER['PK_AR_LEDGER_CODE'] = $PK_AR_LEDGER_CODE;
				$STUDENT_LEDGER['DEBIT'] 			 = $data['AMOUNT'];
				$STUDENT_LEDGER['TRANSACTION_DATE']  = $DATE;
				$STUDENT_LEDGER['EDITED_BY']  		 = $_SESSION['PK_USER'];
				$STUDENT_LEDGER['EDITED_ON']  		 = date("Y-m-d H:i");
				db_perform('S_STUDENT_LEDGER', $STUDENT_LEDGER, 'update'," PK_STUDENT_LEDGER = '".$res->fields['PK_STUDENT_LEDGER']."' ");
			}
		}
	}
}

function delete_student_ledger($data){
	global $db;
	
	$cond = " 1 = 0 ";
	if($data['PK_STUDENT_FEE_BUDGET'] > 0)
		$cond = " AND PK_STUDENT_FEE_BUDGET = '$data[PK_STUDENT_FEE_BUDGET]' ";
	else if($data['PK_STUDENT_DISBURSEMENT'] > 0)
		$cond = " AND PK_STUDENT_DISBURSEMENT = '$data[PK_STUDENT_DISBURSEMENT]' ";
	else if($data['PK_PAYMENT_BATCH_DETAIL'] > 0)
		$cond = " AND PK_PAYMENT_BATCH_DETAIL = '$data[PK_PAYMENT_BATCH_DETAIL]' ";
	else if($data['PK_MISC_BATCH_DETAIL'] > 0)
		$cond = " AND PK_MISC_BATCH_DETAIL = '$data[PK_MISC_BATCH_DETAIL]' ";
	else if($data['PK_TUITION_BATCH_DETAIL'] > 0)
		$cond = " AND PK_TUITION_BATCH_DETAIL = '$data[PK_TUITION_BATCH_DETAIL]' ";
		
	$db->Execute("DELETE from S_STUDENT_LEDGER WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' $cond ");

}