<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("../language/student.php");
require_once("check_access.php");

$REGISTRAR_ACCESS 	= check_access('REGISTRAR_ACCESS');

if($REGISTRAR_ACCESS == 0) {
	header("location:../index");
	exit;
}

$res = $db->Execute("SELECT ENABLE_ETHINK FROM Z_ACCOUNT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
if($res->fields['ENABLE_ETHINK'] == 0) {
	header("location:../index");
	exit;
}

$timezone = $_SESSION['PK_TIMEZONE'];
if($timezone == '' || $timezone == 0) {
	$res = $db->Execute("SELECT PK_TIMEZONE FROM Z_ACCOUNT WHERE  PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	$timezone = $res->fields['PK_TIMEZONE'];
	if($timezone == '' || $timezone == 0)
		$timezone = 4;
}

$res_tz = $db->Execute("SELECT TIMEZONE FROM Z_TIMEZONE WHERE  PK_TIMEZONE = '$timezone' ");

$page = isset($_POST['page']) ? intval($_POST['page']) : 1;
$rows = isset($_POST['rows']) ? intval($_POST['rows']) : 10;
$sort = isset($_POST['sort']) ? strval($_POST['sort']) : 'CAMPUS_CODE ASC, S_TERM_MASTER.BEGIN_DATE DESC, COURSE_CODE ASC, SESSION ASC, S_STUDENT_MASTER.LAST_NAME ASC, S_STUDENT_MASTER.FIRST_NAME ASC ';  
$order = isset($_POST['order']) ? strval($_POST['order']) : '';

$PK_CAMPUS 			= isset($_REQUEST['PK_CAMPUS']) ? ($_REQUEST['PK_CAMPUS']) : '';
$PK_TERM_MASTER 	= isset($_REQUEST['PK_TERM_MASTER']) ? ($_REQUEST['PK_TERM_MASTER']) : '';
$PK_COURSE 			= isset($_REQUEST['PK_COURSE']) ? ($_REQUEST['PK_COURSE']) : '';

$PK_SESSION 		= isset($_REQUEST['PK_SESSION']) ? ($_REQUEST['PK_SESSION']) : '';
$INSTRUCTOR 		= isset($_REQUEST['INSTRUCTOR']) ? ($_REQUEST['INSTRUCTOR']) : '';
$SENT 				= isset($_REQUEST['SENT']) ? ($_REQUEST['SENT']) : '';
$MESSAGE_TYPE 		= isset($_REQUEST['MESSAGE_TYPE']) ? ($_REQUEST['MESSAGE_TYPE']) : '';
$SEARCH 			= isset($_REQUEST['SEARCH']) ? mysql_real_escape_string($_REQUEST['SEARCH']) : '';
$CURRENT_ENROLLMENT_ONLY = isset($_REQUEST['CURRENT_ENROLLMENT_ONLY']) ? mysql_real_escape_string($_REQUEST['CURRENT_ENROLLMENT_ONLY']) : '';

$offset = ($page-1)*$rows;
	
$result = array();
//AND IS_ACTIVE_ENROLLMENT = 1
$where = " S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_STUDENT_ACADEMICS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND ARCHIVED = 0  AND S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT   AND S_COURSE_OFFERING.LMS_ACTIVE = '1' AND  S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND S_STUDENT_COURSE.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_TERM_MASTER.LMS_ACTIVE = '1' AND S_STUDENT_MASTER.PK_STUDENT_MASTER = S_STUDENT_MASTER_ETHINK.PK_STUDENT_MASTER AND S_STUDENT_MASTER_ETHINK.SUCCESS = 1 AND S_STUDENT_MASTER_ETHINK.ETHINK_ID != '' ";

$table = "";

if($CURRENT_ENROLLMENT_ONLY == "true")
	$where .= " AND IS_ACTIVE_ENROLLMENT = 1 ";

if($PK_TERM_MASTER != '') {
	$PK_TERM_MASTER1 = implode(",",$PK_TERM_MASTER);
	$where .= " AND S_COURSE_OFFERING.PK_TERM_MASTER IN ($PK_TERM_MASTER1) ";
}

if(!empty($PK_CAMPUS) || $_SESSION['PK_ROLES'] == 3) {
	if($PK_CAMPUS != '') {
		$PK_CAMPUS1 = implode(",",$PK_CAMPUS);
		$where .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS1) ";
	} else
		$where .= " AND (S_STUDENT_CAMPUS.PK_CAMPUS IN ($_SESSION[PK_CAMPUS],0)  ) ";
}

if(!empty($PK_COURSE) != '')
	$where .= " AND S_COURSE_OFFERING.PK_COURSE IN (".implode(",",$PK_COURSE).") ";
	
if(!empty($PK_SESSION) != '')
	$where .= " AND S_COURSE_OFFERING.PK_SESSION IN (".implode(",",$PK_SESSION).") ";
	
if(!empty($INSTRUCTOR) != '')
	$where .= " AND S_COURSE_OFFERING.INSTRUCTOR IN (".implode(",",$INSTRUCTOR).") ";

if($SEARCH != '') {
	$where .= " AND (COURSE_CODE like '%$SEARCH%' OR CAMPUS_CODE LIKE '%$SEARCH%' OR DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE,'%m/%d/%Y') LIKE '%$SEARCH%' OR CONCAT(EMP_INSTRUCTOR.FIRST_NAME,' ',EMP_INSTRUCTOR.LAST_NAME) LIKE '%$SEARCH%' OR SESSION LIKE '%$SEARCH%' OR LMS_CODE LIKE '%$SEARCH%' OR EMP_INSTRUCTOR.FIRST_NAME LIKE '%$SEARCH%' OR EMP_INSTRUCTOR.LAST_NAME LIKE '%$SEARCH%' OR CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) like '%$SEARCH%' OR S_STUDENT_MASTER.FIRST_NAME LIKE '%$SEARCH%' OR S_STUDENT_MASTER.LAST_NAME LIKE '%$SEARCH%' )";
}

if($SENT == 1)
	$where .= " AND S_STUDENT_COURSE.PK_STUDENT_COURSE IN (SELECT PK_STUDENT_COURSE FROM S_STUDENT_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
else if($SENT == 2)
	$where .= " AND S_STUDENT_COURSE.PK_STUDENT_COURSE NOT IN (SELECT PK_STUDENT_COURSE FROM S_STUDENT_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";

$table = "";
if($MESSAGE_TYPE == 1) {
	$table = ", S_STUDENT_COURSE_ETHINK";
	$where .= " AND S_STUDENT_COURSE_ETHINK.PK_STUDENT_COURSE = S_STUDENT_COURSE.PK_STUDENT_COURSE AND PK_STUDENT_COURSE_ETHINK IN (SELECT MAX(PK_STUDENT_COURSE_ETHINK)  FROM S_STUDENT_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_STUDENT_COURSE ) AND S_STUDENT_COURSE_ETHINK.SUCCESS = 1 ";
} else if($MESSAGE_TYPE == 2) { 
	$table = ", S_STUDENT_COURSE_ETHINK";
	$where .= " AND S_STUDENT_COURSE_ETHINK.PK_STUDENT_COURSE = S_STUDENT_COURSE.PK_STUDENT_COURSE AND PK_STUDENT_COURSE_ETHINK IN (SELECT MAX(PK_STUDENT_COURSE_ETHINK)  FROM S_STUDENT_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_STUDENT_COURSE ) AND S_STUDENT_COURSE_ETHINK.SUCCESS != 1 ";
}

$rs = mysql_query("SELECT S_STUDENT_MASTER.PK_STUDENT_MASTER 
FROM 
S_STUDENT_MASTER_ETHINK, S_STUDENT_MASTER, S_STUDENT_ACADEMICS, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS
, S_STUDENT_COURSE, S_COURSE_OFFERING  
LEFT JOIN S_EMPLOYEE_MASTER AS EMP_INSTRUCTOR ON EMP_INSTRUCTOR.PK_EMPLOYEE_MASTER = S_COURSE_OFFERING.INSTRUCTOR 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
$table
WHERE " . $where. " GROUP BY S_STUDENT_COURSE.PK_STUDENT_COURSE ")or die(mysql_error());
$row = mysql_fetch_row($rs);
$result["total"] = mysql_num_rows($rs);

$query = "SELECT S_STUDENT_COURSE.PK_COURSE_OFFERING,S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT,S_STUDENT_MASTER.PK_STUDENT_MASTER,PK_REPRESENTATIVE,  CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) AS NAME, STUDENT_ID, S_TERM_MASTER.BEGIN_DATE,STUDENT_STATUS, CONCAT(M_CAMPUS_PROGRAM.CODE,' - ',M_CAMPUS_PROGRAM.DESCRIPTION) as PROGRAM, COURSE_CODE,CONCAT(SUBSTRING(SESSION, 1, 1),' - ',SESSION_NO) as SESSION, FINAL_GRADE_GRADE, S_STUDENT_COURSE.PK_STUDENT_COURSE, CAMPUS_CODE, LMS_CODE,CONCAT(EMP_INSTRUCTOR.LAST_NAME,', ',EMP_INSTRUCTOR.FIRST_NAME) AS INSTRUCTOR_NAME   
FROM 
S_STUDENT_MASTER_ETHINK, S_STUDENT_MASTER, S_STUDENT_ACADEMICS, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS
, S_STUDENT_COURSE, S_COURSE_OFFERING  
LEFT JOIN S_EMPLOYEE_MASTER AS EMP_INSTRUCTOR ON EMP_INSTRUCTOR.PK_EMPLOYEE_MASTER = S_COURSE_OFFERING.INSTRUCTOR 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
$table 
WHERE " . $where ." GROUP BY S_STUDENT_COURSE.PK_STUDENT_COURSE order by $sort $order " ;
//echo $query;exit;	
$_SESSION['query'] = $query;
$rs = mysql_query($query. " limit $offset,$rows")or die(mysql_error());	
	
$items = array();
while($row = mysql_fetch_array($rs)){
	$PK_STUDENT_ENROLLMENT = $row['PK_STUDENT_ENROLLMENT'];
	$PK_STUDENT_COURSE 	   = $row['PK_STUDENT_COURSE'];

	if($row['BEGIN_DATE'] != '0000-00-00' && $row['BEGIN_DATE'] != '')
		$row['BEGIN_DATE'] = date("m/d/Y",strtotime($row['BEGIN_DATE']));
	else
		$row['BEGIN_DATE'] = '';
		
	$res1 = $db->Execute("SELECT S_STUDENT_COURSE_ETHINK.CREATED_ON, CONCAT(LAST_NAME,', ',FIRST_NAME) as NAME, MESSAGE FROM S_STUDENT_COURSE_ETHINK LEFT JOIN Z_USER ON Z_USER.PK_USER = S_STUDENT_COURSE_ETHINK.CREATED_BY AND PK_USER_TYPE IN (1,2) LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = Z_USER.ID WHERE PK_STUDENT_COURSE = '$PK_STUDENT_COURSE' ORDER BY PK_STUDENT_COURSE_ETHINK DESC ");	
	
	if($res1->RecordCount() == 0){
		$row['SENT'] 		= 'N';
		$row['SENT_ON'] 	= '';
		$row['SENT_BY'] 	= '';
		$row['MESSAGE'] 	= '';
	} else {
		//if($res1->fields['SUCCESS'] == 1)
			$row['SENT'] = 'Y';
		/*else
			$row['SENT'] = 'N';*/
			
		$row['SENT_ON'] 	= convert_to_user_date($res1->fields['CREATED_ON'],'m/d/Y h:i A',$res_tz->fields['TIMEZONE'],date_default_timezone_get());
		$row['SENT_BY'] 	= $res1->fields['NAME'];
		$row['MESSAGE'] 	= $res1->fields['MESSAGE'];
	}
	
	$row['SELECT'] = '<input type="checkbox" name="CHK_PK_STUDENT_COURSE[]" id="CHK_PK_STUDENT_COURSE_'.$row['PK_STUDENT_COURSE'].'" value="'.$row['PK_STUDENT_COURSE'].'_'.$row['PK_STUDENT_MASTER'].'_'.$row['PK_STUDENT_ENROLLMENT'].'" onchange="show_btn()" >';
	
	array_push($items, $row);
}
$result["rows"] = $items;
echo json_encode($result);