<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("../language/student.php");
require_once("check_access.php");

$REGISTRAR_ACCESS 	= check_access('REGISTRAR_ACCESS');

$res = $db->Execute("SELECT ENABLE_CANVAS FROM Z_ACCOUNT WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' "); 
if($res->fields['ENABLE_CANVAS'] == 0) {
	header("location:../index");
	exit;
}

if($REGISTRAR_ACCESS == 0) {
	header("location:../index");
	exit;
}

$timezone = $_SESSION['PK_TIMEZONE'];
if($timezone == '' || $timezone == 0) {
	$res = $db->Execute("SELECT PK_TIMEZONE FROM Z_ACCOUNT WHERE  PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	$timezone = $res->fields['PK_TIMEZONE'];
	if($timezone == '' || $timezone == 0)
		$timezone = 4;
}

$res_tz = $db->Execute("SELECT TIMEZONE FROM Z_TIMEZONE WHERE  PK_TIMEZONE = '$timezone' ");

$page = isset($_POST['page']) ? intval($_POST['page']) : 1;
$rows = isset($_POST['rows']) ? intval($_POST['rows']) : 10;
$sort = isset($_POST['sort']) ? strval($_POST['sort']) : ' CAMPUS_CODE ASC, S_STUDENT_MASTER.LAST_NAME ASC, S_STUDENT_MASTER.FIRST_NAME ASC ';  
$order = isset($_POST['order']) ? strval($_POST['order']) : '';

$PK_CAMPUS			 	= isset($_REQUEST['PK_CAMPUS']) ? ($_REQUEST['PK_CAMPUS']) : '';		
$SEARCH 				= isset($_REQUEST['SEARCH']) ? mysql_real_escape_string($_REQUEST['SEARCH']) : '';
$PK_TERM_MASTER			= isset($_REQUEST['PK_TERM_MASTER']) ? ($_REQUEST['PK_TERM_MASTER']) : '';
$PK_COURSE_OFFERING		= isset($_REQUEST['PK_COURSE_OFFERING']) ? ($_REQUEST['PK_COURSE_OFFERING']) : '';
$PK_STUDENT_STATUS		= isset($_REQUEST['PK_STUDENT_STATUS']) ? ($_REQUEST['PK_STUDENT_STATUS']) : '';
$PK_CAMPUS_PROGRAM		= isset($_REQUEST['PK_CAMPUS_PROGRAM']) ? ($_REQUEST['PK_CAMPUS_PROGRAM']) : '';
$SENT					= isset($_REQUEST['SENT']) ? ($_REQUEST['SENT']) : '';
$MESSAGE_TYPE			= isset($_REQUEST['MESSAGE_TYPE']) ? ($_REQUEST['MESSAGE_TYPE']) : '';

$offset = ($page-1)*$rows;

$result = array();
//AND S_STUDENT_MASTER.PK_STUDENT_MASTER NOT IN (SELECT PK_STUDENT_MASTER FROM S_STUDENT_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND CANVAS_ID != '')
$where = " S_STUDENT_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_STUDENT_ACADEMICS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND S_STUDENT_ENROLLMENT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND ARCHIVED = 0  AND IS_ACTIVE_ENROLLMENT = 1 AND S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT   AND S_COURSE_OFFERING.LMS_ACTIVE = '1' AND  S_STUDENT_COURSE.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT AND S_STUDENT_COURSE.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_TERM_MASTER.LMS_ACTIVE = '1' AND STUDENT_ID != '' ";

if($SEARCH != '') {
	$sub = "";
	$MOBILE_NO = preg_replace( '/[^0-9]/', '', $SEARCH);
	if($MOBILE_NO != '') {
		//$sub = " OR (REPLACE(REPLACE(REPLACE(REPLACE(CELL_PHONE, '(', ''), ')', ''), '-', ''),' ','') LIKE '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(HOME_PHONE, '(', ''), ')', ''), '-', ''),' ','') LIKE '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(WORK_PHONE, '(', ''), ')', ''), '-', ''),' ','') LIKE '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(WORK_PHONE, '(', ''), ')', ''), '-', ''),' ','') LIKE '$OTHER_PHONE') ";
		$sub = " OR (REPLACE(REPLACE(REPLACE(REPLACE(CELL_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(HOME_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') OR (REPLACE(REPLACE(REPLACE(REPLACE(WORK_PHONE, '(', ''), ')', ''), '-', ''),' ','') = '$MOBILE_NO') ";
	}
	
	//$where .= " AND (STUDENT_ID like '%$SEARCH%' OR CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) like '%$SEARCH%' $sub OR S_STUDENT_CONTACT.EMAIL like '%$SEARCH%' OR S_STUDENT_CONTACT.EMAIL_OTHER like '%$SEARCH%'  )";
	$where .= " AND (CAMPUS_CODE like '%$SEARCH%' OR CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) like '%$SEARCH%' OR S_STUDENT_MASTER.LAST_NAME like '%$SEARCH%'  OR S_STUDENT_MASTER.FIRST_NAME like '%$SEARCH%' OR S_STUDENT_CONTACT.EMAIL like '%$SEARCH%' OR DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE,'%m/%d/%Y') LIKE '%$SEARCH%' OR M_CAMPUS_PROGRAM.CODE  like '%$SEARCH%' OR STUDENT_STATUS like '%$SEARCH%' )";
}

if($PK_TERM_MASTER != '') {
	$PK_TERM_MASTER1 = implode(",",$PK_TERM_MASTER);
	$where .= " AND S_COURSE_OFFERING.PK_TERM_MASTER IN ($PK_TERM_MASTER1) ";
}

if($PK_CAMPUS_PROGRAM != '') {
	$PK_CAMPUS_PROGRAM1 = implode(",",$PK_CAMPUS_PROGRAM);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM IN ($PK_CAMPUS_PROGRAM1) ";
}

if(!empty($PK_CAMPUS) || $_SESSION['PK_ROLES'] == 3) {

	if($PK_CAMPUS != '') {
		$PK_CAMPUS1 = implode(",",$PK_CAMPUS);
		$where .= " AND S_STUDENT_CAMPUS.PK_CAMPUS IN ($PK_CAMPUS1) ";
	} else
		$where .= " AND (S_STUDENT_CAMPUS.PK_CAMPUS IN ($_SESSION[PK_CAMPUS],0)  ) ";
}

if(!empty($PK_COURSE_OFFERING)) {
	$PK_COURSE_OFFERING1 = implode(",",$PK_COURSE_OFFERING);
	$where .= " AND S_COURSE_OFFERING.PK_COURSE_OFFERING IN ($PK_COURSE_OFFERING1) ";
}

if(!empty($PK_STUDENT_STATUS)){
	$PK_STUDENT_STATUS = implode(",",$PK_STUDENT_STATUS);
	$where .= " AND S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS IN (".$PK_STUDENT_STATUS.") ";
}

if($SENT == 1)
	$where .= " AND S_STUDENT_MASTER.PK_STUDENT_MASTER  IN (SELECT PK_STUDENT_MASTER FROM S_STUDENT_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
else if($SENT == 2)
	$where .= " AND S_STUDENT_MASTER.PK_STUDENT_MASTER  NOT IN (SELECT PK_STUDENT_MASTER FROM S_STUDENT_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
	
$table = "";
if($MESSAGE_TYPE == 1) {
	$table = ", S_STUDENT_MASTER_CANVAS ";
	$where .= " AND S_STUDENT_MASTER_CANVAS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_MASTER_CANVAS IN (SELECT MAX(PK_STUDENT_MASTER_CANVAS)  FROM S_STUDENT_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_STUDENT_MASTER_CANVAS ) AND SUCCESS = 1 ";
} else if($MESSAGE_TYPE == 2) { 
	$table = ", S_STUDENT_MASTER_CANVAS ";
	$where .= " AND S_STUDENT_MASTER_CANVAS.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_MASTER_CANVAS IN (SELECT MAX(PK_STUDENT_MASTER_CANVAS)  FROM S_STUDENT_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_STUDENT_MASTER_CANVAS ) AND SUCCESS != 1 ";
}

$rs = mysql_query("SELECT S_STUDENT_MASTER.PK_STUDENT_MASTER 
FROM 
S_STUDENT_MASTER
LEFT JOIN S_STUDENT_CONTACT ON S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = 1 
, S_STUDENT_ACADEMICS, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS
, S_STUDENT_COURSE, S_COURSE_OFFERING  
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
$table
WHERE " . $where. " GROUP BY S_STUDENT_MASTER.PK_STUDENT_MASTER")or die(mysql_error());
$row = mysql_fetch_row($rs);
$result["total"] = mysql_num_rows($rs);
//DIAM-1471
$query = "SELECT S_STUDENT_MASTER.PK_STUDENT_MASTER,PK_REPRESENTATIVE, S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT, CONCAT(S_STUDENT_MASTER.LAST_NAME,', ', S_STUDENT_MASTER.FIRST_NAME) AS NAME,S_STUDENT_MASTER.ARCHIVED,PK_STUDENT_STATUS_MASTER, STUDENT_ID, S_TERM_MASTER.BEGIN_DATE,STUDENT_STATUS, M_CAMPUS_PROGRAM.CODE AS PROGRAM, EMAIL, CAMPUS_CODE,S_COURSE_OFFERING.CO_EXTERNAL_ID AS EXTERNAL_ID, S_STUDENT_ACADEMICS.STUDENT_ID AS STUDENT_ID, S_STUDENT_CONTACT.EMAIL AS EMAIL
FROM 
S_STUDENT_MASTER
LEFT JOIN S_STUDENT_CONTACT ON S_STUDENT_CONTACT.PK_STUDENT_MASTER = S_STUDENT_MASTER.PK_STUDENT_MASTER AND PK_STUDENT_CONTACT_TYPE_MASTER = 1 
, S_STUDENT_ACADEMICS, S_STUDENT_ENROLLMENT 
LEFT JOIN S_STUDENT_CAMPUS ON S_STUDENT_CAMPUS.PK_STUDENT_ENROLLMENT = S_STUDENT_ENROLLMENT.PK_STUDENT_ENROLLMENT 
LEFT JOIN M_CAMPUS_PROGRAM ON M_CAMPUS_PROGRAM.PK_CAMPUS_PROGRAM = S_STUDENT_ENROLLMENT.PK_CAMPUS_PROGRAM 
LEFT JOIN M_STUDENT_STATUS ON M_STUDENT_STATUS.PK_STUDENT_STATUS = S_STUDENT_ENROLLMENT.PK_STUDENT_STATUS
, S_STUDENT_COURSE, S_COURSE_OFFERING  
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
$table
WHERE " . $where ." GROUP BY S_STUDENT_MASTER.PK_STUDENT_MASTER order by $sort $order " ;
//echo $query;exit;	
$_SESSION['query_canvas_send_student'] = $query;
$rs = mysql_query($query. " limit $offset,$rows")or die(mysql_error());	
	
$items = array();
$i = 0;
while($row = mysql_fetch_array($rs)){

	// $CAMPUS = "";
	// $res_campus = $db->Execute("SELECT CAMPUS_CODE FROM S_CAMPUS, S_STUDENT_CAMPUS WHERE S_CAMPUS.PK_CAMPUS = S_STUDENT_CAMPUS.PK_CAMPUS  AND PK_STUDENT_ENROLLMENT = '".$row['PK_STUDENT_ENROLLMENT']."' ");
	// while (!$res_campus->EOF) { 
	// 	if($CAMPUS != '')
	// 		$CAMPUS .= ', ';
			
	// 	$CAMPUS .= $res_campus->fields['CAMPUS_CODE'];
	// 	$res_campus->MoveNext();
	// }
	// $row['CAMPUS'] = $CAMPUS;
	
	if($row['BEGIN_DATE'] != '0000-00-00' && $row['BEGIN_DATE'] != '')
		$row['BEGIN_DATE'] = date("m/d/Y",strtotime($row['BEGIN_DATE']));
	else
		$row['BEGIN_DATE'] = '';
	
	$row['ACTION'] = '<input type="checkbox" name="CHK_PK_STUDENT_MASTER[]" id="CHK_PK_STUDENT_MASTER_'.$row['PK_STUDENT_MASTER'].'" value="'.$row['PK_STUDENT_MASTER'].'" onchange="show_btn()" >';
	
	$row['NAME'] = $row['NAME'].'<input type="hidden" name="CHK_EXTERNAL_ID[]" id="CHK_EXTERNAL_ID_'.$row['EXTERNAL_ID'].'" value="'.$row['EXTERNAL_ID'].'" >'; //DIAM-1471
	
	$PK_STUDENT_MASTER = $row['PK_STUDENT_MASTER'];
	$res1 = $db->Execute("SELECT SUCCESS, S_STUDENT_MASTER_CANVAS.CREATED_ON, CONCAT(LAST_NAME,', ',FIRST_NAME) as NAME,MESSAGE FROM S_STUDENT_MASTER_CANVAS LEFT JOIN Z_USER ON Z_USER.PK_USER = S_STUDENT_MASTER_CANVAS.CREATED_BY AND PK_USER_TYPE IN (1,2) LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = Z_USER.ID WHERE  PK_STUDENT_MASTER = '$PK_STUDENT_MASTER' ORDER BY S_STUDENT_MASTER_CANVAS.CREATED_ON DESC ");	
	
	if($res1->RecordCount() == 0){
		$row['SENT'] 		= 'N';
		$row['SENT_ON'] 	= '';
		$row['SENT_BY'] 	= '';
		$row['MESSAGE'] 	= '';
	} else {
		//if($res1->fields['SUCCESS'] == 1)
			$row['SENT'] = 'Y';
		/*else
			$row['SENT'] = 'N';*/
			
		$row['SENT_ON'] = convert_to_user_date($res1->fields['CREATED_ON'],'m/d/Y h:i A',$res_tz->fields['TIMEZONE'],date_default_timezone_get());
		$row['SENT_BY'] = $res1->fields['NAME'];
		$row['MESSAGE'] = $res1->fields['MESSAGE'];
	}
	
	array_push($items, $row);
	$i++;
}
$result["rows"] = $items;
echo json_encode($result);