<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_REGISTRAR') == 0 ){
	header("location:../index");
	exit;
}

$timezone = $_SESSION['PK_TIMEZONE'];
if($timezone == '' || $timezone == 0) {
	$res = $db->Execute("SELECT PK_TIMEZONE FROM Z_ACCOUNT WHERE  PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	$timezone = $res->fields['PK_TIMEZONE'];
	if($timezone == '' || $timezone == 0)
		$timezone = 4;
}

$res_tz = $db->Execute("SELECT TIMEZONE FROM Z_TIMEZONE WHERE  PK_TIMEZONE = '$timezone' ");

$page = isset($_POST['page']) ? intval($_POST['page']) : 1;
$rows = isset($_POST['rows']) ? intval($_POST['rows']) : 10;
$sort = isset($_POST['sort']) ? strval($_POST['sort']) : 'CAMPUS_CODE ASC, BEGIN_DATE DESC, COURSE_CODE ASC, SESSION ASC, SESSION_NO ASC ';  
$order = isset($_POST['order']) ? strval($_POST['order']) : '';

$PK_CAMPUS 			= isset($_REQUEST['PK_CAMPUS']) ? ($_REQUEST['PK_CAMPUS']) : '';
$PK_TERM_MASTER 	= isset($_REQUEST['PK_TERM_MASTER']) ? ($_REQUEST['PK_TERM_MASTER']) : '';
$PK_COURSE 			= isset($_REQUEST['PK_COURSE']) ? ($_REQUEST['PK_COURSE']) : '';

$PK_SESSION 		= isset($_REQUEST['PK_SESSION']) ? ($_REQUEST['PK_SESSION']) : '';
$INSTRUCTOR 		= isset($_REQUEST['INSTRUCTOR']) ? ($_REQUEST['INSTRUCTOR']) : '';
$SENT 				= isset($_REQUEST['SENT']) ? ($_REQUEST['SENT']) : '';
$MESSAGE_TYPE 		= isset($_REQUEST['MESSAGE_TYPE']) ? ($_REQUEST['MESSAGE_TYPE']) : '';
$SEARCH 			= isset($_REQUEST['SEARCH']) ? mysql_real_escape_string($_REQUEST['SEARCH']) : '';

$offset = ($page-1)*$rows;
	
$result = array();

$where = " S_COURSE_OFFERING.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' AND S_COURSE_OFFERING.LMS_ACTIVE = 1 AND S_TERM_MASTER.LMS_ACTIVE = 1 AND S_COURSE_OFFERING_ETHINK.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_COURSE_OFFERING_ETHINK.ETHINK_ID != '' AND S_COURSE_OFFERING_ETHINK.SUCCESS = 1 ";
	
if($SEARCH != '')
	$where .= " AND (COURSE_CODE like '%$SEARCH%' OR CAMPUS_CODE LIKE '%$SEARCH%' OR DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE,'%m/%d/%Y') LIKE '%$SEARCH%' OR CONCAT(S_EMPLOYEE_MASTER.FIRST_NAME,' ',S_EMPLOYEE_MASTER.LAST_NAME) LIKE '%$SEARCH%' OR SESSION LIKE '%$SEARCH%' OR LMS_CODE LIKE '%$SEARCH%' OR S_EMPLOYEE_MASTER.FIRST_NAME LIKE '%$SEARCH%' OR S_EMPLOYEE_MASTER.LAST_NAME LIKE '%$SEARCH%' )";

if(!empty($PK_CAMPUS) != '')
	$where .= " AND S_COURSE_OFFERING.PK_CAMPUS IN (".implode(",",$PK_CAMPUS).") ";
	
if(!empty($PK_TERM_MASTER) != '')
	$where .= " AND S_COURSE_OFFERING.PK_TERM_MASTER IN (".implode(",",$PK_TERM_MASTER).") ";
	
if(!empty($PK_COURSE) != '')
	$where .= " AND S_COURSE_OFFERING.PK_COURSE IN (".implode(",",$PK_COURSE).") ";
	
if(!empty($PK_SESSION) != '')
	$where .= " AND S_COURSE_OFFERING.PK_SESSION IN (".implode(",",$PK_SESSION).") ";
	
if(!empty($INSTRUCTOR) != '') {
	$where1 = " AND S_COURSE_OFFERING.INSTRUCTOR IN (".implode(",",$INSTRUCTOR).") ";
	$where2 = " AND S_COURSE_OFFERING_ASSISTANT.ASSISTANT IN (".implode(",",$INSTRUCTOR).") ";
	$where3 = " AND PK_EMPLOYEE_MASTER_1 IN (".implode(",",$INSTRUCTOR).") ";
}
	
if($SENT == 1)
	$where4 = " AND PK_EMPLOYEE_MASTER_1 IN (SELECT PK_EMPLOYEE_MASTER FROM S_EMPLOYEE_MASTER_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
else if($SENT == 2)
	$where4 = " AND PK_EMPLOYEE_MASTER_1 NOT IN (SELECT PK_EMPLOYEE_MASTER FROM S_EMPLOYEE_MASTER_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
	
$table = "";
if($MESSAGE_TYPE == 1) {
	$table = ", S_EMPLOYEE_COURSE_ETHINK";
	$where .= " AND S_EMPLOYEE_COURSE_ETHINK.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_EMPLOYEE_COURSE_ETHINK.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND PK_EMPLOYEE_COURSE_ETHINK IN (SELECT MAX(PK_EMPLOYEE_COURSE_ETHINK)  FROM S_EMPLOYEE_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_COURSE_OFFERING, PK_EMPLOYEE_MASTER ) AND S_EMPLOYEE_COURSE_ETHINK.SUCCESS = 1 ";
} else if($MESSAGE_TYPE == 2) { 
	$table = ", S_EMPLOYEE_COURSE_ETHINK";
	$where .= " AND S_EMPLOYEE_COURSE_ETHINK.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_EMPLOYEE_COURSE_ETHINK.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND PK_EMPLOYEE_COURSE_ETHINK IN (SELECT MAX(PK_EMPLOYEE_COURSE_ETHINK)  FROM S_EMPLOYEE_COURSE_ETHINK WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_COURSE_OFFERING, PK_EMPLOYEE_MASTER ) AND S_EMPLOYEE_COURSE_ETHINK.SUCCESS != 1  ";
}

$rs = mysql_query("SELECT * FROM (SELECT S_COURSE_OFFERING.PK_COURSE_OFFERING, S_COURSE_OFFERING.INSTRUCTOR as PK_EMPLOYEE_MASTER_1 FROM 
S_COURSE_OFFERING 
LEFT JOIN M_COURSE_OFFERING_STATUS ON M_COURSE_OFFERING_STATUS.PK_COURSE_OFFERING_STATUS = S_COURSE_OFFERING.PK_COURSE_OFFERING_STATUS 
LEFT JOIN M_CAMPUS_ROOM ON M_CAMPUS_ROOM.PK_CAMPUS_ROOM = S_COURSE_OFFERING.PK_CAMPUS_ROOM  
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
, S_EMPLOYEE_MASTER, S_COURSE_OFFERING_ETHINK $table WHERE " . $where." ".$where1." AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_COURSE_OFFERING.INSTRUCTOR 
UNION 
SELECT  S_COURSE_OFFERING.PK_COURSE_OFFERING,S_COURSE_OFFERING_ASSISTANT.ASSISTANT as PK_EMPLOYEE_MASTER_1 FROM 
S_COURSE_OFFERING 
LEFT JOIN M_COURSE_OFFERING_STATUS ON M_COURSE_OFFERING_STATUS.PK_COURSE_OFFERING_STATUS = S_COURSE_OFFERING.PK_COURSE_OFFERING_STATUS 
LEFT JOIN M_CAMPUS_ROOM ON M_CAMPUS_ROOM.PK_CAMPUS_ROOM = S_COURSE_OFFERING.PK_CAMPUS_ROOM  
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
, S_EMPLOYEE_MASTER, S_COURSE_OFFERING_ASSISTANT, S_COURSE_OFFERING_ETHINK $table WHERE " . $where." ".$where2." AND S_COURSE_OFFERING_ASSISTANT.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING 
) AS TEMP WHERE 1 = 1 $where4 ")or die(mysql_error());
$row = mysql_fetch_row($rs);
$result["total"] = mysql_num_rows($rs);
	
$fields = " S_COURSE_OFFERING.PK_COURSE_OFFERING,COURSE_CODE, LMS_CODE, IF(S_TERM_MASTER.BEGIN_DATE != '0000-00-00',DATE_FORMAT(S_TERM_MASTER.BEGIN_DATE,'%m/%d/%Y'),'') AS BEGIN_DATE, CAMPUS_CODE ,CONCAT(S_EMPLOYEE_MASTER.LAST_NAME,', ',S_EMPLOYEE_MASTER.FIRST_NAME) AS INSTRUCTOR_NAME,CONCAT(SESSION,' - ',SESSION_NO) as SESSION , CONCAT(ROOM_NO,' - ', ROOM_DESCRIPTION) AS ROOM_NO, IF(S_COURSE_OFFERING.ACTIVE = 1,'<i class=\'fa fa-square round_green icon_size_active\' ></i>','<i class=\'fa fa-square round_red icon_size_active\' ></i>') AS ACTIVE, COURSE_OFFERING_STATUS, SESSION_NO, S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER ";
$query = "SELECT * FROM (SELECT $fields , S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER as PK_EMPLOYEE_MASTER_1 FROM 
S_COURSE_OFFERING 
LEFT JOIN M_COURSE_OFFERING_STATUS ON M_COURSE_OFFERING_STATUS.PK_COURSE_OFFERING_STATUS = S_COURSE_OFFERING.PK_COURSE_OFFERING_STATUS 
LEFT JOIN M_CAMPUS_ROOM ON M_CAMPUS_ROOM.PK_CAMPUS_ROOM = S_COURSE_OFFERING.PK_CAMPUS_ROOM  
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
, S_EMPLOYEE_MASTER, S_COURSE_OFFERING_ETHINK $table WHERE " . $where." ".$where1." AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_COURSE_OFFERING.INSTRUCTOR 
UNION 
SELECT $fields , S_COURSE_OFFERING_ASSISTANT.ASSISTANT as PK_EMPLOYEE_MASTER_1 FROM 
S_COURSE_OFFERING 
LEFT JOIN M_COURSE_OFFERING_STATUS ON M_COURSE_OFFERING_STATUS.PK_COURSE_OFFERING_STATUS = S_COURSE_OFFERING.PK_COURSE_OFFERING_STATUS 
LEFT JOIN M_CAMPUS_ROOM ON M_CAMPUS_ROOM.PK_CAMPUS_ROOM = S_COURSE_OFFERING.PK_CAMPUS_ROOM  
LEFT JOIN S_COURSE ON S_COURSE_OFFERING.PK_COURSE = S_COURSE.PK_COURSE 
LEFT JOIN S_TERM_MASTER ON S_TERM_MASTER.PK_TERM_MASTER = S_COURSE_OFFERING.PK_TERM_MASTER 
LEFT JOIN M_SESSION ON M_SESSION.PK_SESSION = S_COURSE_OFFERING.PK_SESSION 
LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_COURSE_OFFERING.PK_CAMPUS 
, S_COURSE_OFFERING_ASSISTANT, S_EMPLOYEE_MASTER, S_COURSE_OFFERING_ETHINK $table WHERE " . $where." ".$where2." AND S_COURSE_OFFERING_ASSISTANT.PK_COURSE_OFFERING = S_COURSE_OFFERING.PK_COURSE_OFFERING AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = S_COURSE_OFFERING_ASSISTANT.ASSISTANT ) AS TEMP WHERE 1 = 1 $where4 order by $sort $order " ;
//echo $query;exit;	
$_SESSION['query'] = $query;
$rs = mysql_query($query. " limit $offset,$rows")or die(mysql_error());	
	
$items = array();
while($row = mysql_fetch_array($rs)){

	$PK_COURSE_OFFERING = $row['PK_COURSE_OFFERING'];
	$PK_EMPLOYEE_MASTER = $row['PK_EMPLOYEE_MASTER'];
	$res1 = $db->Execute("SELECT SUCCESS, S_EMPLOYEE_COURSE_ETHINK.CREATED_ON, CONCAT(LAST_NAME,', ',FIRST_NAME) as NAME,MESSAGE FROM S_EMPLOYEE_COURSE_ETHINK LEFT JOIN Z_USER ON Z_USER.PK_USER = S_EMPLOYEE_COURSE_ETHINK.CREATED_BY AND PK_USER_TYPE IN (1,2) LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = Z_USER.ID WHERE  PK_COURSE_OFFERING = '$PK_COURSE_OFFERING' AND S_EMPLOYEE_COURSE_ETHINK.PK_EMPLOYEE_MASTER = '$PK_EMPLOYEE_MASTER' ORDER BY PK_EMPLOYEE_COURSE_ETHINK DESC ");	
	
	if($res1->RecordCount() == 0){
		$row['SENT'] 		= 'N';
		$row['SENT_ON'] 	= '';
		$row['SENT_BY'] 	= '';
		$row['MESSAGE'] 	= '';
	} else {
		//if($res1->fields['SUCCESS'] == 1)
			$row['SENT'] = 'Y';
		/*else
			$row['SENT'] = 'N';*/
			
		$row['SENT_ON'] = convert_to_user_date($res1->fields['CREATED_ON'],'m/d/Y h:i A',$res_tz->fields['TIMEZONE'],date_default_timezone_get());
		$row['SENT_BY'] = $res1->fields['NAME'];
		$row['MESSAGE'] = $res1->fields['MESSAGE'];
	}

	$row['ACTION'] = '<input type="checkbox" checked name="PK_COURSE_OFFERING[]" id="PK_COURSE_OFFERING_'.$row['PK_COURSE_OFFERING'].'_'.$row['PK_EMPLOYEE_MASTER'].'" value="'.$row['PK_COURSE_OFFERING'].'_'.$row['PK_EMPLOYEE_MASTER'].'" onclick="show_btn()" >';
	
	array_push($items, $row);
}
$result["rows"] = $items;
echo json_encode($result);