<? require_once("../global/config.php"); 
require_once("../language/common.php");
require_once("check_access.php");

if(check_access('MANAGEMENT_REGISTRAR') == 0 ){
	header("location:../index");
	exit;
}

$timezone = $_SESSION['PK_TIMEZONE'];
if($timezone == '' || $timezone == 0) {
	$res = $db->Execute("SELECT PK_TIMEZONE FROM Z_ACCOUNT WHERE  PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ");
	$timezone = $res->fields['PK_TIMEZONE'];
	if($timezone == '' || $timezone == 0)
		$timezone = 4;
}

$res_tz = $db->Execute("SELECT TIMEZONE FROM Z_TIMEZONE WHERE  PK_TIMEZONE = '$timezone' ");

$page = isset($_POST['page']) ? intval($_POST['page']) : 1;
$rows = isset($_POST['rows']) ? intval($_POST['rows']) : 10;
$sort = isset($_POST['sort']) ? strval($_POST['sort']) : " CAMPUS_CODE ASC, S_EMPLOYEE_MASTER.LAST_NAME ASC, S_EMPLOYEE_MASTER.FIRST_NAME ASC, S_EMPLOYEE_MASTER_CANVAS.CREATED_ON ASC";  
$order = isset($_POST['order']) ? strval($_POST['order']) : '';

$PK_CAMPUS 			= isset($_REQUEST['PK_CAMPUS']) ? ($_REQUEST['PK_CAMPUS']) : '';
$SENT 				= isset($_REQUEST['SENT']) ? ($_REQUEST['SENT']) : '';
$MESSAGE_TYPE 		= isset($_REQUEST['MESSAGE_TYPE']) ? ($_REQUEST['MESSAGE_TYPE']) : '';
$SEARCH 			= isset($_REQUEST['SEARCH']) ? mysql_real_escape_string($_REQUEST['SEARCH']) : '';

$offset = ($page-1)*$rows;

$PK_EMPLOYEE_MASTER		= isset($_REQUEST['PK_EMPLOYEE_MASTER']) ? ($_REQUEST['PK_EMPLOYEE_MASTER']) : '';

$where = "";
if($SEARCH != '')
{
	$where .= " AND (CAMPUS_CODE LIKE '%$SEARCH%' OR CONCAT(S_EMPLOYEE_MASTER.FIRST_NAME,' ',S_EMPLOYEE_MASTER.LAST_NAME) LIKE '%$SEARCH%' OR S_EMPLOYEE_MASTER.FIRST_NAME LIKE '%$SEARCH%' OR S_EMPLOYEE_MASTER.LAST_NAME LIKE '%$SEARCH%' )";
}

if(!empty($PK_CAMPUS) != '')
{
	$where .= " AND S_EMPLOYEE_CAMPUS.PK_CAMPUS IN (".implode(",",$PK_CAMPUS).") ";
}

if(!empty($PK_EMPLOYEE_MASTER))
{
	$PK_EMPLOYEE_MASTER = implode(",",$PK_EMPLOYEE_MASTER);
	$where .= " AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER IN (".$PK_EMPLOYEE_MASTER.") ";
}

if($SENT == 1)
{
	$where .= " AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER  IN (SELECT PK_EMPLOYEE_MASTER FROM S_EMPLOYEE_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
}
else if($SENT == 2)
{
	$where .= " AND S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER  NOT IN (SELECT PK_EMPLOYEE_MASTER FROM S_EMPLOYEE_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' ) ";
}
	
$table = "";
if($MESSAGE_TYPE == 1) {
	$table = ", S_EMPLOYEE_MASTER_CANVAS";
	$where .= " AND S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND PK_EMPLOYEE_MASTER_CANVAS IN (SELECT MAX(PK_EMPLOYEE_MASTER_CANVAS)  FROM S_EMPLOYEE_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_EMPLOYEE_MASTER ) AND S_EMPLOYEE_MASTER_CANVAS.SUCCESS = 1 ";
} else if($MESSAGE_TYPE == 2) { 
	$table = ", S_EMPLOYEE_MASTER_CANVAS";
	$where .= " AND S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER AND PK_EMPLOYEE_MASTER_CANVAS IN (SELECT MAX(PK_EMPLOYEE_MASTER_CANVAS)  FROM S_EMPLOYEE_MASTER_CANVAS WHERE PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' GROUP BY PK_EMPLOYEE_MASTER ) AND S_EMPLOYEE_MASTER_CANVAS.SUCCESS != 1  ";
}
	
$result = array();
$sQuery_Cnt = "SELECT 
					DISTINCT(S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER)
					FROM 
						S_EMPLOYEE_MASTER 
						LEFT JOIN S_EMPLOYEE_MASTER_CANVAS ON S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER 
						-- LEFT JOIN S_EMPLOYEE_COURSE_CANVAS ON S_EMPLOYEE_COURSE_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER 
						-- LEFT JOIN S_COURSE_OFFERING ON S_COURSE_OFFERING.PK_COURSE_OFFERING = S_EMPLOYEE_COURSE_CANVAS.PK_COURSE_OFFERING 
						LEFT JOIN S_EMPLOYEE_CAMPUS ON S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER
						LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_EMPLOYEE_CAMPUS.PK_CAMPUS
					WHERE 
						S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' 
						AND S_EMPLOYEE_MASTER.IS_FACULTY = 1 AND S_EMPLOYEE_MASTER.ACTIVE =1
						$where 
					GROUP BY 
						S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER"; //DIAM-2120 > DIAM-2105

$rs = mysql_query($sQuery_Cnt) or die(mysql_error());
$row = mysql_fetch_row($rs);
$result["total"] = mysql_num_rows($rs);

$sQuery_Final = "SELECT S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER
						,S_EMPLOYEE_MASTER.EMAIL AS EMAIL
						,CONCAT(S_EMPLOYEE_MASTER.LAST_NAME, ', ', S_EMPLOYEE_MASTER.FIRST_NAME) AS INSTRUCTOR_NAME 
					FROM 
						S_EMPLOYEE_MASTER 
						LEFT JOIN S_EMPLOYEE_MASTER_CANVAS ON S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER 
						-- LEFT JOIN S_EMPLOYEE_COURSE_CANVAS ON S_EMPLOYEE_COURSE_CANVAS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER 
						-- LEFT JOIN S_COURSE_OFFERING ON S_COURSE_OFFERING.PK_COURSE_OFFERING = S_EMPLOYEE_COURSE_CANVAS.PK_COURSE_OFFERING 
						LEFT JOIN S_EMPLOYEE_CAMPUS ON S_EMPLOYEE_CAMPUS.PK_EMPLOYEE_MASTER = S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER
						LEFT JOIN S_CAMPUS ON S_CAMPUS.PK_CAMPUS = S_EMPLOYEE_CAMPUS.PK_CAMPUS
					WHERE 
						S_EMPLOYEE_MASTER.PK_ACCOUNT = '$_SESSION[PK_ACCOUNT]' 
						AND S_EMPLOYEE_MASTER.IS_FACULTY = 1 AND S_EMPLOYEE_MASTER.ACTIVE =1
						$where
					GROUP BY 
						S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER
					ORDER BY 
						$sort $order "; //DIAM-2120 > DIAM-2105

// echo $sQuery_Final;exit;	
$_SESSION['query'] = $sQuery_Final;
$rs = mysql_query($sQuery_Final. " limit $offset,$rows")or die(mysql_error());	
	
$items = array();
$i = 0;
while($row = mysql_fetch_array($rs)){

	$PK_EMPLOYEE_MASTER = $row['PK_EMPLOYEE_MASTER'];
	$res1 = $db->Execute("SELECT SUCCESS, S_EMPLOYEE_MASTER_CANVAS.CREATED_ON, CONCAT(LAST_NAME,', ',FIRST_NAME) as NAME,MESSAGE FROM S_EMPLOYEE_MASTER_CANVAS LEFT JOIN Z_USER ON Z_USER.PK_USER = S_EMPLOYEE_MASTER_CANVAS.CREATED_BY AND PK_USER_TYPE IN (1,2) LEFT JOIN S_EMPLOYEE_MASTER ON S_EMPLOYEE_MASTER.PK_EMPLOYEE_MASTER = Z_USER.ID WHERE  S_EMPLOYEE_MASTER_CANVAS.PK_EMPLOYEE_MASTER = '$PK_EMPLOYEE_MASTER' ORDER BY S_EMPLOYEE_MASTER_CANVAS.CREATED_ON DESC ");	

	$res_campus = $db->Execute("SELECT GROUP_CONCAT(CAMPUS_CODE) AS CAMPUS_CODE FROM S_CAMPUS, S_EMPLOYEE_CAMPUS WHERE S_CAMPUS.PK_CAMPUS = S_EMPLOYEE_CAMPUS.PK_CAMPUS  AND PK_EMPLOYEE_MASTER = '".$row['PK_EMPLOYEE_MASTER']."' ORDER BY CAMPUS_CODE ASC ");

	$row['CAMPUS_CODE'] = $res_campus->fields['CAMPUS_CODE'];
	
	if($res1->RecordCount() == 0){
		$row['SENT'] 		= 'N';
		$row['SENT_ON'] 	= '';
		$row['SENT_BY'] 	= '';
		$row['MESSAGE'] 	= '';
	} else {
		//if($res1->fields['SUCCESS'] == 1)
			$row['SENT'] = 'Y';
		/*else
			$row['SENT'] = 'N';*/
			
		$row['SENT_ON'] = convert_to_user_date($res1->fields['CREATED_ON'],'m/d/Y h:i A',$res_tz->fields['TIMEZONE'],date_default_timezone_get());
		$row['SENT_BY'] = $res1->fields['NAME'];
		$row['MESSAGE'] = $res1->fields['MESSAGE'];
	}

	$row['ACTION'] = '<input type="checkbox" name="PK_EMPLOYEE_MASTER[]" id="PK_TERM_MASTER_'.$row['PK_EMPLOYEE_MASTER'].'" value="'.$row['PK_EMPLOYEE_MASTER'].'" onclick="show_btn()" >';
	
	array_push($items, $row);
	$i++;
}
$result["rows"] = $items;
echo json_encode($result);
