<? require_once("../global/config.php"); 
require_once("../language/common.php");

$PK_ACCOUNT = 57;
$SINGLE_PK_USER ='';
//$SINGLE_PK_USER = " AND S_STUDENT_COURSE.PK_STUDENT_MASTER='175'";

$sql = "SELECT  S_STUDENT_COURSE.PK_STUDENT_MASTER,S_STUDENT_COURSE.PK_STUDENT_COURSE, CONCAT(S_STUDENT_MASTER.FIRST_NAME,'_',S_STUDENT_MASTER.LAST_NAME) AS NAME, 
S_STUDENT_MASTER.CONVERSION_ID AS STUDENT_CONVERSION_ID ,S_STUDENT_COURSE.PK_COURSE_OFFERING , S_STUDENT_COURSE.CONVERSION_ID AS COURSE_CONVERSION_ID, S_STUDENT_COURSE.FINAL_GRADE FROM S_STUDENT_COURSE 
LEFT JOIN S_COURSE_OFFERING ON S_COURSE_OFFERING.PK_COURSE_OFFERING = S_STUDENT_COURSE.PK_COURSE_OFFERING 
LEFT JOIN S_GRADE ON S_GRADE.PK_GRADE = S_STUDENT_COURSE.FINAL_GRADE 
LEFT JOIN S_STUDENT_MASTER ON S_STUDENT_MASTER.PK_STUDENT_MASTER=S_STUDENT_COURSE.PK_STUDENT_MASTER
WHERE S_STUDENT_COURSE.PK_ACCOUNT = 57 AND S_STUDENT_COURSE.FINAL_GRADE=0 GROUP BY S_STUDENT_COURSE.PK_STUDENT_COURSE
ORDER BY S_STUDENT_COURSE.PK_STUDENT_MASTER ASC";

/*
$sql = "SELECT  S_STUDENT_COURSE.PK_STUDENT_MASTER, CONCAT(S_STUDENT_MASTER.FIRST_NAME,'_',S_STUDENT_MASTER.LAST_NAME) AS NAME, 
S_STUDENT_MASTER.CONVERSION_ID AS STUDENT_CONVERSION_ID ,S_STUDENT_COURSE.PK_COURSE_OFFERING , S_STUDENT_COURSE.CONVERSION_ID AS COURSE_CONVERSION_ID, S_STUDENT_COURSE.FINAL_GRADE FROM S_STUDENT_COURSE 
LEFT JOIN S_COURSE_OFFERING ON S_COURSE_OFFERING.PK_COURSE_OFFERING = S_STUDENT_COURSE.PK_COURSE_OFFERING 
LEFT JOIN S_GRADE ON S_GRADE.PK_GRADE = S_STUDENT_COURSE.FINAL_GRADE 
LEFT JOIN S_STUDENT_MASTER ON S_STUDENT_MASTER.PK_STUDENT_MASTER=S_STUDENT_COURSE.PK_STUDENT_MASTER
WHERE S_STUDENT_COURSE.PK_ACCOUNT = 57 AND S_STUDENT_COURSE.EDITED_BY=3915 AND S_STUDENT_COURSE.CONVERSION_ID !='' GROUP BY S_STUDENT_COURSE.PK_STUDENT_COURSE
ORDER BY S_STUDENT_COURSE.PK_STUDENT_MASTER ASC LIMIT 500 ";*/

$res = $db->Execute($sql); 

echo "<b><hr/></b><br/>";
echo "Total Record Count = ". $res->RecordCount();
echo "<br/>";
echo "ACCOUNT ID = ".$PK_ACCOUNT; 
echo "<b><hr/></b><br/>";
?>
<table border=1>
	<thead>
	<th>SR. NO</th>
		<th>PK_STUDENT_MASTER</th>
		<th>NAME</th>
		<th>PK_COURSE_OFFERING</th>
		<th>Final Grade</th>

		<th>PK_STUDENT_MASTER UAT</th>
		<th>NAME UAT</th>
		<th>PK_COURSE_OFFERING UAT</th>
		<th>Final Grade UAT</th>

</thead>
  </tbody>
<?
$i=1;

while (!$res->EOF) { 

	// $sql_uat_student="SELECT CONCAT(SSM.FIRST_NAME,'_',SSM.LAST_NAME) as NAME,SSM.PK_STUDENT_MASTER AS PK_STUDENT_MASTER FROM S_STUDENT_MASTER_UAT_74 SSM WHERE SSM.CONVERSION_ID='".$res->fields['STUDENT_CONVERSION_ID']."'";
	//  //exit;
	// $sql_uat = $db->Execute($sql_uat_student);
	if($res->fields['PK_STUDENT_MASTER']!=""){

	//  $sql_uat_student="SELECT S_STUDENT_COURSE_UAT_74.PK_STUDENT_MASTER, CONCAT(S_STUDENT_MASTER_UAT_74.FIRST_NAME,'_',S_STUDENT_MASTER_UAT_74.LAST_NAME) AS NAME, 
	// S_STUDENT_MASTER_UAT_74.CONVERSION_ID AS STUDENT_CONVERSION_ID ,S_STUDENT_COURSE_UAT_74.PK_COURSE_OFFERING
	// , S_STUDENT_COURSE_UAT_74.FINAL_GRADE FROM S_STUDENT_COURSE_UAT_74 
	// LEFT JOIN S_COURSE_OFFERING_UAT_74 ON S_COURSE_OFFERING_UAT_74.PK_COURSE_OFFERING = S_STUDENT_COURSE_UAT_74.PK_COURSE_OFFERING 
	// LEFT JOIN S_GRADE_UAT_74 ON S_GRADE_UAT_74.PK_GRADE = S_STUDENT_COURSE_UAT_74.FINAL_GRADE 
	// LEFT JOIN S_STUDENT_MASTER_UAT_74 ON S_STUDENT_MASTER_UAT_74.PK_STUDENT_MASTER=S_STUDENT_COURSE_UAT_74.PK_STUDENT_MASTER
	// WHERE S_STUDENT_COURSE_UAT_74.PK_ACCOUNT = 57 
	// AND S_STUDENT_COURSE_UAT_74.PK_STUDENT_MASTER='".$res->fields['PK_STUDENT_MASTER']."'
	// AND S_STUDENT_COURSE_UAT_74.PK_COURSE_OFFERING='".$res->fields['PK_COURSE_OFFERING']."'
	// AND S_STUDENT_COURSE_UAT_74.PK_STUDENT_COURSE = '".$res->fields['PK_STUDENT_COURSE']."'
	// ORDER BY S_STUDENT_COURSE_UAT_74.PK_STUDENT_MASTER ASC";
	$sql_uat_student="SELECT S_STUDENT_COURSE_26.PK_STUDENT_MASTER, CONCAT(S_STUDENT_MASTER.FIRST_NAME,'_',S_STUDENT_MASTER.LAST_NAME) AS NAME, 
	S_STUDENT_MASTER.CONVERSION_ID AS STUDENT_CONVERSION_ID ,S_STUDENT_COURSE_26.PK_COURSE_OFFERING
	, S_STUDENT_COURSE_26.FINAL_GRADE FROM S_STUDENT_COURSE_26 
	LEFT JOIN S_STUDENT_MASTER ON S_STUDENT_MASTER.PK_STUDENT_MASTER=S_STUDENT_COURSE_26.PK_STUDENT_MASTER
	WHERE S_STUDENT_COURSE_26.PK_ACCOUNT = 57 
	AND S_STUDENT_COURSE_26.PK_STUDENT_MASTER='".$res->fields['PK_STUDENT_MASTER']."'
	AND S_STUDENT_COURSE_26.PK_COURSE_OFFERING='".$res->fields['PK_COURSE_OFFERING']."'
	AND S_STUDENT_COURSE_26.PK_STUDENT_COURSE = '".$res->fields['PK_STUDENT_COURSE']."'
	ORDER BY S_STUDENT_COURSE_26.PK_STUDENT_MASTER ASC";

    $sql_uat = $db->Execute($sql_uat_student);


	// $COURSE_STRING =  $res->fields['COURSE_CODE'].'_'.substr($res->fields['SESSION'],0,1).'_'.$res->fields['SESSION_NO'].'_'.$res->fields['COURSE_DESCRIPTION'];

	echo '<tr>';
	echo '<td>'.$i.'</td>';	

	echo '<td>'.$res->fields['PK_STUDENT_MASTER'].'</td>';	
	echo '<td>'.$res->fields['NAME'].'</td>';
	echo '<td>'.$res->fields['PK_COURSE_OFFERING'].'</td>';
	echo '<td>'.$res->fields['FINAL_GRADE'].'</td>';
	echo '<td>'.$sql_uat->fields['PK_STUDENT_MASTER'].'</td>';
	echo '<td>'.$sql_uat->fields['NAME'].'</td>';
	echo '<td>'.$sql_uat->fields['PK_COURSE_OFFERING'].'</td>';
	echo '<td>'.$sql_uat->fields['FINAL_GRADE'].'</td>';

	echo '</tr>';	

	if($sql_uat->fields['FINAL_GRADE']!=0)
	{
		$UPDATE_SQL="UPDATE S_STUDENT_COURSE SET FINAL_GRADE = '".$sql_uat->fields['FINAL_GRADE']."',EDITED_BY=3915,EDITED_ON='2023-12-01 12:43:00' WHERE PK_STUDENT_MASTER = '".$res->fields['PK_STUDENT_MASTER']."'  
		AND PK_COURSE_OFFERING='".$res->fields['PK_COURSE_OFFERING']."'
		AND PK_STUDENT_COURSE = '".$res->fields['PK_STUDENT_COURSE']."' AND  PK_ACCOUNT =57"; 
		//echo $UPDATE_SQL;
	//echo "<br>";
		$db->Execute($UPDATE_SQL);

	}
}

	$i++;
	$res->MoveNext();
}
?>
  </tbody>
</table>
