<? require_once("../global/config.php"); 
$db->Execute("UPDATE Z_NOTIFICATION_RECIPIENTS SET NOTI_READ = 1 WHERE PK_NOTIFICATION_RECIPIENTS = '$_GET[id]' ");

$res_noti = $db->Execute("select LINK from Z_NOTIFICATION, Z_NOTIFICATION_RECIPIENTS WHERE Z_NOTIFICATION.PK_NOTIFICATION = Z_NOTIFICATION_RECIPIENTS.PK_NOTIFICATION AND Z_NOTIFICATION_RECIPIENTS.PK_EMPLOYEE_MASTER = '$_SESSION[PK_EMPLOYEE_MASTER]' AND PK_NOTIFICATION_RECIPIENTS = '$_GET[id]' ");
header("location:".$res_noti->fields['LINK'].'&from_noti=1');